// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

import Foundation

public struct AssortedPrimitives: Equatable {
    public var b: Bool
    public var eight: Int8
    public var sixteen: Int16
    public var thirtytwo: Int32
    public var sixtyfour: Int64
    public var fthirtytwo: Float
    public var fsixtyfour: Double
    public var oB: Optional<Bool>
    public var oEight: Optional<Int8>
    public var oSixteen: Optional<Int16>
    public var oThirtytwo: Optional<Int32>
    public var oSixtyfour: Optional<Int64>
    public var oFthirtytwo: Optional<Float>
    public var oFsixtyfour: Optional<Double>

    public init(b: Bool, eight: Int8, sixteen: Int16, thirtytwo: Int32, sixtyfour: Int64, fthirtytwo: Float, fsixtyfour: Double, oB: Optional<Bool>, oEight: Optional<Int8>, oSixteen: Optional<Int16>, oThirtytwo: Optional<Int32>, oSixtyfour: Optional<Int64>, oFthirtytwo: Optional<Float>, oFsixtyfour: Optional<Double>)
    {
        self.b = b
        self.eight = eight
        self.sixteen = sixteen
        self.thirtytwo = thirtytwo
        self.sixtyfour = sixtyfour
        self.fthirtytwo = fthirtytwo
        self.fsixtyfour = fsixtyfour
        self.oB = oB
        self.oEight = oEight
        self.oSixteen = oSixteen
        self.oThirtytwo = oThirtytwo
        self.oSixtyfour = oSixtyfour
        self.oFthirtytwo = oFthirtytwo
        self.oFsixtyfour = oFsixtyfour
    }
}
