// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

import DjinniSupport
import TestSuite

public typealias ColorMarshaller = DjinniSupport.EnumMarshaller<Color>
