// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

final class ConflictUserCppProxy: DjinniSupport.CppProxy, TestSuite.ConflictUser {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
    func Conflict() throws -> TestSuite.Conflict {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        var ret = djinni_generated.ConflictUser_Conflict(&_params)
        try handleCppErrors(&ret)
        return ConflictMarshaller.fromCpp(ret)
    }
    func conflictArg(_ cs: Array<TestSuite.Conflict>) throws -> Bool {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        _params.addValue(ListMarshaller<ConflictMarshaller>.toCpp(cs))
        var ret = djinni_generated.ConflictUser_conflictArg(&_params)
        try handleCppErrors(&ret)
        return BoolMarshaller.fromCpp(ret)
    }
}
public enum ConflictUserMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.ConflictUser
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { ConflictUserCppProxy(c) as SwiftType })
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { fatalError("n/a") })
    }
}
