// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

enum ConstantRecordMarshaller: DjinniSupport.Marshaller {
    typealias SwiftType = TestSuite.ConstantRecord
    static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return withUnsafePointer(to: c) { p in
            let someInteger = I32Marshaller.fromCpp(djinni.swift.getMember(p, 0))
            let someString = StringMarshaller.fromCpp(djinni.swift.getMember(p, 1))
            return SwiftType(someInteger: someInteger, someString: someString)
        }
    }
    static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        var ret = djinni.swift.makeCompositeValue()
        djinni.swift.addMember(&ret, I32Marshaller.toCpp(s.someInteger))
        djinni.swift.addMember(&ret, StringMarshaller.toCpp(s.someString))
        return ret
    }
}
