// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

import Foundation

public protocol DataRefTest: AnyObject {
    func sendData(_ data: Foundation.NSData) throws -> Void
    func retriveAsBin() throws -> Data
    func sendMutableData(_ data: Foundation.NSData) throws -> Void
    func generateData() throws -> Foundation.NSData
    func dataFromVec() throws -> Foundation.NSData
    func dataFromStr() throws -> Foundation.NSData
    func sendDataView(_ data: Foundation.NSData) throws -> Data
    func recvDataView() throws -> Foundation.NSData
}
