// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

import Foundation

public protocol DataRefTest: AnyObject {
    func sendData(_ data: NSData) throws -> Void
    func retriveAsBin() throws -> Data
    func sendMutableData(_ data: NSData) throws -> Void
    func generateData() throws -> NSData
    func dataFromVec() throws -> NSData
    func dataFromStr() throws -> NSData
    func sendDataView(_ data: NSData) throws -> Data
    func recvDataView() throws -> NSData
}
