// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

import Foundation

public struct EnumUsageRecord {
    public var e: TestSuite.Color
    public var o: Optional<TestSuite.Color>
    public var l: Array<TestSuite.Color>
    public var s: Set<TestSuite.Color>
    public var m: Dictionary<TestSuite.Color, TestSuite.Color>

    public init(e: TestSuite.Color, o: Optional<TestSuite.Color>, l: Array<TestSuite.Color>, s: Set<TestSuite.Color>, m: Dictionary<TestSuite.Color, TestSuite.Color>)
    {
        self.e = e
        self.o = o
        self.l = l
        self.s = s
        self.m = m
    }
}
