// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

final class EnumUsageInterfaceCppProxy: DjinniSupport.CppProxy, TestSuite.EnumUsageInterface {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
    func e(e: TestSuite.Color) throws -> TestSuite.Color {
        var params = djinni.swift.ParameterList()
        params.addValue(inst)
        params.addValue(ColorMarshaller.toCpp(e))
        var ret = djinni_generated.EnumUsageInterface_e(&params)
        try handleCppErrors(&ret)
        return ColorMarshaller.fromCpp(ret)
    }
    func o(o: Optional<TestSuite.Color>) throws -> Optional<TestSuite.Color> {
        var params = djinni.swift.ParameterList()
        params.addValue(inst)
        params.addValue(OptionalMarshaller<ColorMarshaller>.toCpp(o))
        var ret = djinni_generated.EnumUsageInterface_o(&params)
        try handleCppErrors(&ret)
        return OptionalMarshaller<ColorMarshaller>.fromCpp(ret)
    }
    func l(l: Array<TestSuite.Color>) throws -> Array<TestSuite.Color> {
        var params = djinni.swift.ParameterList()
        params.addValue(inst)
        params.addValue(ListMarshaller<ColorMarshaller>.toCpp(l))
        var ret = djinni_generated.EnumUsageInterface_l(&params)
        try handleCppErrors(&ret)
        return ListMarshaller<ColorMarshaller>.fromCpp(ret)
    }
    func s(s: Set<TestSuite.Color>) throws -> Set<TestSuite.Color> {
        var params = djinni.swift.ParameterList()
        params.addValue(inst)
        params.addValue(SetMarshaller<ColorMarshaller>.toCpp(s))
        var ret = djinni_generated.EnumUsageInterface_s(&params)
        try handleCppErrors(&ret)
        return SetMarshaller<ColorMarshaller>.fromCpp(ret)
    }
    func m(m: Dictionary<TestSuite.Color, TestSuite.Color>) throws -> Dictionary<TestSuite.Color, TestSuite.Color> {
        var params = djinni.swift.ParameterList()
        params.addValue(inst)
        params.addValue(MapMarshaller<ColorMarshaller, ColorMarshaller>.toCpp(m))
        var ret = djinni_generated.EnumUsageInterface_m(&params)
        try handleCppErrors(&ret)
        return MapMarshaller<ColorMarshaller, ColorMarshaller>.fromCpp(ret)
    }
}
enum EnumUsageInterfaceMarshaller: DjinniSupport.Marshaller {
    typealias SwiftType = TestSuite.EnumUsageInterface
    static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { EnumUsageInterfaceCppProxy(c) as SwiftType })
    }
    static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { fatalError("n/a") })
    }
}
