// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

import Foundation

/** Extended record */
public struct ExtendedRecord {
    public static let extendedRecordConst: ExtendedRecord = ExtendedRecord(
        foo:true)
    public var foo: Bool

    public init(foo: Bool)
    {
        self.foo = foo
    }
}
