// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

final class ExternInterface1CppProxy: DjinniSupport.CppProxy, TestSuite.ExternInterface1 {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
    func foo(_ i: ClientInterface) throws -> ClientReturnedRecord {
        var params = djinni.swift.ParameterList()
        params.addValue(inst)
        params.addValue(ClientInterfaceMarshaller.toCpp(i))
        var ret = djinni_generated.ExternInterface1_foo(&params)
        try handleCppErrors(&ret)
        return ClientReturnedRecordMarshaller.fromCpp(ret)
    }
    func bar(_ e: Color) throws -> Color {
        var params = djinni.swift.ParameterList()
        params.addValue(inst)
        params.addValue(ColorMarshaller.toCpp(e))
        var ret = djinni_generated.ExternInterface1_bar(&params)
        try handleCppErrors(&ret)
        return ColorMarshaller.fromCpp(ret)
    }
}
enum ExternInterface1Marshaller: DjinniSupport.Marshaller {
    typealias SwiftType = TestSuite.ExternInterface1
    static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { ExternInterface1CppProxy(c) as SwiftType })
    }
    static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { fatalError("n/a") })
    }
}
