// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

import Foundation

public protocol ExternInterface2: AnyObject {
    func foo(_ i: TestSuite.TestHelpers) throws -> TestSuite.ExternRecordWithDerivings
}
