// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

public enum ExternRecordWithDerivingsMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.ExternRecordWithDerivings
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return withUnsafePointer(to: c) { p in
            let member = TestSuite.RecordWithDerivingsMarshaller.fromCpp(djinni.swift.getMember(p, 0))
            let e = TestSuite.ColorMarshaller.fromCpp(djinni.swift.getMember(p, 1))
            return SwiftType(member: member, e: e)
        }
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        var ret = djinni.swift.makeCompositeValue()
        djinni.swift.addMember(&ret, TestSuite.RecordWithDerivingsMarshaller.toCpp(s.member))
        djinni.swift.addMember(&ret, TestSuite.ColorMarshaller.toCpp(s.e))
        return ret
    }
}
