// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

import Foundation

public struct MapListRecord {
    public var mapList: Array<Dictionary<String, Int64>>

    public init(mapList: Array<Dictionary<String, Int64>>)
    {
        self.mapList = mapList
    }
}
