// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

import Foundation

public struct NestedLazy {
    public var l: ()->T

    public init(l: ()->T)
    {
        self.l = l
    }
}
