// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

import DjinniSupport
import Foundation

public struct NestedProviderInterface {
    public var obj: DjinniSupport.Provider<TestSuite.SimpleObject>

    public init(obj: DjinniSupport.Provider<TestSuite.SimpleObject>)
    {
        self.obj = obj
    }
}
