// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuiteCxx

public enum NestedProviderMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.NestedProvider
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return withUnsafePointer(to: c) { p in
            let s = DjinniSupport.ProviderMarshaller<I32Marshaller>.fromCpp(djinni.swift.getMember(p, 0))
            return SwiftType(s: s)
        }
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        var ret = djinni.swift.makeCompositeValue()
        djinni.swift.addMember(&ret, DjinniSupport.ProviderMarshaller<I32Marshaller>.toCpp(s.s))
        return ret
    }
}
