// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

import Foundation
import ProtobufTest

public struct RecordWithEmbeddedProto {
    public var person: Djinni_Test_Person

    public init(person: Djinni_Test_Person)
    {
        self.person = person
    }
}
