// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

import Foundation

public protocol ReverseClientInterface: AnyObject {
    func returnStr() throws -> String
    func methTakingInterface(i: TestSuite.ReverseClientInterface) throws -> String
    func methTakingOptionalInterface(i: Optional<TestSuite.ReverseClientInterface>) throws -> String
}
