// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

import Foundation

/** Used for ObjC multiple inheritance tests */
public protocol SecondListener: AnyObject {
    func second() throws -> Void
}
