// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuiteCxx

/** Simple object interface for provider testing */
final class SimpleObjectCppProxy: DjinniSupport.CppProxy, TestSuite.SimpleObject {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
    func getValue() throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        var ret = djinni_generated.SimpleObject_getValue(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    func getName() throws -> String {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        var ret = djinni_generated.SimpleObject_getName(&_params)
        try handleCppErrors(&ret)
        return StringMarshaller.fromCpp(ret)
    }
}
public enum SimpleObjectMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.SimpleObject
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { SimpleObjectCppProxy(c) as SwiftType })
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { fatalError("n/a") })
    }
}
