// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

import Foundation

public struct SupportCopying {
    public var x: Int32

    public init(x: Int32)
    {
        self.x = x
    }
}
