// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuiteCxx

final class TestSupplierCppProxy: DjinniSupport.CppProxy, TestSuite.TestSupplier {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
}
public enum TestSupplierMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.TestSupplier
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { TestSupplierCppProxy(c) as SwiftType })
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { fatalError("n/a") })
    }
}
public class TestSupplier_statics {
    public static func getSupplierString() throws -> DjinniSupport.Supplier<String> {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestSupplier_getSupplierString(&_params)
        try handleCppErrors(&ret)
        return DjinniSupport.SupplierMarshaller<StringMarshaller>.fromCpp(ret)
    }
    public static func getSupplierInt() throws -> DjinniSupport.Supplier<Int32> {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestSupplier_getSupplierInt(&_params)
        try handleCppErrors(&ret)
        return DjinniSupport.SupplierMarshaller<I32Marshaller>.fromCpp(ret)
    }
    public static func callSupplierString(_ x: DjinniSupport.Supplier<String>) throws -> String {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.SupplierMarshaller<StringMarshaller>.toCpp(x))
        var ret = djinni_generated.TestSupplier_callSupplierString(&_params)
        try handleCppErrors(&ret)
        return StringMarshaller.fromCpp(ret)
    }
    public static func callSupplierInt(_ x: DjinniSupport.Supplier<Int32>) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.SupplierMarshaller<I32Marshaller>.toCpp(x))
        var ret = djinni_generated.TestSupplier_callSupplierInt(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func getNestedSupplier() throws -> TestSuite.NestedSupplier {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestSupplier_getNestedSupplier(&_params)
        try handleCppErrors(&ret)
        return NestedSupplierMarshaller.fromCpp(ret)
    }
    public static func callNestedSupplier(_ x: TestSuite.NestedSupplier) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(NestedSupplierMarshaller.toCpp(x))
        var ret = djinni_generated.TestSupplier_callNestedSupplier(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func getSupplierObject() throws -> DjinniSupport.Supplier<TestSuite.SimpleObject> {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestSupplier_getSupplierObject(&_params)
        try handleCppErrors(&ret)
        return DjinniSupport.SupplierMarshaller<SimpleObjectMarshaller>.fromCpp(ret)
    }
    public static func callSupplierObject(_ x: DjinniSupport.Supplier<TestSuite.SimpleObject>) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.SupplierMarshaller<SimpleObjectMarshaller>.toCpp(x))
        var ret = djinni_generated.TestSupplier_callSupplierObject(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func callSupplierObjectGetName(_ x: DjinniSupport.Supplier<TestSuite.SimpleObject>) throws -> String {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.SupplierMarshaller<SimpleObjectMarshaller>.toCpp(x))
        var ret = djinni_generated.TestSupplier_callSupplierObjectGetName(&_params)
        try handleCppErrors(&ret)
        return StringMarshaller.fromCpp(ret)
    }
    public static func getNestedSupplierInterface() throws -> TestSuite.NestedSupplierInterface {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestSupplier_getNestedSupplierInterface(&_params)
        try handleCppErrors(&ret)
        return NestedSupplierInterfaceMarshaller.fromCpp(ret)
    }
    public static func callNestedSupplierInterface(_ x: TestSuite.NestedSupplierInterface) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(NestedSupplierInterfaceMarshaller.toCpp(x))
        var ret = djinni_generated.TestSupplier_callNestedSupplierInterface(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func createSimpleObject(_ value: Int32, name: String) throws -> TestSuite.SimpleObject {
        var _params = djinni.swift.ParameterList()
        _params.addValue(I32Marshaller.toCpp(value))
        _params.addValue(StringMarshaller.toCpp(name))
        var ret = djinni_generated.TestSupplier_createSimpleObject(&_params)
        try handleCppErrors(&ret)
        return SimpleObjectMarshaller.fromCpp(ret)
    }
}
