// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

final class TestLazyCppProxy: DjinniSupport.CppProxy, TestSuite.TestLazy {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
}
public enum TestLazyMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.TestLazy
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { TestLazyCppProxy(c) as SwiftType })
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { fatalError("n/a") })
    }
}
public class TestLazy_statics {
    public static func getLazyString() throws -> ()->T {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestLazy_getLazyString(&_params)
        try handleCppErrors(&ret)
        return DjinniSupport.LazyMarshaller<StringMarshaller>.fromCpp(ret)
    }
    public static func getLazyInt() throws -> ()->T {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestLazy_getLazyInt(&_params)
        try handleCppErrors(&ret)
        return DjinniSupport.LazyMarshaller<I32Marshaller>.fromCpp(ret)
    }
    public static func callLazyString(_ x: ()->T) throws -> String {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.LazyMarshaller<StringMarshaller>.toCpp(x))
        var ret = djinni_generated.TestLazy_callLazyString(&_params)
        try handleCppErrors(&ret)
        return StringMarshaller.fromCpp(ret)
    }
    public static func callLazyInt(_ x: ()->T) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.LazyMarshaller<I32Marshaller>.toCpp(x))
        var ret = djinni_generated.TestLazy_callLazyInt(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func getNestedLazy() throws -> TestSuite.NestedLazy {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestLazy_getNestedLazy(&_params)
        try handleCppErrors(&ret)
        return NestedLazyMarshaller.fromCpp(ret)
    }
    public static func callNestedLazy(_ x: TestSuite.NestedLazy) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(NestedLazyMarshaller.toCpp(x))
        var ret = djinni_generated.TestLazy_callNestedLazy(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func getLazyObject() throws -> ()->T {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestLazy_getLazyObject(&_params)
        try handleCppErrors(&ret)
        return DjinniSupport.LazyMarshaller<SimpleObjectMarshaller>.fromCpp(ret)
    }
    public static func callLazyObject(_ x: ()->T) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.LazyMarshaller<SimpleObjectMarshaller>.toCpp(x))
        var ret = djinni_generated.TestLazy_callLazyObject(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func callLazyObjectGetName(_ x: ()->T) throws -> String {
        var _params = djinni.swift.ParameterList()
        _params.addValue(DjinniSupport.LazyMarshaller<SimpleObjectMarshaller>.toCpp(x))
        var ret = djinni_generated.TestLazy_callLazyObjectGetName(&_params)
        try handleCppErrors(&ret)
        return StringMarshaller.fromCpp(ret)
    }
    public static func getNestedLazyInterface() throws -> TestSuite.NestedLazyInterface {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.TestLazy_getNestedLazyInterface(&_params)
        try handleCppErrors(&ret)
        return NestedLazyInterfaceMarshaller.fromCpp(ret)
    }
    public static func callNestedLazyInterface(_ x: TestSuite.NestedLazyInterface) throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(NestedLazyInterfaceMarshaller.toCpp(x))
        var ret = djinni_generated.TestLazy_callNestedLazyInterface(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    public static func createSimpleObject(_ value: Int32, name: String) throws -> TestSuite.SimpleObject {
        var _params = djinni.swift.ParameterList()
        _params.addValue(I32Marshaller.toCpp(value))
        _params.addValue(StringMarshaller.toCpp(name))
        var ret = djinni_generated.TestLazy_createSimpleObject(&_params)
        try handleCppErrors(&ret)
        return SimpleObjectMarshaller.fromCpp(ret)
    }
}
