// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

import Foundation

public protocol VarnameInterface: AnyObject {
    /**
     * We should also rewrite parameter names in docstrings.
     * RArg should be rewritten.
     * _i_arg_ should not.
     */
    func Rmethod(RArg: TestSuite.VarnameRecord) throws -> TestSuite.VarnameRecord
    func Imethod(IArg: TestSuite.VarnameInterface) throws -> TestSuite.VarnameInterface
}
