// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.yaml

#pragma once

#include "djinni_support.hpp"
#include "proto/cpp/test.pb.h"

namespace djinni_generated {

class NativePriority final : ::djinni::JniEnum {
public:
    using CppType = ::djinni::test::Priority;
    using JniType = jobject;

    using Boxed = NativePriority;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativePriority>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativePriority>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativePriority() : JniEnum("djinni/test/Test$Priority") {}
    friend ::djinni::JniClass<NativePriority>;
};

} // namespace djinni_generated
