// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

#pragma once

#include "djinni_support.hpp"
#include "nested_lazy.hpp"

namespace djinni_generated {

class NativeNestedLazy final {
public:
    using CppType = ::testsuite::NestedLazy;
    using JniType = jobject;

    using Boxed = NativeNestedLazy;

    ~NativeNestedLazy();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeNestedLazy();
    friend ::djinni::JniClass<NativeNestedLazy>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/NestedLazy") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lcom/google/common/base/Supplier;)V") };
    const jfieldID field_mL { ::djinni::jniGetFieldID(clazz.get(), "mL", "Lcom/google/common/base/Supplier;") };
};

} // namespace djinni_generated
