// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from string_view_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "test_interface_with_string.hpp"

namespace djinni_generated {

class NativeTestInterfaceWithString final : ::djinni::JniInterface<::testsuite::TestInterfaceWithString, NativeTestInterfaceWithString> {
public:
    using CppType = std::shared_ptr<::testsuite::TestInterfaceWithString>;
    using CppOptType = std::shared_ptr<::testsuite::TestInterfaceWithString>;
    using JniType = jobject;

    using Boxed = NativeTestInterfaceWithString;

    ~NativeTestInterfaceWithString();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTestInterfaceWithString>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTestInterfaceWithString>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTestInterfaceWithString();
    friend ::djinni::JniClass<NativeTestInterfaceWithString>;
    friend ::djinni::JniInterface<::testsuite::TestInterfaceWithString, NativeTestInterfaceWithString>;

};

} // namespace djinni_generated
