// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

#include "NativeTestSupplier.hpp"  // my header
#include "Marshal.hpp"
#include "NativeNestedSupplier.hpp"
#include "NativeNestedSupplierInterface.hpp"
#include "NativeSimpleObject.hpp"
#include "Supplier_jni.hpp"

namespace djinni_generated {

NativeTestSupplier::NativeTestSupplier() : ::djinni::JniInterface<::testsuite::TestSupplier, NativeTestSupplier>("com/dropbox/djinni/test/TestSupplier$CppProxy") {}

NativeTestSupplier::~NativeTestSupplier() = default;


CJNIEXPORT void JNICALL Java_com_dropbox_djinni_test_TestSupplier_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::testsuite::TestSupplier>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ::djinni::SupplierAdaptor<::djinni::String>::JniType JNICALL Java_com_dropbox_djinni_test_TestSupplier_getSupplierString(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::testsuite::TestSupplier::getSupplierString();
        return ::djinni::release(::djinni::SupplierAdaptor<::djinni::String>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT ::djinni::SupplierAdaptor<::djinni::I32>::JniType JNICALL Java_com_dropbox_djinni_test_TestSupplier_getSupplierInt(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::testsuite::TestSupplier::getSupplierInt();
        return ::djinni::release(::djinni::SupplierAdaptor<::djinni::I32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_dropbox_djinni_test_TestSupplier_callSupplierString(JNIEnv* jniEnv, jobject /*this*/, ::djinni::SupplierAdaptor<::djinni::String>::JniType j_x)
{
    try {
        auto r = ::testsuite::TestSupplier::callSupplierString(::djinni::SupplierAdaptor<::djinni::String>::toCpp(jniEnv, j_x));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_TestSupplier_callSupplierInt(JNIEnv* jniEnv, jobject /*this*/, ::djinni::SupplierAdaptor<::djinni::I32>::JniType j_x)
{
    try {
        auto r = ::testsuite::TestSupplier::callSupplierInt(::djinni::SupplierAdaptor<::djinni::I32>::toCpp(jniEnv, j_x));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_dropbox_djinni_test_TestSupplier_getNestedSupplier(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::testsuite::TestSupplier::getNestedSupplier();
        return ::djinni::release(::djinni_generated::NativeNestedSupplier::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_TestSupplier_callNestedSupplier(JNIEnv* jniEnv, jobject /*this*/, jobject j_x)
{
    try {
        auto r = ::testsuite::TestSupplier::callNestedSupplier(::djinni_generated::NativeNestedSupplier::toCpp(jniEnv, j_x));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT ::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::JniType JNICALL Java_com_dropbox_djinni_test_TestSupplier_getSupplierObject(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::testsuite::TestSupplier::getSupplierObject();
        return ::djinni::release(::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_TestSupplier_callSupplierObject(JNIEnv* jniEnv, jobject /*this*/, ::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::JniType j_x)
{
    try {
        auto r = ::testsuite::TestSupplier::callSupplierObject(::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::toCpp(jniEnv, j_x));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_dropbox_djinni_test_TestSupplier_callSupplierObjectGetName(JNIEnv* jniEnv, jobject /*this*/, ::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::JniType j_x)
{
    try {
        auto r = ::testsuite::TestSupplier::callSupplierObjectGetName(::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::toCpp(jniEnv, j_x));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_dropbox_djinni_test_TestSupplier_getNestedSupplierInterface(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::testsuite::TestSupplier::getNestedSupplierInterface();
        return ::djinni::release(::djinni_generated::NativeNestedSupplierInterface::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_TestSupplier_callNestedSupplierInterface(JNIEnv* jniEnv, jobject /*this*/, jobject j_x)
{
    try {
        auto r = ::testsuite::TestSupplier::callNestedSupplierInterface(::djinni_generated::NativeNestedSupplierInterface::toCpp(jniEnv, j_x));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_dropbox_djinni_test_TestSupplier_createSimpleObject(JNIEnv* jniEnv, jobject /*this*/, jint j_value, jstring j_name)
{
    try {
        auto r = ::testsuite::TestSupplier::createSimpleObject(::djinni::I32::toCpp(jniEnv, j_value),
                                                               ::djinni::String::toCpp(jniEnv, j_name));
        return ::djinni::release(::djinni_generated::NativeSimpleObject::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
