// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

#include "NativeNestedSupplierInterface.hpp"  // my header
#include "NativeSimpleObject.hpp"
#include "Supplier_jni.hpp"

namespace djinni_generated {

NativeNestedSupplierInterface::NativeNestedSupplierInterface() = default;

NativeNestedSupplierInterface::~NativeNestedSupplierInterface() = default;

auto NativeNestedSupplierInterface::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeNestedSupplierInterface>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::fromCpp(jniEnv, c.obj)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeNestedSupplierInterface::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeNestedSupplierInterface>::get();
    return {::djinni::SupplierAdaptor<::djinni_generated::NativeSimpleObject>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mObj))};
}

} // namespace djinni_generated
