// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

#pragma once

#include "djinni_support.hpp"
#include "js_exception_thrower.hpp"

namespace djinni_generated {

class NativeJsExceptionThrower final : ::djinni::JniInterface<::testsuite::JsExceptionThrower, NativeJsExceptionThrower> {
public:
    using CppType = std::shared_ptr<::testsuite::JsExceptionThrower>;
    using CppOptType = std::shared_ptr<::testsuite::JsExceptionThrower>;
    using JniType = jobject;

    using Boxed = NativeJsExceptionThrower;

    ~NativeJsExceptionThrower();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeJsExceptionThrower>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeJsExceptionThrower>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeJsExceptionThrower();
    friend ::djinni::JniClass<NativeJsExceptionThrower>;
    friend ::djinni::JniInterface<::testsuite::JsExceptionThrower, NativeJsExceptionThrower>;

};

}  // namespace djinni_generated
