// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

#pragma once

#include "djinni_support.hpp"
#include "test_outcome.hpp"

namespace djinni_generated {

class NativeTestOutcome final : ::djinni::JniInterface<::testsuite::TestOutcome, NativeTestOutcome> {
public:
    using CppType = std::shared_ptr<::testsuite::TestOutcome>;
    using CppOptType = std::shared_ptr<::testsuite::TestOutcome>;
    using JniType = jobject;

    using Boxed = NativeTestOutcome;

    ~NativeTestOutcome();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "NativeTestOutcome::toCpp requires a non-null Java object");
        return ::djinni::JniClass<NativeTestOutcome>::get()._fromJava(jniEnv, j);
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTestOutcome>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) {
        DJINNI_ASSERT_MSG(c, jniEnv, "NativeTestOutcome::fromCpp requires a non-null C++ object");
        return fromCppOpt(jniEnv, c);
    }

private:
    NativeTestOutcome();
    friend ::djinni::JniClass<NativeTestOutcome>;
    friend ::djinni::JniInterface<::testsuite::TestOutcome, NativeTestOutcome>;

};

}  // namespace djinni_generated
