// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#pragma once

#include "djinni_support.hpp"
#include "nested_provider.hpp"

namespace djinni_generated {

class NativeNestedProvider final {
public:
    using CppType = ::testsuite::NestedProvider;
    using JniType = jobject;

    using Boxed = NativeNestedProvider;

    ~NativeNestedProvider();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeNestedProvider();
    friend ::djinni::JniClass<NativeNestedProvider>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/NestedProvider") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljavax/inject/Provider;)V") };
    const jfieldID field_mS { ::djinni::jniGetFieldID(clazz.get(), "mS", "Ljavax/inject/Provider;") };
};

} // namespace djinni_generated
