// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#pragma once

#include "base_record.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBaseRecord final {
public:
    using CppType = ::testsuite::BaseRecord;
    using JniType = jobject;

    using Boxed = NativeBaseRecord;

    ~NativeBaseRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeBaseRecord();
    friend ::djinni::JniClass<NativeBaseRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/BaseRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(I)V") };
    const jfieldID field_mVal { ::djinni::jniGetFieldID(clazz.get(), "mVal", "I") };
};

} // namespace djinni_generated
