// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#include "NativeNestedProviderInterface.hpp"  // my header
#include "NativeSimpleObject.hpp"
#include "Provider_jni.hpp"

namespace djinni_generated {

NativeNestedProviderInterface::NativeNestedProviderInterface() = default;

NativeNestedProviderInterface::~NativeNestedProviderInterface() = default;

auto NativeNestedProviderInterface::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeNestedProviderInterface>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::ProviderAdaptor<::djinni_generated::NativeSimpleObject>::fromCpp(jniEnv, c.obj)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeNestedProviderInterface::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeNestedProviderInterface>::get();
    return {::djinni::ProviderAdaptor<::djinni_generated::NativeSimpleObject>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mObj))};
}

} // namespace djinni_generated
