// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from no_constructor.djinni

#pragma once

#include "djinni_support.hpp"
#include "no_constructor_record_native.hpp"

namespace djinni_generated {

class NoConstructorRecordNative final {
public:
    using CppType = ::testsuite::NoConstructorRecord;
    using JniType = jobject;

    using Boxed = NoConstructorRecordNative;

    ~NoConstructorRecordNative();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NoConstructorRecordNative();
    friend ::djinni::JniClass<NoConstructorRecordNative>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/NoConstructorRecordNative") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/String;)V") };
    const jfieldID field_mFirstValue { ::djinni::jniGetFieldID(clazz.get(), "mFirstValue", "I") };
    const jfieldID field_mSecondValue { ::djinni::jniGetFieldID(clazz.get(), "mSecondValue", "Ljava/lang/String;") };
};

} // namespace djinni_generated
