// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test;

/** Record containing enum constant */
class ConstantWithEnum {
    companion object {
        val CONST_ENUM: ConstantEnum = ConstantEnum.SOME_VALUE
    }

    override fun toString(): String  {
        return "ConstantWithEnum {" +
        "}"
    }

}
