// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test;

abstract class ExternInterface2 {
    abstract fun foo(i: com.dropbox.djinni.test.TestHelpers): ExternRecordWithDerivings
}
