// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test;

import java.util.HashMap;

data class MapRecord(
    val mMap: HashMap<String, Long>,
    val mImap: HashMap<Int, Int>,
) {

    override fun toString(): String  {
        return "MapRecord {" +
                "mMap=" + mMap +
                "," + "mImap=" + mImap +
        "}"
    }

}
