// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test;

import com.snapchat.djinni.NativeObjectManager;
import djinni.test.Test.AddressBook;
import djinni.test.Test.Person;
import djinni.test2.Test2.PersistingState;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

abstract class ProtoTests {

    companion object {
        external fun protoToStrings(x: AddressBook): ArrayList<String>

        external fun stringsToProto(x: ArrayList<String>): AddressBook

        external fun embeddedProtoToString(x: RecordWithEmbeddedProto): String

        external fun stringToEmbeddedProto(x: String): RecordWithEmbeddedProto

        external fun cppProtoToString(x: PersistingState): String

        external fun stringToCppProto(x: String): PersistingState

        external fun embeddedCppProtoToString(x: RecordWithEmbeddedCppProto): String

        external fun stringToEmbeddedCppProto(x: String): RecordWithEmbeddedCppProto

        external fun protoListToStrings(x: ArrayList<Person>): ArrayList<String>

        external fun stringsToProtoList(x: ArrayList<String>): ArrayList<Person>

        external fun optionalProtoToString(x: Person?): String

        external fun stringToOptionalProto(x: String): Person?

        external fun stringToProtoOutcome(x: String): com.snapchat.djinni.Outcome<Person, Int>
    }

    class CppProxy(private val nativeRef: Long) : ProtoTests() {
        private val destroyed = AtomicBoolean(false)

        init {
            if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
            NativeObjectManager.register(this, nativeRef)
        }

        companion object {
            @kotlin.jvm.JvmStatic
            external fun nativeDestroy(nativeRef: Long)
        }
    }
}
