// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test;

import djinni.test2.Test2.PersistingState;

data class RecordWithEmbeddedCppProto(
    val mState: PersistingState,
) {

    override fun toString(): String  {
        return "RecordWithEmbeddedCppProto {" +
                "mState=" + mState +
        "}"
    }

}
