// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test;

data class RecordWithDurationAndDerivings(
    val mDt: java.time.Duration,
) : Comparable<RecordWithDurationAndDerivings> {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as RecordWithDurationAndDerivings

        if (mDt != other.mDt) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + (mDt.hashCode())
        return hashCode
    }

    override fun toString(): String  {
        return "RecordWithDurationAndDerivings {" +
                "mDt=" + mDt +
        "}"
    }


    override fun compareTo(other: RecordWithDurationAndDerivings): Int  {
        var tempResult: Int
        tempResult = this.mDt.compareTo(other.mDt);
        if (tempResult != 0) {
            return tempResult
        }
        return 0
    }
}
