// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test;

data class Vec2(
    val mX: Int,
    val mY: Int,
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Vec2

        if (mX != other.mX) return false
        if (mY != other.mY) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mX
        hashCode = hashCode * 31 + mY
        return hashCode
    }

    override fun toString(): String  {
        return "Vec2 {" +
                "mX=" + mX +
                "," + "mY=" + mY +
        "}"
    }

}
