// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test;

data class WcharTestRec(
    val mS: String,
) {

    override fun toString(): String  {
        return "WcharTestRec {" +
                "mS=" + mS +
        "}"
    }

}
