// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni


export interface /*record*/ ItemList {
    items: Array<string>;
}

export enum SortOrder {
    ASCENDING = 0,
    DESCENDING = 1,
    RANDOM = 2,
}

export interface SortItems {
    /** For the iOS / Android demo */
    sort(order: SortOrder, items: ItemList): void;
}
export interface SortItems_statics {
    createWithListener(listener: TextboxListener): SortItems;
    /** For the localhost / command-line demo */
    runSort(items: ItemList): ItemList;
}

export interface TextboxListener {
    update(items: ItemList): void;
}

export interface Example_module_statics {
    SortItems: SortItems_statics;
}
