// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

import DjinniSupport
import DjinniSupportCxx
import TextSort
import TextSortCxx

enum TextboxListenerMarshaller: DjinniSupport.Marshaller {
    typealias SwiftType = TextboxListener
    static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { fatalError("n/a") })
    }
    static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { fatalError("n/a") })
    }
}
