// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

import Foundation

public protocol TextboxListener: AnyObject {
    func update(_ items: TextSort.ItemList) throws -> Void
}
