// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** Base record with a required value */
public class BaseRecord {


    /*package*/ final int mVal;

    public BaseRecord(
            int val) {
        this.mVal = val;
    }

    public int getVal() {
        return mVal;
    }

    @Override
    public String toString() {
        return "BaseRecord{" +
                "mVal=" + mVal +
        "}";
    }

}
