// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** Record with a mix of optional and required values */
public class MixedRecord {


    /*package*/ /*optional*/ OptionalInterface mInterfaceVal;

    /*package*/ int mReqInt;

    /*package*/ /*optional*/ BaseRecord mOptRecord;

    /*package*/ BaseRecord mReqRecord;

    public MixedRecord(
            @CheckForNull OptionalInterface interfaceVal,
            int reqInt,
            @CheckForNull BaseRecord optRecord,
            @Nonnull BaseRecord reqRecord) {
        this.mInterfaceVal = interfaceVal;
        this.mReqInt = reqInt;
        this.mOptRecord = optRecord;
        this.mReqRecord = reqRecord;
    }

    public MixedRecord(
            int reqInt,
            @Nonnull BaseRecord reqRecord) {
        this(null,
             reqInt,
             null,
             reqRecord);
    }

    @CheckForNull
    public OptionalInterface getInterfaceVal() {
        return mInterfaceVal;
    }

    public void setInterfaceVal(OptionalInterface interfaceVal) {
        this.mInterfaceVal = interfaceVal;
    }

    public int getReqInt() {
        return mReqInt;
    }

    public void setReqInt(int reqInt) {
        this.mReqInt = reqInt;
    }

    @CheckForNull
    public BaseRecord getOptRecord() {
        return mOptRecord;
    }

    public void setOptRecord(BaseRecord optRecord) {
        this.mOptRecord = optRecord;
    }

    @Nonnull
    public BaseRecord getReqRecord() {
        return mReqRecord;
    }

    public void setReqRecord(@Nonnull BaseRecord reqRecord) {
        this.mReqRecord = reqRecord;
    }

    @Override
    public String toString() {
        return "MixedRecord{" +
                "mInterfaceVal=" + mInterfaceVal +
                "," + "mReqInt=" + mReqInt +
                "," + "mOptRecord=" + mOptRecord +
                "," + "mReqRecord=" + mReqRecord +
        "}";
    }

}
