// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from outcome.djinni

package com.dropbox.djinni.test;

import com.snapchat.djinni.Outcome;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class NestedOutcome {


    /*package*/ final Outcome<Integer, String> mO;

    public NestedOutcome(
            @Nonnull Outcome<Integer, String> o) {
        this.mO = o;
    }

    @Nonnull
    public Outcome<Integer, String> getO() {
        return mO;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof NestedOutcome)) {
            return false;
        }
        NestedOutcome other = (NestedOutcome) obj;
        return this.mO.equals(other.mO);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mO.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "NestedOutcome{" +
                "mO=" + mO +
        "}";
    }

}
