// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class NestedSupplierInterface {


    /*package*/ com.google.common.base.Supplier<SimpleObject> mObj;

    public NestedSupplierInterface(
            @Nonnull com.google.common.base.Supplier<SimpleObject> obj) {
        this.mObj = obj;
    }

    @Nonnull
    public com.google.common.base.Supplier<SimpleObject> getObj() {
        return mObj;
    }

    public void setObj(@Nonnull com.google.common.base.Supplier<SimpleObject> obj) {
        this.mObj = obj;
    }

    @Override
    public String toString() {
        return "NestedSupplierInterface{" +
                "mObj=" + mObj +
        "}";
    }

}
