// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

package com.dropbox.djinni.test;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class OptionalTestHelpers {
    @Nonnull
    public static native BaseRecord getBaseRecord();

    @CheckForNull
    public static native OptionalInterface optionalInterface();

    @Nonnull
    public static native MixedRecord getMixedRecord();

    @Nonnull
    public static native OptionalRecord getOptionalRecord();

    /** Checks that translation occurs properly */
    @Nonnull
    public static native MixedRecord mixedRecordId(@Nonnull MixedRecord i);

    public static final class CppProxy extends OptionalTestHelpers
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);
    }
}
