// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test;

import djinni.test.Test.Person.PhoneType;
import djinni.test.Test.Priority;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class RecordWithProtobufEnum {


    /*package*/ final djinni.test.Test.Person.PhoneType mPhoneType;

    /*package*/ final djinni.test.Test.Priority mPriority;

    public RecordWithProtobufEnum(
            @Nonnull djinni.test.Test.Person.PhoneType phoneType,
            @Nonnull djinni.test.Test.Priority priority) {
        this.mPhoneType = phoneType;
        this.mPriority = priority;
    }

    @Nonnull
    public djinni.test.Test.Person.PhoneType getPhoneType() {
        return mPhoneType;
    }

    @Nonnull
    public djinni.test.Test.Priority getPriority() {
        return mPriority;
    }

    @Override
    public String toString() {
        return "RecordWithProtobufEnum{" +
                "mPhoneType=" + mPhoneType +
                "," + "mPriority=" + mPriority +
        "}";
    }

}
