// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from string_view_test.djinni

package com.dropbox.djinni.test;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** @flag "--cpp-use-string-view true" */
public abstract class TestInterfaceWithString {
    /** Method with string parameter to test string_view generation */
    @Nonnull
    public abstract String processString(@Nonnull String message);

    public static final class CppProxy extends TestInterfaceWithString
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public String processString(String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_processString(this.nativeRef, message);
        }
        private native String native_processString(long _nativeRef, String message);
    }
}
