// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test;

public final class TestOptionalExternInterfaceRecord {


    /*package*/ /*optional*/ com.dropbox.djinni.test.SampleInterface mSampleInterface;

    public TestOptionalExternInterfaceRecord(
            com.dropbox.djinni.test.SampleInterface sampleInterface) {
        this.mSampleInterface = sampleInterface;
    }

    public TestOptionalExternInterfaceRecord() {
        this(null);
    }

    public com.dropbox.djinni.test.SampleInterface getSampleInterface() {
        return mSampleInterface;
    }

    public void setSampleInterface(com.dropbox.djinni.test.SampleInterface sampleInterface) {
        this.mSampleInterface = sampleInterface;
    }

    @Override
    public String toString() {
        return "TestOptionalExternInterfaceRecord{" +
                "mSampleInterface=" + mSampleInterface +
        "}";
    }

}
