// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

package com.dropbox.djinni.test;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class TestSupplier {
    /** Simple type supplier tests */
    @Nonnull
    public static native com.google.common.base.Supplier<String> getSupplierString();

    @Nonnull
    public static native com.google.common.base.Supplier<Integer> getSupplierInt();

    @Nonnull
    public static native String callSupplierString(@Nonnull com.google.common.base.Supplier<String> x);

    public static native int callSupplierInt(@Nonnull com.google.common.base.Supplier<Integer> x);

    @Nonnull
    public static native NestedSupplier getNestedSupplier();

    public static native int callNestedSupplier(@Nonnull NestedSupplier x);

    /** Interface supplier tests - main use case for deferred expensive object creation */
    @Nonnull
    public static native com.google.common.base.Supplier<SimpleObject> getSupplierObject();

    public static native int callSupplierObject(@Nonnull com.google.common.base.Supplier<SimpleObject> x);

    @Nonnull
    public static native String callSupplierObjectGetName(@Nonnull com.google.common.base.Supplier<SimpleObject> x);

    @Nonnull
    public static native NestedSupplierInterface getNestedSupplierInterface();

    public static native int callNestedSupplierInterface(@Nonnull NestedSupplierInterface x);

    /** Helper to create simple_object for testing */
    @CheckForNull
    public static native SimpleObject createSimpleObject(int value, @Nonnull String name);

    public static final class CppProxy extends TestSupplier
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);
    }
}
