// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class Vec2 {


    /*package*/ final int mX;

    /*package*/ final int mY;

    public Vec2(
            int x,
            int y) {
        this.mX = x;
        this.mY = y;
    }

    public int getX() {
        return mX;
    }

    public int getY() {
        return mY;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof Vec2)) {
            return false;
        }
        Vec2 other = (Vec2) obj;
        return this.mX == other.mX &&
                this.mY == other.mY;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mX;
        hashCode = hashCode * 31 + mY;
        return hashCode;
    }

    @Override
    public String toString() {
        return "Vec2{" +
                "mX=" + mX +
                "," + "mY=" + mY +
        "}";
    }

}
