// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "async_interface.h"
#include "djinni_c_translators.hpp"
#include "Future.hpp"
#include "Future_c_translator.hpp"
#include "async_interface.hpp"

using Proxy_Parent = ::djinni::Proxy<testsuite_async_interface_method_defs>;
struct AsyncInterface_Proxy: public Proxy_Parent, public ::testsuite::AsyncInterface  {
    AsyncInterface_Proxy(::djinni::ProxyClass<testsuite_async_interface_method_defs> *proxyClass, void *opaque): Proxy_Parent(proxyClass, opaque) {}

    ~AsyncInterface_Proxy() override = default;

    ::djinni::Future<std::string> future_roundtrip(::djinni::Future<int32_t> f) override {
        auto f_c = ::djinni::c_api::Ref(::djinni::c_api::FutureTranslator<::djinni::c_api::Int32Translator>::fromCpp(std::move(f)));
        auto returnValue = ::djinni::c_api::Ref(Proxy_Parent::getProxyClass().methodDefs().future_roundtrip(Proxy_Parent::getOpaque(), f_c.get()));
        return ::djinni::c_api::FutureTranslator<::djinni::c_api::StringTranslator>::toCpp(returnValue.get());
    }

};

testsuite_async_interface_proxy_class_ref testsuite_async_interface_proxy_class_new(const testsuite_async_interface_method_defs *method_defs, djinni_opaque_deallocator opaque_deallocator) {
    return ::djinni::c_api::InterfaceTranslator<::testsuite::AsyncInterface>::makeProxyClass<testsuite_async_interface_method_defs>(method_defs, opaque_deallocator);
}

testsuite_async_interface_ref testsuite_async_interface_new(testsuite_async_interface_proxy_class_ref proxy_class, void *opaque) {
    return ::djinni::c_api::InterfaceTranslator<::testsuite::AsyncInterface>::makeProxy<testsuite_async_interface_method_defs, AsyncInterface_Proxy>(proxy_class, opaque);
}

djinni_future_ref testsuite_async_interface_future_roundtrip(testsuite_async_interface_ref instance, djinni_future_ref f)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::AsyncInterface>::toCpp(instance)->future_roundtrip(::djinni::c_api::FutureTranslator<::djinni::c_api::Int32Translator>::toCpp(f));
    return ::djinni::c_api::FutureTranslator<::djinni::c_api::StringTranslator>::fromCpp(std::move(retValue));
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(djinni_future_ref)
}


