// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

#pragma once

#include "djinni_c.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/** Record returned by a client */
typedef djinni_record_ref testsuite_client_returned_record_ref;

testsuite_client_returned_record_ref testsuite_client_returned_record_new(int64_t record_id, djinni_string_ref content, djinni_string_ref misc);
int64_t testsuite_client_returned_record_get_record_id(testsuite_client_returned_record_ref instance);
void testsuite_client_returned_record_set_record_id(testsuite_client_returned_record_ref instance, int64_t value);

djinni_string_ref testsuite_client_returned_record_get_content(testsuite_client_returned_record_ref instance);
void testsuite_client_returned_record_set_content(testsuite_client_returned_record_ref instance, djinni_string_ref value);

djinni_string_ref testsuite_client_returned_record_get_misc(testsuite_client_returned_record_ref instance);
void testsuite_client_returned_record_set_misc(testsuite_client_returned_record_ref instance, djinni_string_ref value);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

