// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#pragma once

#include "djinni_c.h"
#include "Conflict.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef djinni_interface_ref testsuite_conflict_user_ref;

testsuite_Conflict_ref testsuite_conflict_user_Conflict(testsuite_conflict_user_ref instance);

bool testsuite_conflict_user_conflict_arg(testsuite_conflict_user_ref instance, djinni_array_ref cs);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

