// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "conflict_user.h"
#include "djinni_c_translators.hpp"
#include "conflict_user.hpp"
#include <memory>

testsuite_Conflict_ref testsuite_conflict_user_Conflict(testsuite_conflict_user_ref instance)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::ConflictUser>::toCpp(instance)->Conflict();
    return ::djinni::c_api::InterfaceTranslator<::testsuite::Conflict>::fromCpp(std::move(retValue));
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(testsuite_Conflict_ref)
}

bool testsuite_conflict_user_conflict_arg(testsuite_conflict_user_ref instance, djinni_array_ref cs)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::ConflictUser>::toCpp(instance)->conflict_arg(::djinni::c_api::ListTranslator<::djinni::c_api::InterfaceTranslator<::testsuite::Conflict>>::toCpp(cs));
    return std::move(retValue);
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(bool)
}


