// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#pragma once

#include "djinni_c.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/** enum for use in constants */
enum testsuite_constant_enum {
    testsuite_constant_enum_SOME_VALUE = 0,
    testsuite_constant_enum_SOME_OTHER_VALUE = 1,
};
#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

