// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#include "constant_with_enum.h"
#include "djinni_c_translators.hpp"
#include "constant_enum.hpp"
#include "constant_with_enum.hpp"

testsuite_constant_with_enum_ref testsuite_constant_with_enum_new() 
{
    return ::djinni::c_api::RecordTranslator<::testsuite::ConstantWithEnum>::make();
}

testsuite_constant_enum testsuite_constant_with_enum_get_const_enum() {
    return ::djinni::c_api::EnumTranslator<::testsuite::constant_enum, testsuite_constant_enum>::fromCpp(::testsuite::ConstantWithEnum::CONST_ENUM);
}


