// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

#pragma once

#include "djinni_c.h"
#include "cpp_exception.h"
#include "throwing_interface.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef djinni_interface_ref testsuite_cpp_exception_ref;

int32_t testsuite_cpp_exception_throw_an_exception(testsuite_cpp_exception_ref instance);

int32_t testsuite_cpp_exception_call_throwing_interface(testsuite_cpp_exception_ref instance, testsuite_throwing_interface_ref cb);

djinni_string_ref testsuite_cpp_exception_call_throwing_and_catch(testsuite_cpp_exception_ref instance, testsuite_throwing_interface_ref cb);

testsuite_cpp_exception_ref testsuite_cpp_exception_get();

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

