// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#include "date_record.h"
#include "djinni_c_helpers.hpp"
#include "date_record.hpp"
#include "djinni_c_helpers.hpp"
#include <chrono>

testsuite_date_record_ref testsuite_date_record_new(djinni_date_ref created_at) 
{
    return ::djinni::c_api::Record<::testsuite::DateRecord>::make(::djinni::c_api::Date::toCpp(created_at));
}

djinni_date_ref testsuite_date_record_get_created_at(testsuite_date_record_ref instance)
{
    return ::djinni::c_api::Date::fromCpp(::djinni::c_api::Record<::testsuite::DateRecord>::toCpp(instance).created_at);
}

void testsuite_date_record_set_created_at(testsuite_date_record_ref instance, djinni_date_ref value)
{
    ::djinni::c_api::Record<::testsuite::DateRecord>::toCpp(instance).created_at = ::djinni::c_api::Date::toCpp(value);
}


