// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "empty_record.h"
#include "djinni_c_translators.hpp"
#include "empty_record.hpp"

testsuite_empty_record_ref testsuite_empty_record_new() 
{
    return ::djinni::c_api::RecordTranslator<::testsuite::EmptyRecord>::make();
}


