// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#pragma once

#include "djinni_c.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Empty record
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
typedef djinni_record_ref testsuite_empty_record_ref;

testsuite_empty_record_ref testsuite_empty_record_new();
#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

