// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

#include "first_listener.h"
#include "djinni_c_translators.hpp"
#include "first_listener.hpp"

void testsuite_first_listener_first(testsuite_first_listener_ref instance)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    ::djinni::c_api::InterfaceTranslator<::testsuite::FirstListener>::toCpp(instance)->first();
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(void)
}


