// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

#include "java_only_listener.h"
#include "djinni_c_translators.hpp"
#include "java_only_listener.hpp"

using Proxy_Parent = ::djinni::Proxy<testsuite_java_only_listener_method_defs>;
struct JavaOnlyListener_Proxy: public Proxy_Parent, public ::testsuite::JavaOnlyListener  {
    JavaOnlyListener_Proxy(::djinni::ProxyClass<testsuite_java_only_listener_method_defs> *proxyClass, void *opaque): Proxy_Parent(proxyClass, opaque) {}

    ~JavaOnlyListener_Proxy() override = default;

};

testsuite_java_only_listener_proxy_class_ref testsuite_java_only_listener_proxy_class_new(const testsuite_java_only_listener_method_defs *method_defs, djinni_opaque_deallocator opaque_deallocator) {
    return ::djinni::c_api::ProxyTranslator<JavaOnlyListener_Proxy, testsuite_java_only_listener_method_defs>::makeClass(method_defs, opaque_deallocator);
}

testsuite_java_only_listener_ref testsuite_java_only_listener_new(testsuite_java_only_listener_proxy_class_ref proxy_class, void *opaque) {
    return ::djinni::c_api::ProxyTranslator<JavaOnlyListener_Proxy, testsuite_java_only_listener_method_defs>::make(proxy_class, opaque);
}


