// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#pragma once

#include "djinni_c.h"
#include "djinni_c.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef djinni_record_ref testsuite_map_date_record_ref;

testsuite_map_date_record_ref testsuite_map_date_record_new(djinni_keyval_array_ref dates_by_id);

djinni_keyval_array_ref testsuite_map_date_record_get_dates_by_id(testsuite_map_date_record_ref instance);
void testsuite_map_date_record_set_dates_by_id(testsuite_map_date_record_ref instance, djinni_keyval_array_ref value);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

