// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#include "nested_provider.h"
#include "djinni_c_translators.hpp"
#include "Provider.hpp"
#include "Provider_c_translator.hpp"
#include "nested_provider.hpp"

testsuite_nested_provider_ref testsuite_nested_provider_new(djinni_provider_ref s) 
{
    return ::djinni::c_api::RecordTranslator<::testsuite::NestedProvider>::make(::djinni::c_api::ProviderTranslator<::djinni::c_api::Int32Translator>::toCpp(s));
}

djinni_provider_ref testsuite_nested_provider_get_s(testsuite_nested_provider_ref instance)
{
    return ::djinni::c_api::ProviderTranslator<::djinni::c_api::Int32Translator>::fromCpp(::djinni::c_api::RecordTranslator<::testsuite::NestedProvider>::toCpp(instance).s);
}

void testsuite_nested_provider_set_s(testsuite_nested_provider_ref instance, djinni_provider_ref value)
{
    ::djinni::c_api::RecordTranslator<::testsuite::NestedProvider>::toCpp(instance).s = ::djinni::c_api::ProviderTranslator<::djinni::c_api::Int32Translator>::toCpp(value);
}


