// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

#include "nested_collection.h"
#include "djinni_c_helpers.hpp"
#include "nested_collection.hpp"

testsuite_nested_collection_ref testsuite_nested_collection_new(djinni_array_ref set_list) 
{
    return ::djinni::c_api::Record<::testsuite::NestedCollection>::make(::djinni::c_api::List<std::unordered_set<std::string>>::toCpp(set_list, [](auto&& value) { return ::djinni::c_api::Set<std::string>::toCpp(std::forward<decltype(value)>(value), [](auto&& value) { return ::djinni::c_api::String::toCpp(std::forward<decltype(value)>(value)); }); }));
}

djinni_array_ref testsuite_nested_collection_get_set_list(testsuite_nested_collection_ref instance)
{
    return ::djinni::c_api::List<std::unordered_set<std::string>>::fromCpp(::djinni::c_api::Record<::testsuite::NestedCollection>::toCpp(instance).set_list, [](auto&& value) { return ::djinni::c_api::Set<std::string>::fromCpp(std::forward<decltype(value)>(value), [](auto&& value) { return ::djinni::c_api::String::fromCpp(std::forward<decltype(value)>(value)); }); });
}

void testsuite_nested_collection_set_set_list(testsuite_nested_collection_ref instance, djinni_array_ref value)
{
    ::djinni::c_api::Record<::testsuite::NestedCollection>::toCpp(instance).set_list = ::djinni::c_api::List<std::unordered_set<std::string>>::toCpp(value, [](auto&& value) { return ::djinni::c_api::Set<std::string>::toCpp(std::forward<decltype(value)>(value), [](auto&& value) { return ::djinni::c_api::String::toCpp(std::forward<decltype(value)>(value)); }); });
}


