// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#pragma once

#include "djinni_c.h"
#include "RecordWithEmbeddedCppProto.h"
#include "RecordWithEmbeddedProto.h"
#include "djinni_c.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef djinni_interface_ref testsuite_proto_tests_ref;
typedef djinni_proxy_class_ref testsuite_proto_tests_proxy_class_ref;

typedef struct 
{
    djinni_array_ref (*protoToStrings)(void *, djinni_binary_ref);
    djinni_binary_ref (*stringsToProto)(void *, djinni_array_ref);
    djinni_string_ref (*embeddedProtoToString)(void *, testsuite_RecordWithEmbeddedProto_ref);
    testsuite_RecordWithEmbeddedProto_ref (*stringToEmbeddedProto)(void *, djinni_string_ref);
    djinni_string_ref (*cppProtoToString)(void *, djinni_binary_ref);
    djinni_binary_ref (*stringToCppProto)(void *, djinni_string_ref);
    djinni_string_ref (*embeddedCppProtoToString)(void *, testsuite_RecordWithEmbeddedCppProto_ref);
    testsuite_RecordWithEmbeddedCppProto_ref (*stringToEmbeddedCppProto)(void *, djinni_string_ref);
    djinni_array_ref (*protoListToStrings)(void *, djinni_array_ref);
    djinni_array_ref (*stringsToProtoList)(void *, djinni_array_ref);
    djinni_string_ref (*optionalProtoToString)(void *, djinni_binary_ref);
    djinni_binary_ref (*stringToOptionalProto)(void *, djinni_string_ref);
    djinni_outcome_ref (*stringToProtoOutcome)(void *, djinni_string_ref);
} testsuite_proto_tests_method_defs;

testsuite_proto_tests_proxy_class_ref testsuite_proto_tests_proxy_class_new(const testsuite_proto_tests_method_defs *method_defs, djinni_opaque_deallocator opaque_deallocator);

testsuite_proto_tests_ref testsuite_proto_tests_new(testsuite_proto_tests_proxy_class_ref proxy_class, void *opaque);

djinni_array_ref testsuite_proto_tests_protoToStrings(djinni_binary_ref x);

djinni_binary_ref testsuite_proto_tests_stringsToProto(djinni_array_ref x);

djinni_string_ref testsuite_proto_tests_embeddedProtoToString(testsuite_RecordWithEmbeddedProto_ref x);

testsuite_RecordWithEmbeddedProto_ref testsuite_proto_tests_stringToEmbeddedProto(djinni_string_ref x);

djinni_string_ref testsuite_proto_tests_cppProtoToString(djinni_binary_ref x);

djinni_binary_ref testsuite_proto_tests_stringToCppProto(djinni_string_ref x);

djinni_string_ref testsuite_proto_tests_embeddedCppProtoToString(testsuite_RecordWithEmbeddedCppProto_ref x);

testsuite_RecordWithEmbeddedCppProto_ref testsuite_proto_tests_stringToEmbeddedCppProto(djinni_string_ref x);

djinni_array_ref testsuite_proto_tests_protoListToStrings(djinni_array_ref x);

djinni_array_ref testsuite_proto_tests_stringsToProtoList(djinni_array_ref x);

djinni_string_ref testsuite_proto_tests_optionalProtoToString(djinni_binary_ref x);

djinni_binary_ref testsuite_proto_tests_stringToOptionalProto(djinni_string_ref x);

djinni_outcome_ref testsuite_proto_tests_stringToProtoOutcome(djinni_string_ref x);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

