// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#pragma once

#include "djinni_c.h"
#include "Outcome_c.h"
#include "RecordWithEmbeddedCppProto.h"
#include "RecordWithEmbeddedProto.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef djinni_interface_ref testsuite_proto_tests_ref;

djinni_array_ref testsuite_proto_tests_protoToStrings(djinni_binary_ref x);

djinni_binary_ref testsuite_proto_tests_stringsToProto(djinni_array_ref x);

djinni_string_ref testsuite_proto_tests_embeddedProtoToString(testsuite_RecordWithEmbeddedProto_ref x);

testsuite_RecordWithEmbeddedProto_ref testsuite_proto_tests_stringToEmbeddedProto(djinni_string_ref x);

djinni_string_ref testsuite_proto_tests_cppProtoToString(djinni_binary_ref x);

djinni_binary_ref testsuite_proto_tests_stringToCppProto(djinni_string_ref x);

djinni_string_ref testsuite_proto_tests_embeddedCppProtoToString(testsuite_RecordWithEmbeddedCppProto_ref x);

testsuite_RecordWithEmbeddedCppProto_ref testsuite_proto_tests_stringToEmbeddedCppProto(djinni_string_ref x);

djinni_array_ref testsuite_proto_tests_protoListToStrings(djinni_array_ref x);

djinni_array_ref testsuite_proto_tests_stringsToProtoList(djinni_array_ref x);

djinni_string_ref testsuite_proto_tests_optionalProtoToString(djinni_binary_ref x);

djinni_binary_ref testsuite_proto_tests_stringToOptionalProto(djinni_string_ref x);

djinni_outcome_ref testsuite_proto_tests_stringToProtoOutcome(djinni_string_ref x);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

