// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

#include "record_with_nested_derivings.h"
#include "djinni_c_translators.hpp"
#include "record_with_derivings.hpp"
#include "record_with_nested_derivings.hpp"

testsuite_record_with_nested_derivings_ref testsuite_record_with_nested_derivings_new(int32_t key, testsuite_record_with_derivings_ref rec) 
{
    return ::djinni::c_api::RecordTranslator<::testsuite::RecordWithNestedDerivings>::make(key, ::djinni::c_api::RecordTranslator<::testsuite::RecordWithDerivings>::toCpp(rec));
}

int32_t testsuite_record_with_nested_derivings_get_key(testsuite_record_with_nested_derivings_ref instance)
{
    return ::djinni::c_api::RecordTranslator<::testsuite::RecordWithNestedDerivings>::toCpp(instance).key;
}

void testsuite_record_with_nested_derivings_set_key(testsuite_record_with_nested_derivings_ref instance, int32_t value)
{
    ::djinni::c_api::RecordTranslator<::testsuite::RecordWithNestedDerivings>::toCpp(instance).key = value;
}

testsuite_record_with_derivings_ref testsuite_record_with_nested_derivings_get_rec(testsuite_record_with_nested_derivings_ref instance)
{
    return ::djinni::c_api::RecordTranslator<::testsuite::RecordWithDerivings>::fromCpp(::djinni::c_api::RecordTranslator<::testsuite::RecordWithNestedDerivings>::toCpp(instance).rec);
}

void testsuite_record_with_nested_derivings_set_rec(testsuite_record_with_nested_derivings_ref instance, testsuite_record_with_derivings_ref value)
{
    ::djinni::c_api::RecordTranslator<::testsuite::RecordWithNestedDerivings>::toCpp(instance).rec = ::djinni::c_api::RecordTranslator<::testsuite::RecordWithDerivings>::toCpp(value);
}


