// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

#include "record_with_duration_and_derivings.h"
#include "djinni_c_translators.hpp"
#include "duration_c_translator.hpp"
#include "record_with_duration_and_derivings.hpp"
#include <chrono>

testsuite_record_with_duration_and_derivings_ref testsuite_record_with_duration_and_derivings_new(djinni_number_ref dt) 
{
    return ::djinni::c_api::RecordTranslator<::testsuite::RecordWithDurationAndDerivings>::make(::djinni::c_api::DurationTranslator<double, std::nano>::toCpp(dt));
}

djinni_number_ref testsuite_record_with_duration_and_derivings_get_dt(testsuite_record_with_duration_and_derivings_ref instance)
{
    return ::djinni::c_api::DurationTranslator<double, std::nano>::fromCpp(::djinni::c_api::RecordTranslator<::testsuite::RecordWithDurationAndDerivings>::toCpp(instance).dt);
}

void testsuite_record_with_duration_and_derivings_set_dt(testsuite_record_with_duration_and_derivings_ref instance, djinni_number_ref value)
{
    ::djinni::c_api::RecordTranslator<::testsuite::RecordWithDurationAndDerivings>::toCpp(instance).dt = ::djinni::c_api::DurationTranslator<double, std::nano>::toCpp(value);
}


