// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#include "record_with_flags.h"
#include "djinni_c_helpers.hpp"
#include "access_flags.hpp"
#include "record_with_flags.hpp"

testsuite_record_with_flags_ref testsuite_record_with_flags_new(testsuite_access_flags access) 
{
    return ::djinni::c_api::Record<::testsuite::RecordWithFlags>::make(::djinni::c_api::Enum<::testsuite::access_flags, testsuite_access_flags>::toCpp(access));
}

testsuite_access_flags testsuite_record_with_flags_get_access(testsuite_record_with_flags_ref instance)
{
    return ::djinni::c_api::Enum<::testsuite::access_flags, testsuite_access_flags>::fromCpp(::djinni::c_api::Record<::testsuite::RecordWithFlags>::toCpp(instance).access);
}

void testsuite_record_with_flags_set_access(testsuite_record_with_flags_ref instance, testsuite_access_flags value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithFlags>::toCpp(instance).access = ::djinni::c_api::Enum<::testsuite::access_flags, testsuite_access_flags>::toCpp(value);
}


