// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

#include "record_with_derivings.h"
#include "djinni_c_helpers.hpp"
#include "record_with_derivings.hpp"

testsuite_record_with_derivings_ref testsuite_record_with_derivings_new(int8_t eight, int16_t sixteen, int32_t thirtytwo, int64_t sixtyfour, float fthirtytwo, double fsixtyfour, djinni_date_ref d, djinni_string_ref s) 
{
    return ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::make(eight, sixteen, thirtytwo, sixtyfour, fthirtytwo, fsixtyfour, ::djinni::c_api::Date::toCpp(d), ::djinni::c_api::String::toCpp(s));
}

int8_t testsuite_record_with_derivings_get_eight(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).eight;
}

void testsuite_record_with_derivings_set_eight(testsuite_record_with_derivings_ref instance, int8_t value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).eight = value;
}

int16_t testsuite_record_with_derivings_get_sixteen(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).sixteen;
}

void testsuite_record_with_derivings_set_sixteen(testsuite_record_with_derivings_ref instance, int16_t value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).sixteen = value;
}

int32_t testsuite_record_with_derivings_get_thirtytwo(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).thirtytwo;
}

void testsuite_record_with_derivings_set_thirtytwo(testsuite_record_with_derivings_ref instance, int32_t value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).thirtytwo = value;
}

int64_t testsuite_record_with_derivings_get_sixtyfour(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).sixtyfour;
}

void testsuite_record_with_derivings_set_sixtyfour(testsuite_record_with_derivings_ref instance, int64_t value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).sixtyfour = value;
}

float testsuite_record_with_derivings_get_fthirtytwo(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).fthirtytwo;
}

void testsuite_record_with_derivings_set_fthirtytwo(testsuite_record_with_derivings_ref instance, float value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).fthirtytwo = value;
}

double testsuite_record_with_derivings_get_fsixtyfour(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).fsixtyfour;
}

void testsuite_record_with_derivings_set_fsixtyfour(testsuite_record_with_derivings_ref instance, double value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).fsixtyfour = value;
}

djinni_date_ref testsuite_record_with_derivings_get_d(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::Date::fromCpp(::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).d);
}

void testsuite_record_with_derivings_set_d(testsuite_record_with_derivings_ref instance, djinni_date_ref value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).d = ::djinni::c_api::Date::toCpp(value);
}

djinni_string_ref testsuite_record_with_derivings_get_s(testsuite_record_with_derivings_ref instance)
{
    return ::djinni::c_api::String::fromCpp(::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).s);
}

void testsuite_record_with_derivings_set_s(testsuite_record_with_derivings_ref instance, djinni_string_ref value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithDerivings>::toCpp(instance).s = ::djinni::c_api::String::toCpp(value);
}


