// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#include "RecordWithEmbeddedCppProto.h"
#include "djinni_c_helpers.hpp"
#include "RecordWithEmbeddedCppProto.hpp"
#include "proto/cpp/test2.pb.h"

testsuite_RecordWithEmbeddedCppProto_ref testsuite_RecordWithEmbeddedCppProto_new(djinni_binary_ref state) 
{
    return ::djinni::c_api::Record<::testsuite::RecordWithEmbeddedCppProto>::make(::djinni::c_api::Protobuf<::djinni::test2::PersistingState>::toCpp(state));
}

djinni_binary_ref testsuite_RecordWithEmbeddedCppProto_get_state(testsuite_RecordWithEmbeddedCppProto_ref instance)
{
    return ::djinni::c_api::Protobuf<::djinni::test2::PersistingState>::fromCpp(::djinni::c_api::Record<::testsuite::RecordWithEmbeddedCppProto>::toCpp(instance).state);
}

void testsuite_RecordWithEmbeddedCppProto_set_state(testsuite_RecordWithEmbeddedCppProto_ref instance, djinni_binary_ref value)
{
    ::djinni::c_api::Record<::testsuite::RecordWithEmbeddedCppProto>::toCpp(instance).state = ::djinni::c_api::Protobuf<::djinni::test2::PersistingState>::toCpp(value);
}


