// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "djinni_c.h"
#include "return_one.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/** Used for C++ multiple inheritance tests */
typedef djinni_interface_ref testsuite_return_one_ref;

testsuite_return_one_ref testsuite_return_one_get_instance();

int8_t testsuite_return_one_return_one(testsuite_return_one_ref instance);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

