// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

#include "reverse_client_interface.h"
#include "djinni_c_translators.hpp"
#include "reverse_client_interface.hpp"
#include <memory>

djinni_string_ref testsuite_reverse_client_interface_return_str(testsuite_reverse_client_interface_ref instance)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::ReverseClientInterface>::toCpp(instance)->return_str();
    return ::djinni::c_api::StringTranslator::fromCpp(std::move(retValue));
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(djinni_string_ref)
}

djinni_string_ref testsuite_reverse_client_interface_meth_taking_interface(testsuite_reverse_client_interface_ref instance, testsuite_reverse_client_interface_ref i)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::ReverseClientInterface>::toCpp(instance)->meth_taking_interface(::djinni::c_api::InterfaceTranslator<::testsuite::ReverseClientInterface>::toCpp(i));
    return ::djinni::c_api::StringTranslator::fromCpp(std::move(retValue));
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(djinni_string_ref)
}

djinni_string_ref testsuite_reverse_client_interface_meth_taking_optional_interface(testsuite_reverse_client_interface_ref instance, testsuite_reverse_client_interface_ref i)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::ReverseClientInterface>::toCpp(instance)->meth_taking_optional_interface(::djinni::c_api::OptionalPtrTranslator<::djinni::c_api::InterfaceTranslator<::testsuite::ReverseClientInterface>>::toCpp(i));
    return ::djinni::c_api::StringTranslator::fromCpp(std::move(retValue));
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(djinni_string_ref)
}

testsuite_reverse_client_interface_ref testsuite_reverse_client_interface_create()
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::testsuite::ReverseClientInterface::create();
    return ::djinni::c_api::InterfaceTranslator<::testsuite::ReverseClientInterface>::fromCpp(std::move(retValue));
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(testsuite_reverse_client_interface_ref)
}


