// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#include "set_record.h"
#include "djinni_c_helpers.hpp"
#include "set_record.hpp"

testsuite_set_record_ref testsuite_set_record_new(djinni_array_ref set, djinni_array_ref iset) 
{
    return ::djinni::c_api::Record<::testsuite::SetRecord>::make(::djinni::c_api::Set<std::string>::toCpp(set, [](auto&& value) { return ::djinni::c_api::String::toCpp(std::forward<decltype(value)>(value)); }), ::djinni::c_api::Set<int32_t>::toCpp(iset, [](auto&& value) { return ::djinni::c_api::Number::toCpp<int32_t>(std::forward<decltype(value)>(value)); }));
}

djinni_array_ref testsuite_set_record_get_set(testsuite_set_record_ref instance)
{
    return ::djinni::c_api::Set<std::string>::fromCpp(::djinni::c_api::Record<::testsuite::SetRecord>::toCpp(instance).set, [](auto&& value) { return ::djinni::c_api::String::fromCpp(std::forward<decltype(value)>(value)); });
}

void testsuite_set_record_set_set(testsuite_set_record_ref instance, djinni_array_ref value)
{
    ::djinni::c_api::Record<::testsuite::SetRecord>::toCpp(instance).set = ::djinni::c_api::Set<std::string>::toCpp(value, [](auto&& value) { return ::djinni::c_api::String::toCpp(std::forward<decltype(value)>(value)); });
}

djinni_array_ref testsuite_set_record_get_iset(testsuite_set_record_ref instance)
{
    return ::djinni::c_api::Set<int32_t>::fromCpp(::djinni::c_api::Record<::testsuite::SetRecord>::toCpp(instance).iset, [](auto&& value) { return ::djinni::c_api::Number::fromCpp<int32_t>(std::forward<decltype(value)>(value)); });
}

void testsuite_set_record_set_iset(testsuite_set_record_ref instance, djinni_array_ref value)
{
    ::djinni::c_api::Record<::testsuite::SetRecord>::toCpp(instance).iset = ::djinni::c_api::Set<int32_t>::toCpp(value, [](auto&& value) { return ::djinni::c_api::Number::toCpp<int32_t>(std::forward<decltype(value)>(value)); });
}


