// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#pragma once

#include "djinni_c.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef djinni_record_ref testsuite_set_record_ref;

testsuite_set_record_ref testsuite_set_record_new(djinni_array_ref set, djinni_array_ref iset);
djinni_array_ref testsuite_set_record_get_set(testsuite_set_record_ref instance);
void testsuite_set_record_set_set(testsuite_set_record_ref instance, djinni_array_ref value);

djinni_array_ref testsuite_set_record_get_iset(testsuite_set_record_ref instance);
void testsuite_set_record_set_iset(testsuite_set_record_ref instance, djinni_array_ref value);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

