// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#include "simple_object.h"
#include "djinni_c_translators.hpp"
#include "simple_object.hpp"

int32_t testsuite_simple_object_get_value(testsuite_simple_object_ref instance)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::SimpleObject>::toCpp(instance)->get_value();
    return std::move(retValue);
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(int32_t)
}

djinni_string_ref testsuite_simple_object_get_name(testsuite_simple_object_ref instance)
{
    DJINNI_HANDLE_EXCEPTION_PROLOGUE
    auto retValue = ::djinni::c_api::InterfaceTranslator<::testsuite::SimpleObject>::toCpp(instance)->get_name();
    return ::djinni::c_api::StringTranslator::fromCpp(std::move(retValue));
    DJINNI_HANDLE_EXCEPTION_EPILOGUE(djinni_string_ref)
}


