// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from user_token.djinni

#pragma once

#include "djinni_c.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef djinni_interface_ref testsuite_user_token_ref;
typedef djinni_proxy_class_ref testsuite_user_token_proxy_class_ref;

typedef struct 
{
    djinni_string_ref (*whoami)(void *);
} testsuite_user_token_method_defs;

testsuite_user_token_proxy_class_ref testsuite_user_token_proxy_class_new(const testsuite_user_token_method_defs *method_defs, djinni_opaque_deallocator opaque_deallocator);

testsuite_user_token_ref testsuite_user_token_new(testsuite_user_token_proxy_class_ref proxy_class, void *opaque);

djinni_string_ref testsuite_user_token_whoami(testsuite_user_token_ref instance);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

