"use strict";
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_perf_benchmark.djinni
exports.__esModule = true;
exports.EnumSixValue = void 0;
var EnumSixValue;
(function (EnumSixValue) {
    EnumSixValue[EnumSixValue["FIRST"] = 0] = "FIRST";
    EnumSixValue[EnumSixValue["SECOND"] = 1] = "SECOND";
    EnumSixValue[EnumSixValue["THIRD"] = 2] = "THIRD";
    EnumSixValue[EnumSixValue["FOURTH"] = 3] = "FOURTH";
    EnumSixValue[EnumSixValue["FIFTH"] = 4] = "FIFTH";
    EnumSixValue[EnumSixValue["SIXTH"] = 5] = "SIXTH";
})(EnumSixValue = exports.EnumSixValue || (exports.EnumSixValue = {}));
