// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "SwiftSortOrder.hpp"  // my header

namespace djinni_generated {


} // namespace djinni_generated
