// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "textbox_listener.hpp"

namespace djinni_generated {

using SwiftTextboxListener = djinni::swift::Interface<::textsort::TextboxListener>;

} // namespace djinni_generated
