// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_perf_benchmark.djinni

#pragma once

namespace snapchat { namespace djinni { namespace benchmark {

/** interfaces for platform Java or Objective-C objects, to be passed to C++ */
class ObjectPlatform {
public:
    virtual ~ObjectPlatform() = default;

    virtual void onDone() = 0;
};

} } }  // namespace snapchat::djinni::benchmark
