// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "Future.hpp"
#include <cstdint>
#include <string>

namespace testsuite {

class AsyncInterface {
public:
    virtual ~AsyncInterface() = default;

    virtual ::snapchat::djinni::Future<std::string> future_roundtrip(::snapchat::djinni::Future<int32_t> f) = 0;
};

}  // namespace testsuite
