// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#include "color.hpp"  // my header

namespace testsuite {

const char* to_string(color e) noexcept {
    static const char* names[] = {
        "red",
        "orange",
        "yellow",
        "green",
        "blue",
        "indigo",
        "violet",
    };
    return names[static_cast<int>(e)];
}

}  // namespace testsuite
