// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#include "constant_enum.hpp"  // my header

namespace testsuite {

const char* to_string(constant_enum e) noexcept {
    static const char* names[] = {
        "some_value",
        "some_other_value",
    };
    return names[static_cast<int>(e)];
}

}  // namespace testsuite
