// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#pragma once

namespace testsuite {

/** Blank interface used for testing */
class OptionalInterface {
public:
    virtual ~OptionalInterface() = default;
};

} // namespace testsuite
