// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

#pragma once

#include "../../handwritten-src/cpp/optional.hpp"
#include <cstdint>
#include <utility>
#include <vector>

namespace testsuite {

struct PrimitiveList final {
    std::vector<int64_t> list;
    std::experimental::optional<std::vector<std::experimental::optional<int64_t>>> optional_list;

    PrimitiveList(std::vector<int64_t> list_,
                  std::experimental::optional<std::vector<std::experimental::optional<int64_t>>> optional_list_)
    : list(std::move(list_))
    , optional_list(std::move(optional_list_))
    {}

    //NOLINTNEXTLINE(google-explicit-constructor)
    PrimitiveList(std::vector<int64_t> list_)
    : PrimitiveList(std::move(list_),
                    std::experimental::nullopt)
    {}
};

} // namespace testsuite
