// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#pragma once

#include "proto/cpp/test.pb.h"
#include <utility>

namespace testsuite {

struct RecordWithEmbeddedProto final {
    ::djinni::test::Person person;

    //NOLINTNEXTLINE(google-explicit-constructor)
    RecordWithEmbeddedProto(::djinni::test::Person person_)
    : person(std::move(person_))
    {}
};

}  // namespace testsuite
