// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#pragma once

#include "proto/cpp/test.pb.h"
#include <utility>

namespace testsuite {

struct RecordWithProtobufEnum final {
    ::djinni::test::Person_PhoneType phone_type;
    ::djinni::test::Priority priority;

    RecordWithProtobufEnum(::djinni::test::Person_PhoneType phone_type_,
                           ::djinni::test::Priority priority_)
    : phone_type(std::move(phone_type_))
    , priority(std::move(priority_))
    {}
};

} // namespace testsuite
