// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

#pragma once

#include "Lazy.hpp"
#include <cstdint>
#include <memory>
#include <string>

namespace testsuite {

class SimpleObject;
struct NestedLazy;
struct NestedLazyInterface;

class TestLazy {
public:
    virtual ~TestLazy() = default;

    /** Simple type lazy tests */
    static ::djinni::Lazy<std::string> getLazyString();

    static ::djinni::Lazy<int32_t> getLazyInt();

    static std::string callLazyString(const ::djinni::Lazy<std::string> & x);

    static int32_t callLazyInt(const ::djinni::Lazy<int32_t> & x);

    static NestedLazy getNestedLazy();

    static int32_t callNestedLazy(const NestedLazy & x);

    /** Interface lazy tests - main use case for deferred expensive object creation */
    static ::djinni::Lazy</*not-null*/ std::shared_ptr<SimpleObject>> getLazyObject();

    static int32_t callLazyObject(const ::djinni::Lazy</*not-null*/ std::shared_ptr<SimpleObject>> & x);

    static std::string callLazyObjectGetName(const ::djinni::Lazy</*not-null*/ std::shared_ptr<SimpleObject>> & x);

    static NestedLazyInterface getNestedLazyInterface();

    static int32_t callNestedLazyInterface(const NestedLazyInterface & x);

    /** Helper to create simple_object for testing */
    static /*not-null*/ std::shared_ptr<SimpleObject> createSimpleObject(int32_t value, const std::string & name);
};

} // namespace testsuite
