// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from interface_and_abstract_class.djinni

#pragma once

namespace testsuite {

class TestJavaAbstractClassOnly {
public:
    virtual ~TestJavaAbstractClassOnly() = default;

    static bool test_method();
};

} // namespace testsuite
