// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from interface_and_abstract_class.djinni

#pragma once

namespace testsuite {

class TestJavaInterfaceOnly {
public:
    virtual ~TestJavaInterfaceOnly() = default;

    virtual bool test_method() = 0;
};

}  // namespace testsuite
