// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

#pragma once

namespace testsuite {

class ThrowingInterface {
public:
    virtual ~ThrowingInterface() = default;

    virtual void throw_exception() = 0;
};

} // namespace testsuite
