// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from array.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace testsuite {

struct Vec2 final {
    int32_t x;
    int32_t y;

    friend bool operator==(const Vec2& lhs, const Vec2& rhs);
    friend bool operator!=(const Vec2& lhs, const Vec2& rhs);

    //NOLINTNEXTLINE(google-explicit-constructor)
    Vec2(int32_t x_,
         int32_t y_)
    : x(std::move(x_))
    , y(std::move(y_))
    {}
};

}  // namespace testsuite
