// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "map_record.hpp"

namespace djinni_generated {

struct NativeMapRecord
{
    using CppType = ::testsuite::MapRecord;
    using JsType = em::val;
    using Boxed = NativeMapRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
