// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "set_record.hpp"

namespace djinni_generated {

struct NativeSetRecord
{
    using CppType = ::testsuite::SetRecord;
    using JsType = em::val;
    using Boxed = NativeSetRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
