// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#include "NativeConstantEnum.hpp"  // my header

namespace djinni_generated {

EM_JS(void, djinni_init_testsuite_constant_enum, (), {
    Module.ConstantEnum =  {
        SOME_VALUE: 0, SOME_OTHER_VALUE: 1
    }
})

EMSCRIPTEN_BINDINGS(constant_enum) {
    djinni_init_testsuite_constant_enum();
}

}  // namespace djinni_generated
