// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum_flags.djinni

#include "NativeEmptyFlags.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init_testsuite_empty_flags_consts, (), {
        Module.testsuite_EmptyFlags =  {
            NONE : 0,
            ALL : (1 << 0) - 1,
        }
    })
}

void NativeEmptyFlags::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_testsuite_empty_flags_consts();
        ::djinni::djinni_register_name_in_ns("testsuite_EmptyFlags", "testsuite.EmptyFlags");
    });
}

EMSCRIPTEN_BINDINGS(testsuite_empty_flags) {
    NativeEmptyFlags::staticInitializeConstants();
}

}  // namespace djinni_generated
