// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

#include "NativeNestedLazyInterface.hpp"  // my header
#include "Lazy_wasm.hpp"
#include "NativeSimpleObject.hpp"

namespace djinni_generated {

auto NativeNestedLazyInterface::toCpp(const JsType& j) -> CppType {
    return {::djinni::LazyAdaptor<::djinni_generated::NativeSimpleObject>::Boxed::toCpp(j["obj"])};
}
auto NativeNestedLazyInterface::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("obj", ::djinni::LazyAdaptor<::djinni_generated::NativeSimpleObject>::Boxed::fromCpp(c.obj));
    return js;
}

} // namespace djinni_generated
