// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#include "NativeConstants.hpp"  // my header

namespace djinni_generated {

auto NativeConstants::toCpp(const JsType& j) -> CppType {
    return {};
}
auto NativeConstants::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    return js;
}

}  // namespace djinni_generated
