// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#include "NativeSimpleObject.hpp"  // my header

namespace djinni_generated {

em::val NativeSimpleObject::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getValue",
        "getName",
    });
    return methods;
}

int32_t NativeSimpleObject::get_value(const CppType& self) {
    try {
        auto r = self->get_value();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
std::string NativeSimpleObject::get_name(const CppType& self) {
    try {
        auto r = self->get_name();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(testsuite_simple_object) {
    ::djinni::DjinniClass_<::testsuite::SimpleObject>("testsuite_SimpleObject", "testsuite.SimpleObject")
        .smart_ptr<std::shared_ptr<::testsuite::SimpleObject>>("testsuite_SimpleObject")
        .function("nativeDestroy", &NativeSimpleObject::nativeDestroy)
        .function("getValue", NativeSimpleObject::get_value)
        .function("getName", NativeSimpleObject::get_name)
        ;
}

} // namespace djinni_generated
