// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#include "NativeConflict.hpp"  // my header

namespace djinni_generated {

em::val NativeConflict::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}


EMSCRIPTEN_BINDINGS(testsuite_Conflict) {
    ::djinni::DjinniClass_<::testsuite::Conflict>("testsuite_Conflict", "testsuite.Conflict")
        .smart_ptr<std::shared_ptr<::testsuite::Conflict>>("testsuite_Conflict")
        .function("nativeDestroy", &NativeConflict::nativeDestroy)
        ;
}

}  // namespace djinni_generated
