// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "nested_supplier_interface.hpp"

namespace djinni_generated {

struct NativeNestedSupplierInterface
{
    using CppType = ::testsuite::NestedSupplierInterface;
    using JsType = em::val;
    using Boxed = NativeNestedSupplierInterface;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
