// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "second_listener.hpp"

namespace djinni_generated {

struct NativeSecondListener : ::djinni::JsInterface<::testsuite::SecondListener, NativeSecondListener> {
    using CppType = std::shared_ptr<::testsuite::SecondListener>;
    using CppOptType = std::shared_ptr<::testsuite::SecondListener>;
    using JsType = em::val;
    using Boxed = NativeSecondListener;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) { return fromCppOpt(c); }

    static em::val cppProxyMethods();

    static void second(const CppType& self);

    struct JsProxy: ::djinni::JsProxyBase, ::testsuite::SecondListener, ::djinni::InstanceTracker<JsProxy> {
        JsProxy(const em::val& v) : JsProxyBase(v) {}
        void second() override;
    };
};

}  // namespace djinni_generated
