// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#include "NativeClientReturnedRecord.hpp"  // my header

namespace djinni_generated {

auto NativeClientReturnedRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::I64::Boxed::toCpp(j["mRecordId"]),
            ::djinni::String::Boxed::toCpp(j["mContent"]),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::Boxed::toCpp(j["mMisc"])};
}
auto NativeClientReturnedRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("mRecordId", ::djinni::I64::Boxed::fromCpp(c.record_id));
    js.set("mContent", ::djinni::String::Boxed::fromCpp(c.content));
    js.set("mMisc", ::djinni::Optional<std::experimental::optional, ::djinni::String>::Boxed::fromCpp(c.misc));
    return js;
}

}  // namespace djinni_generated
