// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "record_using_extended_record.hpp"

namespace djinni_generated {

struct NativeRecordUsingExtendedRecord
{
    using CppType = ::testsuite::RecordUsingExtendedRecord;
    using JsType = em::val;
    using Boxed = NativeRecordUsingExtendedRecord;
    
    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
