// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum_flags.djinni

#include "NativeEmptyFlags.hpp"  // my header

namespace djinni_generated {

EM_JS(void, djinni_init_testsuite_empty_flags, (), {
    Module.EmptyFlags =  {
        NONE: 0, ALL: 1
    }
})

EMSCRIPTEN_BINDINGS(empty_flags) {
    djinni_init_testsuite_empty_flags();
}

}  // namespace djinni_generated
