// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#pragma once

#include "constant_with_enum.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeConstantWithEnum
{
    using CppType = ::testsuite::ConstantWithEnum;
    using JsType = em::val;
    using Boxed = NativeConstantWithEnum;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
