// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#include "NativeWcharTestHelpers.hpp"  // my header
#include "NativeWcharTestRec.hpp"

namespace djinni_generated {

em::val NativeWcharTestHelpers::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getRecord",
        "getString",
        "checkString",
        "checkRecord",
    });
    return methods;
}

em::val NativeWcharTestHelpers::get_record() {
    return ::djinni_generated::NativeWcharTestRec::fromCpp(::testsuite::WcharTestHelpers::get_record());
}
std::wstring NativeWcharTestHelpers::get_string() {
    return ::djinni::WString::fromCpp(::testsuite::WcharTestHelpers::get_string());
}
bool NativeWcharTestHelpers::check_string(const std::wstring& w_str) {
    return ::djinni::Bool::fromCpp(::testsuite::WcharTestHelpers::check_string(::djinni::WString::toCpp(w_str)));
}
bool NativeWcharTestHelpers::check_record(const em::val& w_rec) {
    return ::djinni::Bool::fromCpp(::testsuite::WcharTestHelpers::check_record(::djinni_generated::NativeWcharTestRec::toCpp(w_rec)));
}

EMSCRIPTEN_BINDINGS(wchar_test_helpers) {
    em::class_<::testsuite::WcharTestHelpers>("WcharTestHelpers")
        .smart_ptr<std::shared_ptr<::testsuite::WcharTestHelpers>>("WcharTestHelpers")
        .function("nativeDestroy", &NativeWcharTestHelpers::nativeDestroy)
        .class_function("getRecord", NativeWcharTestHelpers::get_record)
        .class_function("getString", NativeWcharTestHelpers::get_string)
        .class_function("checkString", NativeWcharTestHelpers::check_string)
        .class_function("checkRecord", NativeWcharTestHelpers::check_record)
        ;
}

}  // namespace djinni_generated
