// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#include "NativeReverseClientInterface.hpp"  // my header

namespace djinni_generated {

em::val NativeReverseClientInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "returnStr",
        "methTakingInterface",
        "methTakingOptionalInterface",
    });
    return methods;
}

std::string NativeReverseClientInterface::return_str(const CppType& self) {
    auto r = self->return_str();
    return ::djinni::String::fromCpp(r);
}
std::string NativeReverseClientInterface::meth_taking_interface(const CppType& self, const em::val& w_i) {
    auto r = self->meth_taking_interface(::djinni_generated::NativeReverseClientInterface::toCpp(w_i));
    return ::djinni::String::fromCpp(r);
}
std::string NativeReverseClientInterface::meth_taking_optional_interface(const CppType& self, const em::val& w_i) {
    auto r = self->meth_taking_optional_interface(::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeReverseClientInterface>::toCpp(w_i));
    return ::djinni::String::fromCpp(r);
}
em::val NativeReverseClientInterface::create() {
    auto r = ::testsuite::ReverseClientInterface::create();
    return ::djinni_generated::NativeReverseClientInterface::fromCpp(r);
}

namespace {
    EM_JS(void, djinni_init_testsuite_reverse_client_interface, (), {
        'testsuite'.split('.').reduce(function(path, part) {
            if (!path.hasOwnProperty(part)) { path[part] = {}}; 
            return path[part]
        }, Module);
        Module.testsuite.ReverseClientInterface = Module.testsuite_ReverseClientInterface
    })
}
void NativeReverseClientInterface::staticInitialize() {
    static std::once_flag initOnce;
    std::call_once(initOnce, djinni_init_testsuite_reverse_client_interface);
}
EMSCRIPTEN_BINDINGS(testsuite_reverse_client_interface) {
    em::class_<::testsuite::ReverseClientInterface>("testsuite_ReverseClientInterface")
        .smart_ptr<std::shared_ptr<::testsuite::ReverseClientInterface>>("testsuite_ReverseClientInterface")
        .function("nativeDestroy", &NativeReverseClientInterface::nativeDestroy)
        .function("returnStr", NativeReverseClientInterface::return_str)
        .function("methTakingInterface", NativeReverseClientInterface::meth_taking_interface)
        .function("methTakingOptionalInterface", NativeReverseClientInterface::meth_taking_optional_interface)
        .class_function("create", NativeReverseClientInterface::create)
        ;
    NativeReverseClientInterface::staticInitialize();
}

}  // namespace djinni_generated
