// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#include "NativeMixedRecord.hpp"  // my header
#include "NativeBaseRecord.hpp"
#include "NativeOptionalInterface.hpp"

namespace djinni_generated {

auto NativeMixedRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeOptionalInterface>::Boxed::toCpp(j["interfaceVal"]),
            ::djinni::I32::Boxed::toCpp(j["reqInt"]),
            ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeBaseRecord>::Boxed::toCpp(j["optRecord"]),
            ::djinni_generated::NativeBaseRecord::Boxed::toCpp(j["reqRecord"])};
}
auto NativeMixedRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("interfaceVal", ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeOptionalInterface>::Boxed::fromCpp(c.interfaceVal));
    js.set("reqInt", ::djinni::I32::Boxed::fromCpp(c.reqInt));
    js.set("optRecord", ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeBaseRecord>::Boxed::fromCpp(c.optRecord));
    js.set("reqRecord", ::djinni_generated::NativeBaseRecord::Boxed::fromCpp(c.reqRecord));
    return js;
}

} // namespace djinni_generated
