// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

#include "NativeEnumUsageInterface.hpp"  // my header
#include "NativeColor.hpp"

namespace djinni_generated {

em::val NativeEnumUsageInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "e",
        "o",
        "l",
        "s",
        "m",
    });
    return methods;
}

int32_t NativeEnumUsageInterface::e(const CppType& self, int32_t w_e) {
    try {
        auto r = self->e(::djinni_generated::NativeColor::toCpp(w_e));
        return ::djinni_generated::NativeColor::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeColor>::handleNativeException(e);
    }
}
em::val NativeEnumUsageInterface::o(const CppType& self, const em::val& w_o) {
    try {
        auto r = self->o(::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeColor>::toCpp(w_o));
        return ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeColor>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeColor>>::handleNativeException(e);
    }
}
em::val NativeEnumUsageInterface::l(const CppType& self, const em::val& w_l) {
    try {
        auto r = self->l(::djinni::List<::djinni_generated::NativeColor>::toCpp(w_l));
        return ::djinni::List<::djinni_generated::NativeColor>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::List<::djinni_generated::NativeColor>>::handleNativeException(e);
    }
}
em::val NativeEnumUsageInterface::s(const CppType& self, const em::val& w_s) {
    try {
        auto r = self->s(::djinni::Set<::djinni_generated::NativeColor>::toCpp(w_s));
        return ::djinni::Set<::djinni_generated::NativeColor>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Set<::djinni_generated::NativeColor>>::handleNativeException(e);
    }
}
em::val NativeEnumUsageInterface::m(const CppType& self, const em::val& w_m) {
    try {
        auto r = self->m(::djinni::Map<::djinni_generated::NativeColor, ::djinni_generated::NativeColor>::toCpp(w_m));
        return ::djinni::Map<::djinni_generated::NativeColor, ::djinni_generated::NativeColor>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Map<::djinni_generated::NativeColor, ::djinni_generated::NativeColor>>::handleNativeException(e);
    }
}

::testsuite::color NativeEnumUsageInterface::JsProxy::e(::testsuite::color e) {
    auto ret = callMethod("e", ::djinni_generated::NativeColor::fromCpp(e));
    checkError(ret);
    return ::djinni_generated::NativeColor::toCpp(ret.as<int32_t>());
}

std::experimental::optional<::testsuite::color> NativeEnumUsageInterface::JsProxy::o(std::experimental::optional<::testsuite::color> o) {
    auto ret = callMethod("o", ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeColor>::fromCpp(o));
    checkError(ret);
    return ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeColor>::toCpp(ret);
}

std::vector<::testsuite::color> NativeEnumUsageInterface::JsProxy::l(const std::vector<::testsuite::color> & l) {
    auto ret = callMethod("l", ::djinni::List<::djinni_generated::NativeColor>::fromCpp(l));
    checkError(ret);
    return ::djinni::List<::djinni_generated::NativeColor>::toCpp(ret);
}

std::unordered_set<::testsuite::color> NativeEnumUsageInterface::JsProxy::s(const std::unordered_set<::testsuite::color> & s) {
    auto ret = callMethod("s", ::djinni::Set<::djinni_generated::NativeColor>::fromCpp(s));
    checkError(ret);
    return ::djinni::Set<::djinni_generated::NativeColor>::toCpp(ret);
}

std::unordered_map<::testsuite::color, ::testsuite::color> NativeEnumUsageInterface::JsProxy::m(const std::unordered_map<::testsuite::color, ::testsuite::color> & m) {
    auto ret = callMethod("m", ::djinni::Map<::djinni_generated::NativeColor, ::djinni_generated::NativeColor>::fromCpp(m));
    checkError(ret);
    return ::djinni::Map<::djinni_generated::NativeColor, ::djinni_generated::NativeColor>::toCpp(ret);
}

EMSCRIPTEN_BINDINGS(testsuite_enum_usage_interface) {
    ::djinni::DjinniClass_<::testsuite::EnumUsageInterface>("testsuite_EnumUsageInterface", "testsuite.EnumUsageInterface")
        .smart_ptr<std::shared_ptr<::testsuite::EnumUsageInterface>>("testsuite_EnumUsageInterface")
        .function("nativeDestroy", &NativeEnumUsageInterface::nativeDestroy)
        .function("e", NativeEnumUsageInterface::e)
        .function("o", NativeEnumUsageInterface::o)
        .function("l", NativeEnumUsageInterface::l)
        .function("s", NativeEnumUsageInterface::s)
        .function("m", NativeEnumUsageInterface::m)
        ;
}

} // namespace djinni_generated
