// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

#include "NativeReturnTwo.hpp"  // my header

namespace djinni_generated {

em::val NativeReturnTwo::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "returnTwo",
    });
    return methods;
}

em::val NativeReturnTwo::get_instance() {
    try {
        auto r = ::testsuite::ReturnTwo::get_instance();
        return ::djinni_generated::NativeReturnTwo::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e.what());
        throw;
    }
}
int8_t NativeReturnTwo::return_two(const CppType& self) {
    try {
        auto r = self->return_two();
        return ::djinni::I8::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e.what());
        throw;
    }
}

EMSCRIPTEN_BINDINGS(testsuite_return_two) {
    ::djinni::DjinniClass_<::testsuite::ReturnTwo>("testsuite_ReturnTwo", "testsuite.ReturnTwo")
        .smart_ptr<std::shared_ptr<::testsuite::ReturnTwo>>("testsuite_ReturnTwo")
        .function("nativeDestroy", &NativeReturnTwo::nativeDestroy)
        .class_function("getInstance", NativeReturnTwo::get_instance)
        .function("returnTwo", NativeReturnTwo::return_two)
        ;
}

}  // namespace djinni_generated
