// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum_flags.djinni

#include "NativeEmptyFlags.hpp"  // my header

namespace djinni_generated {

namespace testsuite {
    EM_JS(void, djinni_init_empty_flags, (), {
        Module.EmptyFlags =  {
            NONE : 0,
            ALL : (1 << 0) - 1,
        }
    })
}

EMSCRIPTEN_BINDINGS(empty_flags) {
    testsuite::djinni_init_empty_flags();
}

}  // namespace djinni_generated
