// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

#include "NativeRecordWithDurationAndDerivings.hpp"  // my header
#include "Duration-wasm.hpp"

namespace djinni_generated {

auto NativeRecordWithDurationAndDerivings::toCpp(const JsType& j) -> CppType {
    return {::djinni::Duration<::djinni::F64, ::djinni::Duration_ns>::Boxed::toCpp(j["dt"])};
}
auto NativeRecordWithDurationAndDerivings::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("dt", ::djinni::Duration<::djinni::F64, ::djinni::Duration_ns>::Boxed::fromCpp(c.dt));
    return js;
}

}  // namespace djinni_generated
