// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#include "NativeReturnOne.hpp"  // my header

namespace djinni_generated {

em::val NativeReturnOne::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "returnOne",
    });
    return methods;
}

em::val NativeReturnOne::get_instance() {
    auto r = ::testsuite::ReturnOne::get_instance();
    return ::djinni_generated::NativeReturnOne::fromCpp(r);
}
int8_t NativeReturnOne::return_one(const CppType& self) {
    auto r = self->return_one();
    return ::djinni::I8::fromCpp(r);
}

namespace {
    EM_JS(void, djinni_init_testsuite_return_one, (), {
        'testsuite'.split('.').reduce(function(path, part) {
            if (!path.hasOwnProperty(part)) { path[part] = {}}; 
            return path[part]
        }, Module);
        Module.testsuite.ReturnOne = Module.testsuite_ReturnOne
    })
}
void NativeReturnOne::staticInitialize() {
    static std::once_flag initOnce;
    std::call_once(initOnce, djinni_init_testsuite_return_one);
}
EMSCRIPTEN_BINDINGS(testsuite_return_one) {
    em::class_<::testsuite::ReturnOne>("testsuite_ReturnOne")
        .smart_ptr<std::shared_ptr<::testsuite::ReturnOne>>("testsuite_ReturnOne")
        .function("nativeDestroy", &NativeReturnOne::nativeDestroy)
        .class_function("getInstance", NativeReturnOne::get_instance)
        .function("returnOne", NativeReturnOne::return_one)
        ;
    NativeReturnOne::staticInitialize();
}

}  // namespace djinni_generated
