// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "primitive_list.hpp"

namespace djinni_generated {

struct NativePrimitiveList
{
    using CppType = ::testsuite::PrimitiveList;
    using JsType = em::val;
    using Boxed = NativePrimitiveList;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
