// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#include "NativeTestProvider.hpp"  // my header
#include "NativeNestedProvider.hpp"
#include "NativeNestedProviderInterface.hpp"
#include "NativeSimpleObject.hpp"
#include "Provider_wasm.hpp"

namespace djinni_generated {

em::val NativeTestProvider::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

em::val NativeTestProvider::getProviderString() {
    try {
        auto r = ::testsuite::TestProvider::getProviderString();
        return ::djinni::ProviderAdaptor<::djinni::String>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::ProviderAdaptor<::djinni::String>>::handleNativeException(e);
    }
}
em::val NativeTestProvider::getProviderInt() {
    try {
        auto r = ::testsuite::TestProvider::getProviderInt();
        return ::djinni::ProviderAdaptor<::djinni::I32>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::ProviderAdaptor<::djinni::I32>>::handleNativeException(e);
    }
}
std::string NativeTestProvider::callProviderString(const em::val& w_x) {
    try {
        auto r = ::testsuite::TestProvider::callProviderString(::djinni::ProviderAdaptor<::djinni::String>::toCpp(w_x));
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
int32_t NativeTestProvider::callProviderInt(const em::val& w_x) {
    try {
        auto r = ::testsuite::TestProvider::callProviderInt(::djinni::ProviderAdaptor<::djinni::I32>::toCpp(w_x));
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
em::val NativeTestProvider::getNestedProvider() {
    try {
        auto r = ::testsuite::TestProvider::getNestedProvider();
        return ::djinni_generated::NativeNestedProvider::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeNestedProvider>::handleNativeException(e);
    }
}
int32_t NativeTestProvider::callNestedProvider(const em::val& w_x) {
    try {
        auto r = ::testsuite::TestProvider::callNestedProvider(::djinni_generated::NativeNestedProvider::toCpp(w_x));
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
em::val NativeTestProvider::getProviderObject() {
    try {
        auto r = ::testsuite::TestProvider::getProviderObject();
        return ::djinni::ProviderAdaptor<::djinni_generated::NativeSimpleObject>::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::ProviderAdaptor<::djinni_generated::NativeSimpleObject>>::handleNativeException(e);
    }
}
int32_t NativeTestProvider::callProviderObject(const em::val& w_x) {
    try {
        auto r = ::testsuite::TestProvider::callProviderObject(::djinni::ProviderAdaptor<::djinni_generated::NativeSimpleObject>::toCpp(w_x));
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
std::string NativeTestProvider::callProviderObjectGetName(const em::val& w_x) {
    try {
        auto r = ::testsuite::TestProvider::callProviderObjectGetName(::djinni::ProviderAdaptor<::djinni_generated::NativeSimpleObject>::toCpp(w_x));
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
em::val NativeTestProvider::getNestedProviderInterface() {
    try {
        auto r = ::testsuite::TestProvider::getNestedProviderInterface();
        return ::djinni_generated::NativeNestedProviderInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeNestedProviderInterface>::handleNativeException(e);
    }
}
int32_t NativeTestProvider::callNestedProviderInterface(const em::val& w_x) {
    try {
        auto r = ::testsuite::TestProvider::callNestedProviderInterface(::djinni_generated::NativeNestedProviderInterface::toCpp(w_x));
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
em::val NativeTestProvider::createSimpleObject(int32_t w_value,const std::string& w_name) {
    try {
        auto r = ::testsuite::TestProvider::createSimpleObject(::djinni::I32::toCpp(w_value),
                           ::djinni::String::toCpp(w_name));
        return ::djinni_generated::NativeSimpleObject::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeSimpleObject>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(testsuite_test_provider) {
    ::djinni::DjinniClass_<::testsuite::TestProvider>("testsuite_TestProvider", "testsuite.TestProvider")
        .smart_ptr<std::shared_ptr<::testsuite::TestProvider>>("testsuite_TestProvider")
        .function("nativeDestroy", &NativeTestProvider::nativeDestroy)
        .class_function("getProviderString", NativeTestProvider::getProviderString)
        .class_function("getProviderInt", NativeTestProvider::getProviderInt)
        .class_function("callProviderString", NativeTestProvider::callProviderString)
        .class_function("callProviderInt", NativeTestProvider::callProviderInt)
        .class_function("getNestedProvider", NativeTestProvider::getNestedProvider)
        .class_function("callNestedProvider", NativeTestProvider::callNestedProvider)
        .class_function("getProviderObject", NativeTestProvider::getProviderObject)
        .class_function("callProviderObject", NativeTestProvider::callProviderObject)
        .class_function("callProviderObjectGetName", NativeTestProvider::callProviderObjectGetName)
        .class_function("getNestedProviderInterface", NativeTestProvider::getNestedProviderInterface)
        .class_function("callNestedProviderInterface", NativeTestProvider::callNestedProviderInterface)
        .class_function("createSimpleObject", NativeTestProvider::createSimpleObject)
        ;
}

} // namespace djinni_generated
