// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include "color.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeColor: ::djinni::WasmEnum<::testsuite::color> {
    static void staticInitialize();
};

}  // namespace djinni_generated
