// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_token.djinni

#include "NativeUserToken.hpp"  // my header

namespace djinni_generated {

em::val NativeUserToken::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "whoami",
    });
    return methods;
}

std::string NativeUserToken::whoami(const CppType& self) {
    return ::djinni::String::fromCpp(self->whoami());
}

std::string NativeUserToken::JsProxy::whoami() {
    return ::djinni::String::toCpp(_jsRef().call<std::string>("whoami"));
}

EMSCRIPTEN_BINDINGS(user_token) {
    em::class_<::testsuite::UserToken>("UserToken")
        .smart_ptr<std::shared_ptr<::testsuite::UserToken>>("UserToken")
        .function("nativeDestroy", &NativeUserToken::nativeDestroy)
        .function("whoami", NativeUserToken::whoami)
        ;
}

}  // namespace djinni_generated
