// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

#include "NativeVarnameInterface.hpp"  // my header
#include "NativeVarnameRecord.hpp"

namespace djinni_generated {

em::val NativeVarnameInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "Rmethod",
        "Imethod",
    });
    return methods;
}

em::val NativeVarnameInterface::_rmethod_(const CppType& self, const em::val& w__r_arg_) {
    try {
        auto r = self->_rmethod_(::djinni_generated::NativeVarnameRecord::toCpp(w__r_arg_));
        return ::djinni_generated::NativeVarnameRecord::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni_generated::NativeVarnameRecord>::handleNativeException(e);
    }
}
em::val NativeVarnameInterface::_imethod_(const CppType& self, const em::val& w__i_arg_) {
    try {
        auto r = self->_imethod_(::djinni_generated::NativeVarnameInterface::toCpp(w__i_arg_));
        return ::djinni_generated::NativeVarnameInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni_generated::NativeVarnameInterface>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(testsuite__varname_interface_) {
    ::djinni::DjinniClass_<::testsuite::VarnameInterface>("testsuite_VarnameInterface", "testsuite.VarnameInterface")
        .smart_ptr<std::shared_ptr<::testsuite::VarnameInterface>>("testsuite_VarnameInterface")
        .function("nativeDestroy", &NativeVarnameInterface::nativeDestroy)
        .function("Rmethod", NativeVarnameInterface::_rmethod_)
        .function("Imethod", NativeVarnameInterface::_imethod_)
        ;
}

} // namespace djinni_generated
