// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "mixed_record.hpp"

namespace djinni_generated {

struct NativeMixedRecord
{
    using CppType = ::testsuite::MixedRecord;
    using JsType = em::val;
    using Boxed = NativeMixedRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
