// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#include "NativeWcharTestHelpers.hpp"  // my header
#include "NativeWcharTestRec.hpp"

namespace djinni_generated {

em::val NativeWcharTestHelpers::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

em::val NativeWcharTestHelpers::get_record() {
    auto r = ::testsuite::WcharTestHelpers::get_record();
    return ::djinni_generated::NativeWcharTestRec::fromCpp(r);
}
std::wstring NativeWcharTestHelpers::get_string() {
    auto r = ::testsuite::WcharTestHelpers::get_string();
    return ::djinni::WString::fromCpp(r);
}
bool NativeWcharTestHelpers::check_string(const std::wstring& w_str) {
    auto r = ::testsuite::WcharTestHelpers::check_string(::djinni::WString::toCpp(w_str));
    return ::djinni::Bool::fromCpp(r);
}
bool NativeWcharTestHelpers::check_record(const em::val& w_rec) {
    auto r = ::testsuite::WcharTestHelpers::check_record(::djinni_generated::NativeWcharTestRec::toCpp(w_rec));
    return ::djinni::Bool::fromCpp(r);
}

namespace {
    EM_JS(void, djinni_init_testsuite_wchar_test_helpers, (), {
        'testsuite'.split('.').reduce(function(path, part) {
            if (!(part in path)) { path[part] = {}}; 
            return path[part]
        }, Module);
        Module.testsuite.WcharTestHelpers = Module.testsuite_WcharTestHelpers
    })
}
void NativeWcharTestHelpers::staticInitialize() {
    static std::once_flag initOnce;
    std::call_once(initOnce, djinni_init_testsuite_wchar_test_helpers);
}
EMSCRIPTEN_BINDINGS(testsuite_wchar_test_helpers) {
    em::class_<::testsuite::WcharTestHelpers>("testsuite_WcharTestHelpers")
        .smart_ptr<std::shared_ptr<::testsuite::WcharTestHelpers>>("testsuite_WcharTestHelpers")
        .function("nativeDestroy", &NativeWcharTestHelpers::nativeDestroy)
        .class_function("getRecord", NativeWcharTestHelpers::get_record)
        .class_function("getString", NativeWcharTestHelpers::get_string)
        .class_function("checkString", NativeWcharTestHelpers::check_string)
        .class_function("checkRecord", NativeWcharTestHelpers::check_record)
        ;
    NativeWcharTestHelpers::staticInitialize();
}

}  // namespace djinni_generated
