// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "optional_record.hpp"

namespace djinni_generated {

struct NativeOptionalRecord
{
    using CppType = ::testsuite::OptionalRecord;
    using JsType = em::val;
    using Boxed = NativeOptionalRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
