// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "client_interface.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeClientInterface : ::djinni::JsInterface<::testsuite::ClientInterface, NativeClientInterface> {
    using CppType = std::shared_ptr<::testsuite::ClientInterface>;
    using CppOptType = std::shared_ptr<::testsuite::ClientInterface>;
    using JsType = em::val;
    using Boxed = NativeClientInterface;
    
    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) { return fromCppOpt(c); }
    
    static em::val cppProxyMethods();
    
    static em::val get_record(const CppType& self, int64_t w_record_id,const std::string& w_utf8string,const em::val& w_misc);
    static double identifier_check(const CppType& self, const em::val& w_data,int32_t w_r,int64_t w_jret);
    static std::string return_str(const CppType& self);
    static std::string meth_taking_interface(const CppType& self, const em::val& w_i);
    static std::string meth_taking_optional_interface(const CppType& self, const em::val& w_i);
    
    struct JsProxy: ::djinni::JsProxyBase, ::testsuite::ClientInterface, ::djinni::InstanceTracker<JsProxy> {
        JsProxy(const em::val& v) : JsProxyBase(v) {}
        ::testsuite::ClientReturnedRecord get_record(int64_t record_id,const std::string & utf8string,const std::experimental::optional<std::string> & misc) override;
        double identifier_check(const std::vector<uint8_t> & data,int32_t r,int64_t jret) override;
        std::string return_str() override;
        std::string meth_taking_interface(const std::shared_ptr<::testsuite::ClientInterface> & i) override;
        std::string meth_taking_optional_interface(const std::shared_ptr<::testsuite::ClientInterface> & i) override;
    };
};

}  // namespace djinni_generated
