// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum_flags.djinni

#include "NativeAccessFlags.hpp"  // my header

namespace djinni_generated {

EM_JS(void, djinni_init_testsuite_access_flags, (), {
    Module.AccessFlags =  {
        NOBODY: 0, OWNER_READ: 1, OWNER_WRITE: 2, OWNER_EXECUTE: 3, GROUP_READ: 4, GROUP_WRITE: 5, GROUP_EXECUTE: 6, SYSTEM_READ: 7, SYSTEM_WRITE: 8, SYSTEM_EXECUTE: 9, EVERYBODY: 10
    }
})

EMSCRIPTEN_BINDINGS(access_flags) {
    djinni_init_testsuite_access_flags();
}

}  // namespace djinni_generated
