// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#include "NativeSampleInterface.hpp"  // my header

namespace djinni_generated {

em::val NativeSampleInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}


namespace {
    EM_JS(void, djinni_init_testsuite_sample_interface, (), {
        'testsuite'.split('.').reduce(function(path, part) {
            if (!path.hasOwnProperty(part)) { path[part] = {}}; 
            return path[part]
        }, Module);
        Module.testsuite.SampleInterface = Module.testsuite_SampleInterface
    })
}
void NativeSampleInterface::staticInitialize() {
    static std::once_flag initOnce;
    std::call_once(initOnce, djinni_init_testsuite_sample_interface);
}
EMSCRIPTEN_BINDINGS(testsuite_sample_interface) {
    em::class_<::testsuite::SampleInterface>("testsuite_SampleInterface")
        .smart_ptr<std::shared_ptr<::testsuite::SampleInterface>>("testsuite_SampleInterface")
        .function("nativeDestroy", &NativeSampleInterface::nativeDestroy)
        ;
    NativeSampleInterface::staticInitialize();
}

}  // namespace djinni_generated
