// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#include "NativeConflict.hpp"  // my header

namespace djinni_generated {

em::val NativeConflict::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}


namespace {
    EM_JS(void, djinni_init_testsuite_Conflict, (), {
        'testsuite'.split('.').reduce(function(path, part) {
            if (!path.hasOwnProperty(part)) { path[part] = {}}; 
            return path[part]
        }, Module);
        Module.testsuite.Conflict = Module.testsuite_Conflict
    })
}
void NativeConflict::staticInitialize() {
    static std::once_flag initOnce;
    std::call_once(initOnce, djinni_init_testsuite_Conflict);
}
EMSCRIPTEN_BINDINGS(testsuite_Conflict) {
    em::class_<::testsuite::Conflict>("testsuite_Conflict")
        .smart_ptr<std::shared_ptr<::testsuite::Conflict>>("testsuite_Conflict")
        .function("nativeDestroy", &NativeConflict::nativeDestroy)
        ;
    NativeConflict::staticInitialize();
}

}  // namespace djinni_generated
