// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort;

internal abstract class TextboxListener {
    abstract fun update(items: ItemList)
}
