// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni


export interface /*record*/ WcharTestRec {
    s: string;
}

export interface WcharTestHelpers {
}
export interface WcharTestHelpers_statics {
    getRecord(): WcharTestRec;
    getString(): string;
    checkString(str: string): boolean;
    checkRecord(rec: WcharTestRec): boolean;
}

export interface Module_statics {
    WcharTestHelpers: WcharTestHelpers_statics;
}
