// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

#include "NativeNestedLazyInterface.hpp"  // my header
#include "Lazy_swift.hpp"
#include "NativeSimpleObject.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeNestedLazyInterface::fromCpp(const ::testsuite::NestedLazyInterface& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::LazyAdaptor<::djinni_generated::NativeSimpleObject>::fromCpp(c.obj));
    return {ret};
}
::testsuite::NestedLazyInterface NativeNestedLazyInterface::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::NestedLazyInterface(::djinni::swift::LazyAdaptor<::djinni_generated::NativeSimpleObject>::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
