// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#include "NativeExternRecordWithDerivings.hpp"  // my header
#include "NativeColor.hpp"
#include "NativeRecordWithDerivings.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeExternRecordWithDerivings::fromCpp(const ::ExternRecordWithDerivings& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni_generated::NativeRecordWithDerivings::fromCpp(c.member));
    ret->addValue(::djinni_generated::NativeColor::fromCpp(c.e));
    return {ret};
}
::ExternRecordWithDerivings NativeExternRecordWithDerivings::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::ExternRecordWithDerivings(::djinni_generated::NativeRecordWithDerivings::toCpp(p->getValue(0)), ::djinni_generated::NativeColor::toCpp(p->getValue(1)));
}

} // namespace djinni_generated
