// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

#pragma once

#include "_varname_interface_.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

using NativeVarnameInterface = djinni::swift::Interface<::testsuite::VarnameInterface>;

djinni::swift::AnyValue VarnameInterface_Rmethod(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue VarnameInterface_Imethod(const djinni::swift::ParameterList* params);

} // namespace djinni_generated
