// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#pragma once

#include "djinni_support.hpp"
#include "extern_interface_2.hpp"

namespace djinni_generated {

using NativeExternInterface2 = djinni::swift::Interface<::ExternInterface2>;

} // namespace djinni_generated
