// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from static_method_language.djinni

#include "NativeTestStaticMethodLanguage.hpp"  // my header

namespace djinni_generated {


} // namespace djinni_generated
