// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

#pragma once

#include "djinni_support.hpp"
#include "test_outcome.hpp"

namespace djinni_generated {

using NativeTestOutcome = djinni::swift::Interface<::testsuite::TestOutcome>;

djinni::swift::AnyValue TestOutcome_getSuccessOutcome(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestOutcome_getErrorOutcome(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestOutcome_putSuccessOutcome(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestOutcome_putErrorOutcome(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestOutcome_getNestedSuccessOutcome(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestOutcome_getNestedErrorOutcome(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestOutcome_putNestedSuccessOutcome(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestOutcome_putNestedErrorOutcome(const djinni::swift::ParameterList* params);

} // namespace djinni_generated
