// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

#pragma once

#include "djinni_support.hpp"
#include "nested_collection.hpp"

namespace djinni_generated {

struct NativeNestedCollection {
    using CppType = ::testsuite::NestedCollection;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
