// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#pragma once

#include "djinni_support.hpp"
#include "test_provider.hpp"

namespace djinni_generated {

using NativeTestProvider = djinni::swift::Interface<::testsuite::TestProvider>;

djinni::swift::AnyValue TestProvider_getProviderString(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_getProviderInt(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_callProviderString(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_callProviderInt(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_getNestedProvider(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_callNestedProvider(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_getProviderObject(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_callProviderObject(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_callProviderObjectGetName(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_getNestedProviderInterface(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_callNestedProviderInterface(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue TestProvider_createSimpleObject(const djinni::swift::ParameterList* params);

} // namespace djinni_generated
