// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

#include "NativeRecordWithDerivings.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue NativeRecordWithDerivings::fromCpp(const ::testsuite::RecordWithDerivings& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::I8::fromCpp(c.eight));
    ret->addValue(::djinni::swift::I16::fromCpp(c.sixteen));
    ret->addValue(::djinni::swift::I32::fromCpp(c.thirtytwo));
    ret->addValue(::djinni::swift::I64::fromCpp(c.sixtyfour));
    ret->addValue(::djinni::swift::F32::fromCpp(c.fthirtytwo));
    ret->addValue(::djinni::swift::F64::fromCpp(c.fsixtyfour));
    ret->addValue(::djinni::swift::Date::fromCpp(c.d));
    ret->addValue(::djinni::swift::String::fromCpp(c.s));
    return {ret};
}
::testsuite::RecordWithDerivings NativeRecordWithDerivings::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::RecordWithDerivings(::djinni::swift::I8::toCpp(p->getValue(0)), ::djinni::swift::I16::toCpp(p->getValue(1)), ::djinni::swift::I32::toCpp(p->getValue(2)), ::djinni::swift::I64::toCpp(p->getValue(3)), ::djinni::swift::F32::toCpp(p->getValue(4)), ::djinni::swift::F64::toCpp(p->getValue(5)), ::djinni::swift::Date::toCpp(p->getValue(6)), ::djinni::swift::String::toCpp(p->getValue(7)));
}

} // namespace djinni_generated
