// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "djinni_support.hpp"
#include "second_listener.hpp"

namespace djinni_generated {

using NativeSecondListener = djinni::swift::Interface<::testsuite::SecondListener>;

} // namespace djinni_generated
