// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "djinni_support.hpp"
#include "return_one.hpp"

namespace djinni_generated {

using NativeReturnOne = djinni::swift::Interface<::testsuite::ReturnOne>;

djinni::swift::AnyValue ReturnOne_getInstance(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue ReturnOne_returnOne(const djinni::swift::ParameterList* params);

} // namespace djinni_generated
