// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

#include "NativeFirstListener.hpp"  // my header

namespace djinni_generated {


} // namespace djinni_generated
