// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

#pragma once

#include "djinni_support.hpp"
#include "support_copying.hpp"

namespace djinni_generated {

struct NativeSupportCopying {
    using CppType = ::testsuite::SupportCopying;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
