// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

#pragma once

#include "constant_record.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

struct NativeConstantRecord {
    using CppType = ::testsuite::ConstantRecord;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
