// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#include "NativeTestOptionalExternInterfaceRecord.hpp"  // my header
#include "NativeSampleInterface.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeTestOptionalExternInterfaceRecord::fromCpp(const ::TestOptionalExternInterfaceRecord& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::Optional<std::experimental::optional, ::djinni_generated::NativeSampleInterface>::fromCpp(c.sample_interface));
    return {ret};
}
::TestOptionalExternInterfaceRecord NativeTestOptionalExternInterfaceRecord::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::TestOptionalExternInterfaceRecord(::djinni::swift::Optional<std::experimental::optional, ::djinni_generated::NativeSampleInterface>::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
