// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#include "NativeNestedProvider.hpp"  // my header
#include "Provider_swift.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeNestedProvider::fromCpp(const ::testsuite::NestedProvider& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::ProviderAdaptor<::djinni::swift::I32>::fromCpp(c.s));
    return {ret};
}
::testsuite::NestedProvider NativeNestedProvider::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::NestedProvider(::djinni::swift::ProviderAdaptor<::djinni::swift::I32>::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
