// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#include "NativeDateRecord.hpp"  // my header
#include "djinni_support.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeDateRecord::fromCpp(const ::testsuite::DateRecord& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::Date::fromCpp(c.created_at));
    return {ret};
}
::testsuite::DateRecord NativeDateRecord::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::DateRecord(::djinni::swift::Date::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
