// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#pragma once

#include "djinni_support.hpp"
#include "map_list_record.hpp"

namespace djinni_generated {

struct NativeMapListRecord {
    using CppType = ::testsuite::MapListRecord;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
