// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#pragma once

#include "djinni_support.hpp"
#include "map_date_record.hpp"

namespace djinni_generated {

struct NativeMapDateRecord {
    using CppType = ::testsuite::MapDateRecord;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
