// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

#pragma once

#include "djinni_support.hpp"
#include "record_with_derivings.hpp"

namespace djinni_generated {

struct NativeRecordWithDerivings {
    using CppType = ::testsuite::RecordWithDerivings;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
