// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#pragma once

#include "constant_with_enum.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

struct NativeConstantWithEnum {
    using CppType = ::testsuite::ConstantWithEnum;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
