// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#pragma once

#include "constant_enum.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

using NativeConstantEnum = djinni::swift::Enum<::testsuite::constant_enum>;

} // namespace djinni_generated
