// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

#include "NativeRecordWithDurationAndDerivings.hpp"  // my header
#include "Duration-swift.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeRecordWithDurationAndDerivings::fromCpp(const ::testsuite::RecordWithDurationAndDerivings& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::Duration<::djinni::swift::F64, ::djinni::swift::Duration_ns>::fromCpp(c.dt));
    return {ret};
}
::testsuite::RecordWithDurationAndDerivings NativeRecordWithDurationAndDerivings::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::RecordWithDurationAndDerivings(::djinni::swift::Duration<::djinni::swift::F64, ::djinni::swift::Duration_ns>::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
