// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#pragma once

#include "conflict_user.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

using NativeConflictUser = djinni::swift::Interface<::testsuite::ConflictUser>;

djinni::swift::AnyValue ConflictUser_Conflict(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue ConflictUser_conflictArg(const djinni::swift::ParameterList* params);

} // namespace djinni_generated
