// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#include "NativeRecordWithFlags.hpp"  // my header
#include "NativeAccessFlags.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeRecordWithFlags::fromCpp(const ::testsuite::RecordWithFlags& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni_generated::NativeAccessFlags::fromCpp(c.access));
    return {ret};
}
::testsuite::RecordWithFlags NativeRecordWithFlags::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::RecordWithFlags(::djinni_generated::NativeAccessFlags::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
