// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "NativeSampleInterface.hpp"  // my header

namespace djinni_generated {


} // namespace djinni_generated
