// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

#include "NativeWcharTestRec.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue NativeWcharTestRec::fromCpp(const ::testsuite::WcharTestRec& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::WString::fromCpp(c.s));
    return {ret};
}
::testsuite::WcharTestRec NativeWcharTestRec::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::WcharTestRec(::djinni::swift::WString::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
