// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

#pragma once

#include "djinni_support.hpp"
#include "first_listener.hpp"

namespace djinni_generated {

using NativeFirstListener = djinni::swift::Interface<::testsuite::FirstListener>;

} // namespace djinni_generated
