// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

#include "NativeVarnameInterface.hpp"  // my header
#include "NativeVarnameRecord.hpp"

namespace djinni_generated {

djinni::swift::AnyValue VarnameInterface_Rmethod(const djinni::swift::ParameterList* params) try {
    auto inst = NativeVarnameInterface::toCpp(params->getValue(0));
    auto __r_arg_ = ::djinni_generated::NativeVarnameRecord::toCpp(params->getValue(1));
    auto ret = inst->_rmethod_(std::move(__r_arg_));
    return ::djinni_generated::NativeVarnameRecord::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}
djinni::swift::AnyValue VarnameInterface_Imethod(const djinni::swift::ParameterList* params) try {
    auto inst = NativeVarnameInterface::toCpp(params->getValue(0));
    auto __i_arg_ = ::djinni_generated::NativeVarnameInterface::toCpp(params->getValue(1));
    auto ret = inst->_imethod_(std::move(__i_arg_));
    return ::djinni_generated::NativeVarnameInterface::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}

} // namespace djinni_generated
