// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

#include "NativeVarnameRecord.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue NativeVarnameRecord::fromCpp(const ::testsuite::VarnameRecord& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::I8::fromCpp(c._field_));
    return {ret};
}
::testsuite::VarnameRecord NativeVarnameRecord::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::VarnameRecord(::djinni::swift::I8::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
