// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#include "NativeMapDateRecord.hpp"  // my header
#include "djinni_support.hpp"

namespace djinni_generated {

djinni::swift::AnyValue NativeMapDateRecord::fromCpp(const ::testsuite::MapDateRecord& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::Map<::djinni::swift::String, ::djinni::swift::Date>::fromCpp(c.dates_by_id));
    return {ret};
}
::testsuite::MapDateRecord NativeMapDateRecord::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::MapDateRecord(::djinni::swift::Map<::djinni::swift::String, ::djinni::swift::Date>::toCpp(p->getValue(0)));
}

} // namespace djinni_generated
