// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

@interface TXSItemList : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithItems:(nonnull NSArray<NSString *> *)items NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)itemListWithItems:(nonnull NSArray<NSString *> *)items;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * items;

@end
