// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, TXSSortOrder)
{
    TXSSortOrderAscending = 0,
    TXSSortOrderDescending = 1,
    TXSSortOrderRandom = 2,
};
