// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_perf_benchmark.djinni

#include "NativeEnumSixValue.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init_snapchat_djinni_benchmark_EnumSixValue, (), {
        Module.benchmark_EnumSixValue =  {
            FIRST : 0,
            SECOND : 1,
            THIRD : 2,
            FOURTH : 3,
            FIFTH : 4,
            SIXTH : 5,
        }
        ;
    })
}

void NativeEnumSixValue::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, djinni_init_snapchat_djinni_benchmark_EnumSixValue);
}

EMSCRIPTEN_BINDINGS(snapchat_djinni_benchmark_EnumSixValue) {
    NativeEnumSixValue::staticInitializeConstants();
}

}  // namespace djinni_generated
