// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_perf_benchmark.djinni

#include "NativeObjectPlatform.hpp"  // my header

namespace djinni_generated {


void NativeObjectPlatform::JsProxy::onDone() {
    return _jsRef().call<void>("onDone");
}

EMSCRIPTEN_BINDINGS(ObjectPlatform) {
    em::class_<::snapchat::djinni::benchmark::ObjectPlatform>("ObjectPlatform")
        .smart_ptr<std::shared_ptr<::snapchat::djinni::benchmark::ObjectPlatform>>("ObjectPlatform")
        .function("nativeDestroy", &NativeObjectPlatform::nativeDestroy)
        ;
}

}  // namespace djinni_generated
