// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from djinni_perf_benchmark.djinni

#include "NativeRecordSixInt.hpp"  // my header

namespace djinni_generated {

auto NativeRecordSixInt::toCpp(const JsType& j) -> CppType {
    return {::djinni::I64::Boxed::toCpp(j["i1"]),
            ::djinni::I64::Boxed::toCpp(j["i2"]),
            ::djinni::I64::Boxed::toCpp(j["i3"]),
            ::djinni::I64::Boxed::toCpp(j["i4"]),
            ::djinni::I64::Boxed::toCpp(j["i5"]),
            ::djinni::I64::Boxed::toCpp(j["i6"])};
}
auto NativeRecordSixInt::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("i1", ::djinni::I64::Boxed::fromCpp(c.i1));
    js.set("i2", ::djinni::I64::Boxed::fromCpp(c.i2));
    js.set("i3", ::djinni::I64::Boxed::fromCpp(c.i3));
    js.set("i4", ::djinni::I64::Boxed::fromCpp(c.i4));
    js.set("i5", ::djinni::I64::Boxed::fromCpp(c.i5));
    js.set("i6", ::djinni::I64::Boxed::fromCpp(c.i6));
    return js;
}

}  // namespace djinni_generated
