workspace(name = "djinni_external_test")

local_repository(
    name = "djinni",
    path = "../",
)

load("@djinni//bzl:deps.bzl", "djinni_deps")
djinni_deps()
load("@djinni//bzl:scala_config.bzl", "djinni_scala_config")
djinni_scala_config()
load("@djinni//bzl:setup_deps.bzl", "djinni_setup_deps")
djinni_setup_deps()
