// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#import <Foundation/Foundation.h>

typedef NS_OPTIONS(NSInteger, DBAccessFlagsViewModel)
{
    DBAccessFlagsViewModelNobody = 0,
    DBAccessFlagsViewModelOwnerRead = 1 << 0,
    DBAccessFlagsViewModelOwnerWrite = 1 << 1,
    DBAccessFlagsViewModelOwnerExecute = 1 << 2,
    DBAccessFlagsViewModelGroupRead = 1 << 3,
    DBAccessFlagsViewModelGroupWrite = 1 << 4,
    DBAccessFlagsViewModelGroupExecute = 1 << 5,
    DBAccessFlagsViewModelSystemRead = 1 << 6,
    DBAccessFlagsViewModelSystemWrite = 1 << 7,
    DBAccessFlagsViewModelSystemExecute = 1 << 8,
    DBAccessFlagsViewModelEverybody = 0 | (1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) | (1 << 4) | (1 << 5) | (1 << 6) | (1 << 7) | (1 << 8),
};
