// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

#import "DBAssortedPrimitivesViewModel.h"
#include "assorted_primitives.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBAssortedPrimitivesViewModel;

namespace djinni_generated {

struct AssortedPrimitives
{
    using CppType = ::testsuite::AssortedPrimitives;
    using ObjcType = DBAssortedPrimitivesViewModel*;

    using Boxed = AssortedPrimitives;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
