// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

#import <Foundation/Foundation.h>

@interface DBAssortedPrimitives : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithB:(BOOL)b
                            eight:(int8_t)eight
                          sixteen:(int16_t)sixteen
                        thirtytwo:(int32_t)thirtytwo
                        sixtyfour:(int64_t)sixtyfour
                       fthirtytwo:(float)fthirtytwo
                       fsixtyfour:(double)fsixtyfour
                               oB:(nullable NSNumber *)oB
                           oEight:(nullable NSNumber *)oEight
                         oSixteen:(nullable NSNumber *)oSixteen
                       oThirtytwo:(nullable NSNumber *)oThirtytwo
                       oSixtyfour:(nullable NSNumber *)oSixtyfour
                      oFthirtytwo:(nullable NSNumber *)oFthirtytwo
                      oFsixtyfour:(nullable NSNumber *)oFsixtyfour NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)assortedPrimitivesWithB:(BOOL)b
                                          eight:(int8_t)eight
                                        sixteen:(int16_t)sixteen
                                      thirtytwo:(int32_t)thirtytwo
                                      sixtyfour:(int64_t)sixtyfour
                                     fthirtytwo:(float)fthirtytwo
                                     fsixtyfour:(double)fsixtyfour
                                             oB:(nullable NSNumber *)oB
                                         oEight:(nullable NSNumber *)oEight
                                       oSixteen:(nullable NSNumber *)oSixteen
                                     oThirtytwo:(nullable NSNumber *)oThirtytwo
                                     oSixtyfour:(nullable NSNumber *)oSixtyfour
                                    oFthirtytwo:(nullable NSNumber *)oFthirtytwo
                                    oFsixtyfour:(nullable NSNumber *)oFsixtyfour;
- (nonnull instancetype)initWithB:(BOOL)b
                            eight:(int8_t)eight
                          sixteen:(int16_t)sixteen
                        thirtytwo:(int32_t)thirtytwo
                        sixtyfour:(int64_t)sixtyfour
                       fthirtytwo:(float)fthirtytwo
                       fsixtyfour:(double)fsixtyfour;
+ (nonnull instancetype)assortedPrimitivesWithB:(BOOL)b
                                          eight:(int8_t)eight
                                        sixteen:(int16_t)sixteen
                                      thirtytwo:(int32_t)thirtytwo
                                      sixtyfour:(int64_t)sixtyfour
                                     fthirtytwo:(float)fthirtytwo
                                     fsixtyfour:(double)fsixtyfour;

@property (nonatomic, readonly) BOOL b;

@property (nonatomic, readonly) int8_t eight;

@property (nonatomic, readonly) int16_t sixteen;

@property (nonatomic, readonly) int32_t thirtytwo;

@property (nonatomic, readonly) int64_t sixtyfour;

@property (nonatomic, readonly) float fthirtytwo;

@property (nonatomic, readonly) double fsixtyfour;

@property (nonatomic, nullable) NSNumber * oB;

@property (nonatomic, nullable) NSNumber * oEight;

@property (nonatomic, nullable) NSNumber * oSixteen;

@property (nonatomic, nullable) NSNumber * oThirtytwo;

@property (nonatomic, nullable) NSNumber * oSixtyfour;

@property (nonatomic, nullable) NSNumber * oFthirtytwo;

@property (nonatomic, nullable) NSNumber * oFsixtyfour;

@end
