// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#import <Foundation/Foundation.h>

/** Base record with a required value */
@interface DBBaseRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithVal:(int32_t)val NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)baseRecordWithVal:(int32_t)val;

@property (nonatomic) int32_t val;

@end
