// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

#import "DBConstantRecordViewModel.h"
#import <Foundation/Foundation.h>

/** Record containing constants */
@interface DBConstantsViewModel : NSObject
- (nonnull instancetype)init NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)constants;

+ (NSNumber * __nullable)optBoolConstant;
+ (NSNumber * __nullable)optI8Constant;
/** opt_i16_constant has documentation. */
+ (NSNumber * __nullable)optI16Constant;
+ (NSNumber * __nullable)optI32Constant;
+ (NSNumber * __nullable)optI64Constant;
/**
 * opt_f32_constant has long documentation.
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
+ (NSNumber * __nullable)optF32Constant;
+ (NSNumber * __nullable)optF64Constant;
+ (DBConstantRecordViewModel * __nonnull)objectConstant;
@end

/** bool_constant has documentation. */
extern BOOL const DBConstantsViewModelBoolConstant;
extern int8_t const DBConstantsViewModelI8Constant;
extern int16_t const DBConstantsViewModelI16Constant;
extern int32_t const DBConstantsViewModelI32Constant;
extern int64_t const DBConstantsViewModelI64Constant;
extern float const DBConstantsViewModelF32Constant;
/**
 * f64_constant has long documentation.
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
extern double const DBConstantsViewModelF64Constant;
extern NSString * __nonnull const DBConstantsViewModelStringConstant;
extern NSString * __nullable const DBConstantsViewModelOptStringConstant;
/**
 * No support for null optional constants
 * No support for optional constant records
 * No support for constant binary, list, set, map
 */
extern BOOL const DBConstantsViewModelDummy;
