// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

#import "DBConstantsInterfaceViewModel.h"


BOOL const DBConstantsInterfaceViewModelBoolConstant = YES;

int8_t const DBConstantsInterfaceViewModelI8Constant = 1;

int16_t const DBConstantsInterfaceViewModelI16Constant = 2;

int32_t const DBConstantsInterfaceViewModelI32Constant = 3;

int64_t const DBConstantsInterfaceViewModelI64Constant = 4;

float const DBConstantsInterfaceViewModelF32Constant = 5.0f;

double const DBConstantsInterfaceViewModelF64Constant = 5.0;

NSString * __nonnull const DBConstantsInterfaceViewModelStringConstant = @"string-constant";

NSString * __nullable const DBConstantsInterfaceViewModelOptStringConstant = @"string-constant";

NSString * __nonnull const DBConstantsInterfaceViewModelUPPERCASECONSTANT = @"upper-case-constant";
