// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#import "DBConstantWithEnumViewModel+Private.h"
#import "DBConstantEnumViewModel+Private.h"
#include <cassert>

namespace djinni_generated {

auto ConstantWithEnum::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    (void)obj; // Suppress warnings in relase builds for empty records
    return {};
}

auto ConstantWithEnum::fromCpp(const CppType& cpp) -> ObjcType
{
    (void)cpp; // Suppress warnings in relase builds for empty records
    return [[DBConstantWithEnumViewModel alloc] init];
}

} // namespace djinni_generated
