// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#import <Foundation/Foundation.h>

/** Record for use in constants */
@interface DBConstantRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithSomeInteger:(int32_t)someInteger
                                 someString:(nonnull NSString *)someString NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)constantRecordWithSomeInteger:(int32_t)someInteger
                                           someString:(nonnull NSString *)someString;

@property (nonatomic, readonly) int32_t someInteger;

@property (nonatomic, readonly, nonnull) NSString * someString;

@end
