// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

#import "DBConstantsViewModel.h"
#include "constants.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBConstantsViewModel;

namespace djinni_generated {

struct Constants
{
    using CppType = ::testsuite::Constants;
    using ObjcType = DBConstantsViewModel*;

    using Boxed = Constants;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
