// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#import "DBDateRecordViewModel.h"


@implementation DBDateRecordViewModel

- (nonnull instancetype)initWithCreatedAt:(nonnull NSDate *)createdAt
{
    if (self = [super init]) {
        _createdAt = createdAt;
    }
    return self;
}

+ (nonnull instancetype)dateRecordWithCreatedAt:(nonnull NSDate *)createdAt
{
    return [[self alloc] initWithCreatedAt:createdAt];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBDateRecordViewModel class]]) {
        return NO;
    }
    DBDateRecordViewModel *typedOther = (DBDateRecordViewModel *)other;
    return [self.createdAt isEqual:typedOther.createdAt];
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            ((NSUInteger)self.createdAt.timeIntervalSinceReferenceDate);
}

- (NSComparisonResult)compare:(DBDateRecordViewModel *)other
{
    NSComparisonResult tempResult;
    tempResult = [self.createdAt compare:other.createdAt];
    if (tempResult != NSOrderedSame) {
        return tempResult;
    }
    return NSOrderedSame;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p createdAt:%@>", self.class, (void *)self, self.createdAt];
}

#endif
@end
