// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#import <Foundation/Foundation.h>

typedef NS_OPTIONS(NSInteger, DBEmptyFlagsViewModel)
{
    DBEmptyFlagsViewModelNone = 0,
    DBEmptyFlagsViewModelAll = 0,
};
