// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

#import "DBColorViewModel.h"
#import <Foundation/Foundation.h>


@protocol DBEnumUsageInterfaceViewModel <NSObject>

- (DBColorViewModel)e:(DBColorViewModel)e;

- (nullable NSNumber *)o:(nullable NSNumber *)o;

- (nonnull NSArray<NSNumber *> *)l:(nonnull NSArray<NSNumber *> *)l;

- (nonnull NSSet<NSNumber *> *)s:(nonnull NSSet<NSNumber *> *)s;

- (nonnull NSDictionary<NSNumber *, NSNumber *> *)m:(nonnull NSDictionary<NSNumber *, NSNumber *> *)m;

@end
