// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

#import "DBColorViewModel.h"
#import <Foundation/Foundation.h>

@interface DBEnumUsageRecordViewModel : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithE:(DBColorViewModel)e
                                o:(nullable NSNumber *)o
                                l:(nonnull NSArray<NSNumber *> *)l
                                s:(nonnull NSSet<NSNumber *> *)s
                                m:(nonnull NSDictionary<NSNumber *, NSNumber *> *)m NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)enumUsageRecordWithE:(DBColorViewModel)e
                                           o:(nullable NSNumber *)o
                                           l:(nonnull NSArray<NSNumber *> *)l
                                           s:(nonnull NSSet<NSNumber *> *)s
                                           m:(nonnull NSDictionary<NSNumber *, NSNumber *> *)m;

@property (nonatomic, readonly) DBColorViewModel e;

@property (nonatomic, readonly, nullable) NSNumber * o;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * l;

@property (nonatomic, readonly, nonnull) NSSet<NSNumber *> * s;

@property (nonatomic, readonly, nonnull) NSDictionary<NSNumber *, NSNumber *> * m;

@end
