// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#import "DBExternRecordWithDerivingsViewModel.h"


@implementation DBExternRecordWithDerivingsViewModel

- (nonnull instancetype)initWithMember:(nonnull DBRecordWithDerivingsViewModel *)member
                                     e:(DBColorViewModel)e
{
    if (self = [super init]) {
        _member = member;
        _e = e;
    }
    return self;
}

+ (nonnull instancetype)externRecordWithDerivingsWithMember:(nonnull DBRecordWithDerivingsViewModel *)member
                                                          e:(DBColorViewModel)e
{
    return [[self alloc] initWithMember:member
                                      e:e];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBExternRecordWithDerivingsViewModel class]]) {
        return NO;
    }
    DBExternRecordWithDerivingsViewModel *typedOther = (DBExternRecordWithDerivingsViewModel *)other;
    return [self.member isEqual:typedOther.member] &&
            self.e == typedOther.e;
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            (self.member.hash) ^
            (NSUInteger)self.e;
}

- (NSComparisonResult)compare:(DBExternRecordWithDerivingsViewModel *)other
{
    NSComparisonResult tempResult;
    tempResult = [self.member compare:other.member];
    if (tempResult != NSOrderedSame) {
        return tempResult;
    }
    if (self.e < other.e) {
        tempResult = NSOrderedAscending;
    } else if (self.e > other.e) {
        tempResult = NSOrderedDescending;
    } else {
        tempResult = NSOrderedSame;
    }
    if (tempResult != NSOrderedSame) {
        return tempResult;
    }
    return NSOrderedSame;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p member:%@ e:%@>", self.class, (void *)self, self.member, @(self.e)];
}

#endif
@end
