// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#import "DBColorViewModel.h"
#import "DBRecordWithDerivingsViewModel.h"
#import <Foundation/Foundation.h>

/** This file tests YAML dumped by Djinni can be parsed back in */
@interface DBExternRecordWithDerivingsViewModel : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithMember:(nonnull DBRecordWithDerivingsViewModel *)member
                                     e:(DBColorViewModel)e NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)externRecordWithDerivingsWithMember:(nonnull DBRecordWithDerivingsViewModel *)member
                                                          e:(DBColorViewModel)e;

@property (nonatomic, readonly, nonnull) DBRecordWithDerivingsViewModel * member;

@property (nonatomic, readonly) DBColorViewModel e;

- (NSComparisonResult)compare:(nonnull DBExternRecordWithDerivingsViewModel *)other;

@end
