// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#import "DBColor.h"
#import "DBRecordWithDerivings.h"
#import <Foundation/Foundation.h>

/** This file tests YAML dumped by Djinni can be parsed back in */
@interface DBExternRecordWithDerivings : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithMember:(nonnull DBRecordWithDerivings *)member
                                     e:(DBColor)e NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)externRecordWithDerivingsWithMember:(nonnull DBRecordWithDerivings *)member
                                                          e:(DBColor)e;

@property (nonatomic, readonly, nonnull) DBRecordWithDerivings * member;

@property (nonatomic, readonly) DBColor e;

- (NSComparisonResult)compare:(nonnull DBExternRecordWithDerivings *)other;

@end
