// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from function_prologue.djinni

#import <Foundation/Foundation.h>


@interface DBFunctionPrologueHelper : NSObject

+ (nonnull NSString *)foo;

@end
