// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

#include "js_exception.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBJsException;

namespace djinni_generated {

class JsException
{
public:
    using CppType = std::shared_ptr<::testsuite::JsException>;
    using CppOptType = std::shared_ptr<::testsuite::JsException>;
    using ObjcType = DBJsException*;

    using Boxed = JsException;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

