// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#import <Foundation/Foundation.h>

@interface DBMapRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithMap:(nonnull NSDictionary<NSString *, NSNumber *> *)map
                               imap:(nonnull NSDictionary<NSNumber *, NSNumber *> *)imap NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)mapRecordWithMap:(nonnull NSDictionary<NSString *, NSNumber *> *)map
                                    imap:(nonnull NSDictionary<NSNumber *, NSNumber *> *)imap;

@property (nonatomic, copy, nonnull) NSDictionary<NSString *, NSNumber *> * map;

@property (nonatomic, copy, nonnull) NSDictionary<NSNumber *, NSNumber *> * imap;

@end
