// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from outcome.djinni

#import "DBNestedOutcome.h"


@implementation DBNestedOutcome

- (nonnull instancetype)initWithO:(nonnull DJOutcome<NSNumber *, NSString *> *)o
{
    if (self = [super init]) {
        _o = [o copy];
    }
    return self;
}

+ (nonnull instancetype)nestedOutcomeWithO:(nonnull DJOutcome<NSNumber *, NSString *> *)o
{
    return [[self alloc] initWithO:o];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBNestedOutcome class]]) {
        return NO;
    }
    DBNestedOutcome *typedOther = (DBNestedOutcome *)other;
    return [self.o isEqualToOutcome:typedOther.o];
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            self.o.hash;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p o:%@>", self.class, (void *)self, self.o];
}

#endif
@end
