// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from outcome.djinni

#import "DJOutcome.h"
#import <Foundation/Foundation.h>

@interface DBNestedOutcome : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithO:(nonnull DJOutcome<NSNumber *, NSString *> *)o NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)nestedOutcomeWithO:(nonnull DJOutcome<NSNumber *, NSString *> *)o;

@property (nonatomic, readonly, nonnull) DJOutcome<NSNumber *, NSString *> * o;

@end
