// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

#import "DJSupplier.h"
#import <Foundation/Foundation.h>

@interface DBNestedSupplier : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithS:(nonnull DJSupplier<NSNumber *> *)s NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)nestedSupplierWithS:(nonnull DJSupplier<NSNumber *> *)s;

@property (nonatomic, nonnull) DJSupplier<NSNumber *> * s;

@end
