// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from supplier.djinni

#ifdef __cplusplus
#import "DBNestedSupplierInterface.h"
#include "nested_supplier_interface.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBNestedSupplierInterface;

namespace djinni_generated {

struct NestedSupplierInterface
{
    using CppType = ::testsuite::NestedSupplierInterface;
    using ObjcType = DBNestedSupplierInterface*;

    using Boxed = NestedSupplierInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
#endif // __cplusplus
