// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

#ifdef __cplusplus
#import "DBNestedLazyInterface+Private.h"
#import "DBSimpleObject+Private.h"
#import "Lazy_objc.hpp"
#include <cassert>

namespace djinni_generated {

auto NestedLazyInterface::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::LazyAdaptor<::djinni_generated::SimpleObject>::toCpp(obj.obj)};
}

auto NestedLazyInterface::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBNestedLazyInterface alloc] initWithObj:(::djinni::LazyAdaptor<::djinni_generated::SimpleObject>::fromCpp(cpp.obj))];
}

} // namespace djinni_generated
#endif // __cplusplus
