// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from no_constructor.djinni

#import "DBNoConstructorRecord.h"


NSString * __nonnull const DBNoConstructorRecordRECORDCONSTVALUENative = @"test";

int32_t const DBNoConstructorRecordXXXWeirdCaseNative = 1;

@implementation DBNoConstructorRecord

- (nonnull instancetype)initWithFirstValue:(int32_t)FirstValue
                               secondValue:(nonnull NSString *)secondValue
{
    if (self = [super init]) {
        _FirstValue = FirstValue;
        _secondValue = [secondValue copy];
    }
    return self;
}

+ (nonnull instancetype)noConstructorRecordWithFirstValue:(int32_t)FirstValue
                                              secondValue:(nonnull NSString *)secondValue
{
    return [[self alloc] initWithFirstValue:FirstValue
                                secondValue:secondValue];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p FirstValue:%@ secondValue:%@>", self.class, (void *)self, @(self.FirstValue), self.secondValue];
}

#endif
@end
