// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

#include "objc_only_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DBObjcOnlyListener;

namespace djinni_generated {

class ObjcOnlyListener
{
public:
    using CppType = std::shared_ptr<::testsuite::ObjcOnlyListener>;
    using CppOptType = std::shared_ptr<::testsuite::ObjcOnlyListener>;
    using ObjcType = id<DBObjcOnlyListener>;

    using Boxed = ObjcOnlyListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) {
        if (!cpp) {
            throw std::invalid_argument("ObjcOnlyListener::fromCpp requires a non-null C++ object");
        }
        return fromCppOpt(cpp);
    }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

