// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#import "DBBaseRecord.h"
#import "DBMixedRecord.h"
#import "DBOptionalRecord.h"
#import <Foundation/Foundation.h>
@class DBOptionalInterface;


@interface DBOptionalTestHelpers : NSObject

+ (nonnull DBBaseRecord *)getBaseRecord;

+ (nullable DBOptionalInterface *)optionalInterface;

+ (nonnull DBMixedRecord *)getMixedRecord;

+ (nonnull DBOptionalRecord *)getOptionalRecord;

/** Checks that translation occurs properly */
+ (nonnull DBMixedRecord *)mixedRecordId:(nonnull DBMixedRecord *)i;

@end
