// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from optionals.djinni

#ifdef __cplusplus
#include "optional_test_helpers.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBOptionalTestHelpers;

namespace djinni_generated {

class OptionalTestHelpers
{
public:
    using CppType = std::shared_ptr<::testsuite::OptionalTestHelpers>;
    using CppOptType = std::shared_ptr<::testsuite::OptionalTestHelpers>;
    using ObjcType = DBOptionalTestHelpers*;

    using Boxed = OptionalTestHelpers;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif // __cplusplus
