// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

#import "DBPrimitiveListViewModel.h"
#include "primitive_list.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBPrimitiveListViewModel;

namespace djinni_generated {

struct PrimitiveList
{
    using CppType = ::testsuite::PrimitiveList;
    using ObjcType = DBPrimitiveListViewModel*;

    using Boxed = PrimitiveList;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
