// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

#import <Foundation/Foundation.h>

@interface DBPrimitiveList : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithList:(nonnull NSArray<NSNumber *> *)list NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)primitiveListWithList:(nonnull NSArray<NSNumber *> *)list;

@property (nonatomic, copy, nonnull) NSArray<NSNumber *> * list;

@end
