// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#import "proto/objc/test.pbobjc.h"
#import <Foundation/Foundation.h>

@interface DBRecordWithProtobufEnum : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithPhoneType:(DJTestPerson_PhoneType)phoneType
                                 priority:(DJTestPriority)priority NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)RecordWithProtobufEnumWithPhoneType:(DJTestPerson_PhoneType)phoneType
                                                   priority:(DJTestPriority)priority;

@property (nonatomic, readonly) DJTestPerson_PhoneType phoneType;

@property (nonatomic, readonly) DJTestPriority priority;

@end
