// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#ifdef __cplusplus
#import "DBRecordWithEmbeddedCppProto+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RecordWithEmbeddedCppProto::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::ProtobufPassthrough<::djinni::test2::PersistingState>::toCpp(obj.state)};
}

auto RecordWithEmbeddedCppProto::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBRecordWithEmbeddedCppProto alloc] initWithState:(::djinni::ProtobufPassthrough<::djinni::test2::PersistingState>::fromCpp(cpp.state))];
}

} // namespace djinni_generated
#endif // __cplusplus
