// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#import "DBRecordWithEmbeddedProtoViewModel.h"
#include "RecordWithEmbeddedProto.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBRecordWithEmbeddedProtoViewModel;

namespace djinni_generated {

struct RecordWithEmbeddedProto
{
    using CppType = ::testsuite::RecordWithEmbeddedProto;
    using ObjcType = DBRecordWithEmbeddedProtoViewModel*;

    using Boxed = RecordWithEmbeddedProto;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
