// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proto.djinni

#import "DBRecordWithEmbeddedProto.h"


@implementation DBRecordWithEmbeddedProto

- (nonnull instancetype)initWithPerson:(nonnull DJTestPerson *)person
{
    if (self = [super init]) {
        _person = person;
    }
    return self;
}

+ (nonnull instancetype)RecordWithEmbeddedProtoWithPerson:(nonnull DJTestPerson *)person
{
    return [[self alloc] initWithPerson:person];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p person:%@>", self.class, (void *)self, self.person];
}

#endif
@end
