// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#import "DBRecordWithProtobufEnum.h"


@implementation DBRecordWithProtobufEnum

- (nonnull instancetype)initWithPhoneType:(DJTestPerson_PhoneType)phoneType
                                 priority:(DJTestPriority)priority
{
    if (self = [super init]) {
        _phoneType = phoneType;
        _priority = priority;
    }
    return self;
}

+ (nonnull instancetype)RecordWithProtobufEnumWithPhoneType:(DJTestPerson_PhoneType)phoneType
                                                   priority:(DJTestPriority)priority
{
    return [[self alloc] initWithPhoneType:phoneType
                                  priority:priority];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p phoneType:%@ priority:%@>", self.class, (void *)self, self.phoneType, self.priority];
}

#endif
@end
