// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#import "DBRecordWithFlagsViewModel+Private.h"
#import "DBAccessFlagsViewModel+Private.h"
#include <cassert>

namespace djinni_generated {

auto RecordWithFlags::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::testsuite::access_flags, DBAccessFlagsViewModel>::toCpp(obj.access)};
}

auto RecordWithFlags::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBRecordWithFlagsViewModel alloc] initWithAccess:(::djinni::Enum<::testsuite::access_flags, DBAccessFlagsViewModel>::fromCpp(cpp.access))];
}

} // namespace djinni_generated
