// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#import "DBSetRecordViewModel.h"
#include "set_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSetRecordViewModel;

namespace djinni_generated {

struct SetRecord
{
    using CppType = ::testsuite::SetRecord;
    using ObjcType = DBSetRecordViewModel*;

    using Boxed = SetRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
