// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from provider.djinni

#import <Foundation/Foundation.h>


/** Simple object interface for provider testing */
@interface DBSimpleObject : NSObject

- (int32_t)getValue;

- (nonnull NSString *)getName;

@end
