// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

#import "DBSupportCopyingViewModel.h"


@implementation DBSupportCopyingViewModel

- (nonnull instancetype)initWithX:(int32_t)x
{
    if (self = [super init]) {
        _x = x;
    }
    return self;
}

+ (nonnull instancetype)supportCopyingWithX:(int32_t)x
{
    return [[self alloc] initWithX:x];
}

- (id)copyWithZone:(NSZone *)zone
{
    return self;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p x:%@>", self.class, (void *)self, @(self.x)];
}

#endif
@end
