// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#import "DBTestOptionalExternInterfaceRecordViewModel+Private.h"
#import "DBSampleInterfaceViewModel+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TestOptionalExternInterfaceRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni_generated::SampleInterface>::toCpp(obj.sampleInterface)};
}

auto TestOptionalExternInterfaceRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBTestOptionalExternInterfaceRecordViewModel alloc] initWithSampleInterface:(::djinni::Optional<std::experimental::optional, ::djinni_generated::SampleInterface>::fromCpp(cpp.sample_interface))];
}

} // namespace djinni_generated
