// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from lazy.djinni

#import "DBNestedLazy.h"
#import "DBNestedLazyInterface.h"
#import "DJLazy.h"
#import <Foundation/Foundation.h>
@class DBSimpleObject;


@interface DBTestLazy : NSObject

/** Simple type lazy tests */
+ (nonnull DJLazy<NSString *> *)getLazyString;

+ (nonnull DJLazy<NSNumber *> *)getLazyInt;

+ (nonnull NSString *)callLazyString:(nonnull DJLazy<NSString *> *)x;

+ (int32_t)callLazyInt:(nonnull DJLazy<NSNumber *> *)x;

+ (nonnull DBNestedLazy *)getNestedLazy;

+ (int32_t)callNestedLazy:(nonnull DBNestedLazy *)x;

/** Interface lazy tests - main use case for deferred expensive object creation */
+ (nonnull DJLazy<DBSimpleObject *> *)getLazyObject;

+ (int32_t)callLazyObject:(nonnull DJLazy<DBSimpleObject *> *)x;

+ (nonnull NSString *)callLazyObjectGetName:(nonnull DJLazy<DBSimpleObject *> *)x;

+ (nonnull DBNestedLazyInterface *)getNestedLazyInterface;

+ (int32_t)callNestedLazyInterface:(nonnull DBNestedLazyInterface *)x;

/** Helper to create simple_object for testing */
+ (nullable DBSimpleObject *)createSimpleObject:(int32_t)value
                                           name:(nonnull NSString *)name;

@end
