// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ident_explicit.djinni

#import "DBTestIdentRecord.h"


NSString * __nonnull const DBTestIdentRecordNativeRecordConstValue = @"test";

int32_t const DBTestIdentRecordNativeXXXWeirdCase = 1;

@implementation DBTestIdentRecord

- (nonnull instancetype)initWithFirstValue:(int32_t)FirstValue
                               secondValue:(nonnull NSString *)secondValue
{
    if (self = [super init]) {
        _FirstValue = FirstValue;
        _secondValue = [secondValue copy];
    }
    return self;
}

+ (nonnull instancetype)testIdentRecordWithFirstValue:(int32_t)FirstValue
                                          secondValue:(nonnull NSString *)secondValue
{
    return [[self alloc] initWithFirstValue:FirstValue
                                secondValue:secondValue];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p FirstValue:%@ secondValue:%@>", self.class, (void *)self, @(self.FirstValue), self.secondValue];
}

#endif
@end
