// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from static_method_language.djinni

#import "DBTestStaticMethodLanguageViewModel+Private.h"
#import "DBTestStaticMethodLanguageViewModel.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DBTestStaticMethodLanguageViewModel ()

- (id)initWithCpp:(const std::shared_ptr<::testsuite::TestStaticMethodLanguage>&)cppRef;

@end

@implementation DBTestStaticMethodLanguageViewModel {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::testsuite::TestStaticMethodLanguage>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::testsuite::TestStaticMethodLanguage>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

namespace djinni_generated {

auto TestStaticMethodLanguage::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto TestStaticMethodLanguage::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DBTestStaticMethodLanguageViewModel>(cpp);
}

} // namespace djinni_generated

@end
