// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from interface_and_abstract_class.djinni

#import "DBTestJavaAbstractClassOnly+Private.h"
#import "DBTestJavaAbstractClassOnly.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DBTestJavaAbstractClassOnly ()

- (id)initWithCpp:(const std::shared_ptr<::testsuite::TestJavaAbstractClassOnly>&)cppRef;

@end

@implementation DBTestJavaAbstractClassOnly {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::testsuite::TestJavaAbstractClassOnly>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::testsuite::TestJavaAbstractClassOnly>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (BOOL)testMethod {
    try {
        auto objcpp_result_ = ::testsuite::TestJavaAbstractClassOnly::test_method();
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto TestJavaAbstractClassOnly::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto TestJavaAbstractClassOnly::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DBTestJavaAbstractClassOnly>(cpp);
}

}  // namespace djinni_generated

@end
