// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

#import "DBVec2.h"
#import <Foundation/Foundation.h>


@interface DBTestArray : NSObject

+ (nonnull NSArray<NSString *> *)testStringArray:(nonnull NSArray<NSString *> *)a;

+ (nonnull NSArray<NSNumber *> *)testIntArray:(nonnull NSArray<NSNumber *> *)a;

+ (nonnull NSArray<DBVec2 *> *)testRecordArray:(nonnull NSArray<DBVec2 *> *)a;

+ (nonnull NSArray<NSArray<NSNumber *> *> *)testArrayOfArray:(nonnull NSArray<NSArray<NSNumber *> *> *)a;

@end
