// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ident_explicit.djinni

#import "DBTestRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TestRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.FirstValue),
            ::djinni::String::toCpp(obj.SECONDValue)};
}

auto TestRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBTestRecord alloc] initWithFirstValue:(::djinni::I32::fromCpp(cpp.FirstValue))
                                        SECONDValue:(::djinni::String::fromCpp(cpp.SECOND_Value))];
}

}  // namespace djinni_generated
