// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

#include "test_array.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBTestArray;

namespace djinni_generated {

class TestArray
{
public:
    using CppType = std::shared_ptr<::testsuite::TestArray>;
    using CppOptType = std::shared_ptr<::testsuite::TestArray>;
    using ObjcType = DBTestArray*;

    using Boxed = TestArray;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) {
        if (!cpp) {
            throw std::invalid_argument("TestArray::fromCpp requires a non-null C++ object");
        }
        return fromCppOpt(cpp);
    }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

