// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

#include "throwing_interface.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBThrowingInterfaceViewModel;

namespace djinni_generated {

class ThrowingInterface
{
public:
    using CppType = std::shared_ptr<::testsuite::ThrowingInterface>;
    using CppOptType = std::shared_ptr<::testsuite::ThrowingInterface>;
    using ObjcType = DBThrowingInterfaceViewModel*;

    using Boxed = ThrowingInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

