// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

#import <Foundation/Foundation.h>


@interface DBThrowingInterfaceViewModel : NSObject

- (void)throwException;

@end
