// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

#import <Foundation/Foundation.h>
@class DBJavaOnlyListenerViewModel;
@protocol DBObjcOnlyListenerViewModel;


/**
 * Generating and compiling this makes sure other languages don't break
 * on references to interfaces they don't need.
 */
@protocol DBUsesSingleLanguageListenersViewModel <NSObject>

- (void)callForObjC:(nullable id<DBObjcOnlyListenerViewModel>)l;

- (nullable id<DBObjcOnlyListenerViewModel>)returnForObjC;

- (void)callForJava:(nullable DBJavaOnlyListenerViewModel *)l;

- (nullable DBJavaOnlyListenerViewModel *)returnForJava;

@end
