// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from array.djinni

#import "DBVec2.h"
#include "vec2.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBVec2;

namespace djinni_generated {

struct Vec2
{
    using CppType = ::testsuite::Vec2;
    using ObjcType = DBVec2*;

    using Boxed = Vec2;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
