package djinni

import generatorTools.{Spec, q}

import djinni.ast.{Doc, Field, Ident, Interface, ProtobufMessage, Record, TypeDecl, TypeParam, TypeRef}
import djinni.writer.IndentWriter

class CGenerator(spec: Spec) extends Generator(spec) {

  private val cppMarshal = new CppMarshal(spec)

  private class ResolvedField(val field: Field, val translator: CTypeTranslator)

  private class ResolvedMethod(val resolvedName: String, val method: Interface.Method, val parameters: Seq[ResolvedField], val returnType: Option[CTypeTranslator]) {
    def retTypename: String = if (returnType.isDefined) returnType.get.typename else "void"
  }

  private def resolveSymbolName(name: String): String = {
    return spec.cNamespace + name
  }

  private def resolveRefSymbolTypeName(ident: Ident): String = {
    resolveSymbolName(ident.name) + "_ref"
  }

  def typename(t: TypeDecl): String = {
    t.body match {
      case ast.Enum(_, _) => resolveSymbolName(t.ident.name)
      case Record(_, _, _, _) => resolveRefSymbolTypeName(t.ident)
      case Interface(_, _, _) => resolveRefSymbolTypeName(t.ident)
      case ProtobufMessage(_, _, _, _, _) => "djinni_binary_ref"
    }
  }

  def helperName(t: TypeDecl): String = {
    val typeResolver = new CTypeResolver(t.ident, spec, cppMarshal)
    typeResolver.getTranslatorNameForType(t.ident.name, t.body)
  }

  def publicHeader(t: TypeDecl): String = publicHeader(t.ident)

  def publicHeader(ident: Ident): String = q(spec.cIncludePrefix + ident.name + ".h")

  def privateHeader(t: TypeDecl): String = q(spec.cppIncludePrefix + spec.cppFileIdentStyle(t.ident.name) + "." + spec.cppHeaderExt)

  private def writeExternCBegin(w: IndentWriter): Unit = {
    w.wl("#ifdef __cplusplus")
    w.wl("extern \"C\" {")
    w.wl("#endif // __cplusplus")
  }

  private def writeExternCEnd(w: IndentWriter): Unit = {
    w.wl("#ifdef __cplusplus")
    w.wl("} // extern \"C\"")
    w.wl("#endif // __cplusplus")
  }

  private def writeCFile(origin: String, ident: Ident, ext: String, f: IndentWriter => Unit): Unit = {
    val targetDir = if (ext == "h") spec.cHeaderOutFolder else spec.cOutFolder
    createFile(targetDir.get, ident.name + "." + ext, (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      f(w)
      w.wl
    })
  }

  private def writeCFilePair(origin: String, ident: Ident, publicIncludes: Seq[String], privateIncludes: Seq[String])(header: IndentWriter => Unit, impl: IndentWriter => Unit): Unit = {
    writeCFile(origin, ident, "h", (w: IndentWriter) => {
      w.wl("#pragma once")
      w.wl

      w.wl("#include " + q(spec.cBaseLibIncludePrefix + "djinni_c.h"))
      publicIncludes.foreach(w.wl)

      w.wl

      writeExternCBegin(w)
      w.wl

      header(w)

      writeExternCEnd(w)
    })

    writeCFile(origin, ident, "cpp", (w: IndentWriter) => {
      w.wl(s"""#include ${publicHeader(ident)}""")
      w.wl("#include " + q(spec.cppBaseLibIncludePrefix + "djinni_c_helpers.hpp"))
      privateIncludes.foreach(w.wl)

      w.wl
      impl(w)
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    writeCFilePair(origin, ident, List.empty[String], List.empty[String])((w: IndentWriter) => {
      val symbolName = resolveSymbolName(ident.name)
      val enumCasePrefix = symbolName + "_"
      writeDoc(w, doc)
      w.w("enum " + symbolName)
      w.bracedSemi {
        writeEnumOptionNone(w, e, idCpp.enum, "=", enumCasePrefix)
        writeEnumOptions(w, e, idCpp.enum, "=", enumCasePrefix)
        writeEnumOptionAll(w, e, idCpp.enum, "=", enumCasePrefix)
      }

    }, (w: IndentWriter) => {
    })
  }

  private def writeDelimited[T](w: IndentWriter, seq: Seq[T], delimiter: String)(nested: T => Unit): Unit = {
    val lastIndex = seq.size - 1
    for ((v, i) <- seq.zipWithIndex) {
      nested(v)
      if (i != lastIndex) {
        w.w(delimiter)
      }
    }
  }

  private def writeParamList(w: IndentWriter, params: Seq[(String, String)]): Unit = {
    writeDelimited(w, params, ", ")(t => {
      w.w(t._1)
      w.w(" " + t._2)
    })
  }

  private def writeParamListWithResolvedFields(w: IndentWriter, params: Seq[ResolvedField]): Unit = {
    writeParamList(w, params.map(p => (p.translator.typename, p.field.ident.name)))
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: ast.Record): Unit = {
    val selfCpp = cppMarshal.fqTypename(ident, r)

    val typeResolver = new CTypeResolver(ident, spec, cppMarshal)
    val prefix = resolveSymbolName(ident.name)
    val typeName = resolveRefSymbolTypeName(ident)

    val resolvedFields = r.fields.map(f => (new ResolvedField(f, typeResolver.resolve(f.ty.resolved))))

    writeCFilePair(origin, ident, typeResolver.publicImports.toSeq, typeResolver.privateImports.toSeq)((w: IndentWriter) => {
      writeDoc(w, doc)
      w.wl(s"""typedef djinni_record_ref ${typeName};""")
      w.wl

      w.w(s"""${typeName} ${prefix}_new(""")
      writeParamListWithResolvedFields(w, resolvedFields)
      w.wl(");")

      for (resolvedField <- resolvedFields) {
        val fieldName = resolvedField.field.ident.name
        val fieldTypename = resolvedField.translator.typename
        writeDoc(w, resolvedField.field.doc)
        w.wl(s"""${fieldTypename} ${prefix}_get_${fieldName}(${typeName} instance);""")
        w.wl(s"""void ${prefix}_set_${fieldName}(${typeName} instance, ${fieldTypename} value);""")
        w.wl
      }
    }, (w: IndentWriter) => {
      w.w(s"""${typeName} ${prefix}_new(""")
      writeParamListWithResolvedFields(w, resolvedFields)
      w.wl(") ")

      w.braced {
        w.w(s"""return ::djinni::c_api::Record<${selfCpp}>::make(""")

        writeDelimited(w, resolvedFields, ", ")(t => {
          w.w(t.translator.toCppTranslatorFn(t.field.ident.name))
        })

        w.wl(");")
      }

      w.wl

      val toCppExpr = s"::djinni::c_api::Record<${selfCpp}>::toCpp(instance)"
      for (resolvedField <- resolvedFields) {
        val fieldName = resolvedField.field.ident.name
        val fieldTypename = resolvedField.translator.typename
        w.wl(s"""${fieldTypename} ${prefix}_get_${fieldName}(${typeName} instance)""")
        w.braced {
          val param = s"${toCppExpr}.${idCpp.field(resolvedField.field.ident)}"
          w.wl(s"return ${resolvedField.translator.fromCppTranslatorFn(param)};")
        }
        w.wl
        w.wl(s"""void ${prefix}_set_${fieldName}(${typeName} instance, ${fieldTypename} value)""")
        w.braced {
          val toCppValue = resolvedField.translator.toCppTranslatorFn("value")
          w.wl(s"${toCppExpr}.${idCpp.field(resolvedField.field.ident)} = ${toCppValue};")
        }
        w.wl
      }

    })
  }

  private def isReservedIdentifier(ident: Ident): Boolean = {
    ident.name == "new" || ident.name == "proxy_class_new"
  }

  private def getConvertedParamName(resolvedField: ResolvedField): String = {
    return resolvedField.field.ident.name + "_c"
  }

  private def getReturnNameCpp(name: String): String = {
    return name + "_cpp"
  }

  private def writeProxyClass(w: IndentWriter, ident: Ident, methodDefsStructName: String, resolvedMethods: Seq[ResolvedMethod]): String = {
    val baseProxyClassName = "Proxy_Parent"
    w.wl(s"using ${baseProxyClassName} = ::djinni::Proxy<${methodDefsStructName}>;")
    val cppClassName = spec.cppIdentStyle.ty(ident.name)
    val proxyClassName = s"${cppClassName}_Proxy"
    val baseClassName = withCppNs(cppClassName)
    w.w(s"struct ${proxyClassName}: public ${baseProxyClassName}, public ${baseClassName} ")
    w.bracedSemi {
      w.wl(s"${proxyClassName}(::djinni::ProxyClass<${methodDefsStructName}> *proxyClass, void *opaque): ${baseProxyClassName}(proxyClass, opaque) {}")
      w.wl
      w.wl(s"~${proxyClassName}() override = default;")
      w.wl

      for (resolvedMethod <- resolvedMethods.filter(m => !m.method.static)) {
        val returnType = if (resolvedMethod.retTypename != "void") cppMarshal.fqReturnType(resolvedMethod.method.ret) else "void"
        w.w(s"${returnType} ${resolvedMethod.method.ident.name}(")
        writeParamList(w, resolvedMethod.method.params.map(p => (cppMarshal.fqParamType(p.ty), p.ident.name)))
        w.w(") ")
        if (resolvedMethod.method.const) {
          w.w("const ")
        }
        w.w("override")
        w.braced {
          for (param <- resolvedMethod.parameters) {
            val resolvedExpr = cppMarshal.maybeMove(param.field.ident.name, param.field.ty)
            w.wl(s"auto ${getConvertedParamName(param)} = ${param.translator.fromCppTranslatorFn(resolvedExpr)};")
          }

          val retValueName = "returnValue"
          val needsReturnValue = resolvedMethod.retTypename != "void"
          if (needsReturnValue) {
            w.w(s"auto ${retValueName} = ")
          }

          w.w(s"${baseProxyClassName}::getProxyClass().methodDefs().${resolvedMethod.method.ident.name}(${baseProxyClassName}::getOpaque()")
          if (resolvedMethod.parameters.nonEmpty) {
            w.w(", ")
            w.w(resolvedMethod.parameters.map(p => getConvertedParamName(p)).mkString(", "))
          }
          w.wl(");")

          for (param <- resolvedMethod.parameters) {
            if (param.translator.isRefType) {
              w.wl(s"djinni_ref_release(${getConvertedParamName(param)});")
            }
          }

          if (needsReturnValue) {
            w.wl
            w.wl(s"auto ${getReturnNameCpp(retValueName)} = ${resolvedMethod.returnType.get.toCppTranslatorFn(retValueName)};")
            if (resolvedMethod.returnType.get.isRefType) {
              w.wl(s"djinni_ref_release(${retValueName});")
            }
            w.wl(s"return ${getReturnNameCpp(retValueName)};")
          }

        }

        w.wl
      }
    }
    w.wl

    return proxyClassName
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val selfCpp = cppMarshal.fqTypename(ident, i)
    val typeResolver = new CTypeResolver(ident, spec, cppMarshal)
    val resolvedMethods = i.methods.map(m =>
      new ResolvedMethod(
        if (isReservedIdentifier(m.ident)) m.ident.name + "_2" else m.ident.name,
        m,
        m.params.map(p =>
          new ResolvedField(
            p,
            typeResolver.resolve(p.ty.resolved))
        ),
        m.ret.map(r => typeResolver.resolve(r.resolved))
      ))

    val prefix = resolveSymbolName(ident.name)
    val typeName = resolveRefSymbolTypeName(ident)

    val proxyClassName = s"${resolveSymbolName(ident)}_proxy_class_ref"
    val methodDefsStructName = s"${resolveSymbolName(ident)}_method_defs"
    writeCFilePair(origin, ident, typeResolver.publicImports.toSeq, typeResolver.privateImports.toSeq)((w: IndentWriter) => {
      writeDoc(w, doc)
      w.wl(s"""typedef djinni_interface_ref ${typeName};""")
      w.wl(s"""typedef djinni_proxy_class_ref ${proxyClassName};""")
      w.wl

      w.wl(s"""typedef struct """)
      w.bracedEnd(s" ${methodDefsStructName};") {

        if (resolvedMethods.isEmpty) {
          w.wl("void *reserved[1];")
        } else {
          for (resolvedMethod <- resolvedMethods) {
            w.w(s"""${resolvedMethod.retTypename} (*${resolvedMethod.method.ident.name})(""")
            writeDelimited(w, "void *" +: resolvedMethod.parameters.map(p => p.translator.typename), ", ")(s => w.w(s))
            w.wl(");")
          }
        }
      }
      w.wl

      w.wl(s"${proxyClassName} ${prefix}_proxy_class_new(const ${methodDefsStructName} *method_defs, djinni_opaque_deallocator opaque_deallocator);")
      w.wl
      w.wl(s"${typeName} ${prefix}_new(${proxyClassName} proxy_class, void *opaque);")
      w.wl("")

      for (resolvedMethod <- resolvedMethods) {
        writeDoc(w, resolvedMethod.method.doc)
        w.w(s"${resolvedMethod.retTypename} ${prefix}_${resolvedMethod.resolvedName}(")

        if (resolvedMethod.method.static) {
          writeParamList(w, resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
        } else {
          writeParamList(w, (typeName, "instance") +: resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
        }

        w.wl(");")

        w.wl
      }

    }, (w: IndentWriter) => {
      val proxyClassNameCpp = writeProxyClass(w, ident, methodDefsStructName, resolvedMethods)
      w.w(s"${proxyClassName} ${prefix}_proxy_class_new(const ${methodDefsStructName} *method_defs, djinni_opaque_deallocator opaque_deallocator)")
      w.braced {
        w.wl(s"return ::djinni::c_api::ProxyClass<${methodDefsStructName}>::make(method_defs, opaque_deallocator);")
      }
      w.wl

      w.w(s"${typeName} ${prefix}_new(${proxyClassName} proxy_class, void *opaque)")
      w.braced {
        w.wl(s"return ::djinni::c_api::Proxy<${proxyClassNameCpp}, ${methodDefsStructName}>::make(proxy_class, opaque);")
      }
      w.wl




      for (resolvedMethod <- resolvedMethods) {
        writeDoc(w, resolvedMethod.method.doc)
        w.w(s"${resolvedMethod.retTypename} ${prefix}_${resolvedMethod.resolvedName}(")

        if (resolvedMethod.method.static) {
          writeParamList(w, resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
        } else {
          writeParamList(w, (typeName, "instance") +: resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
        }

        w.wl(")")
        w.braced {
          val needsReturnValue = resolvedMethod.retTypename != "void"

          if (needsReturnValue) {
            w.w(s"auto retValue = ")
          }

          if (resolvedMethod.method.static) {
            w.w(s"""${selfCpp}::${resolvedMethod.method.ident.name}(""")
          } else {
            w.w(s"""::djinni::c_api::Interface<${selfCpp}>::toCpp(instance)->${resolvedMethod.method.ident.name}(""")
          }

          writeDelimited(w, resolvedMethod.parameters, ", ")(p => {
            w.w(p.translator.toCppTranslatorFn(p.field.ident.name))
          })

          w.w(")")

          w.wl(";")
          if (needsReturnValue) {
            w.wl(s"""return ${resolvedMethod.returnType.get.fromCppTranslatorFn("std::move(retValue)")};""")
          }
        }

        w.wl
      }
    })
  }
}
