package djinni

import generatorTools.{Spec, q}

import djinni.ast.{Doc, Field, Ident, Interface, ProtobufMessage, Record, TypeDecl, TypeParam, TypeRef}
import djinni.writer.IndentWriter

class CGenerator(spec: Spec) extends Generator(spec) {

  private val cppMarshal = new CppMarshal(spec)

  private class ResolvedField(val field: Field, val translator: CTypeTranslator)
  private class ResolvedConst(val const: ast.Const, val translator: CTypeTranslator)

  private class ResolvedMethod(val resolvedName: String, val method: Interface.Method, val parameters: Seq[ResolvedField], val returnType: Option[CTypeTranslator]) {
    def retTypename: String = if (returnType.isDefined) returnType.get.typename else "void"
  }

  private def resolveSymbolName(name: String): String = {
    return spec.cNamespace + name
  }

  private def resolveRefSymbolTypeName(ident: Ident): String = {
    resolveSymbolName(ident.name) + "_ref"
  }

  def typename(t: TypeDecl): String = {
    t.body match {
      case ast.Enum(_, _) => resolveSymbolName(t.ident.name)
      case Record(_, _, _, _) => resolveRefSymbolTypeName(t.ident)
      case Interface(_, _, _) => resolveRefSymbolTypeName(t.ident)
      case ProtobufMessage(_, _, _, _, _) => "djinni_binary_ref"
    }
  }

  def helperName(t: TypeDecl): String = {
    val typeResolver = new CTypeResolver(t.ident, spec, cppMarshal)
    typeResolver.getTranslatorNameForType(t.ident.name, t.body)
  }

  def publicHeader(t: TypeDecl): String = publicHeader(t.ident)

  def publicHeader(ident: Ident): String = q(spec.cIncludePrefix + ident.name + ".h")

  def privateHeader(t: TypeDecl): String = q(spec.cppIncludePrefix + spec.cppFileIdentStyle(t.ident.name) + "." + spec.cppHeaderExt)

  private def wrapIfCpp(w: IndentWriter, f: IndentWriter => Unit) = {
    w.wl("#ifdef __cplusplus")
    f(w)
    w.wl("#endif // __cplusplus")
  }
  private def wrapExternC(w: IndentWriter, f: IndentWriter => Unit) = {
    wrapIfCpp(w, (w: IndentWriter) => {
      w.wl("extern \"C\" {")
    })
    w.wl
    f(w)
    wrapIfCpp(w, (w: IndentWriter) => {
      w.wl("} // extern \"C\"")
    })
  }
  private def writeFunctionVisiblity(w: IndentWriter) = {
    if (spec.cWrapperUseDlsym) {
      w.wl(s"""__attribute__((visibility("default")))""")
    }
  }

  private def writeCFile(origin: String, ident: Ident, ext: String, f: IndentWriter => Unit): Unit = {
    val targetDir = if (ext == "h") spec.cHeaderOutFolder else spec.cOutFolder
    createFile(targetDir.get, ident.name + "." + ext, (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      f(w)
      w.wl
    })
  }

  private def writeCFilePair(origin: String, ident: Ident, publicIncludes: Seq[String], privateIncludes: Seq[String])(header: IndentWriter => Unit, impl: IndentWriter => Unit): Unit = {
    writeCFile(origin, ident, "h", (w: IndentWriter) => {
      w.wl("#pragma once")
      w.wl

      w.wl("#include " + q(spec.cBaseLibIncludePrefix + "djinni_c.h"))
      publicIncludes.foreach(w.wl)

      w.wl
      header(w)
    })

    writeCFile(origin, ident, "cpp", (w: IndentWriter) => {
      w.wl(s"""#include ${publicHeader(ident)}""")
      w.wl("#include " + q(spec.cppBaseLibIncludePrefix + "djinni_c_translators.hpp"))
      privateIncludes.foreach(w.wl)

      w.wl
      impl(w)
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    writeCFilePair(origin, ident, List.empty[String], List.empty[String])((w: IndentWriter) => {
      val symbolName = resolveSymbolName(ident.name)
      val enumCasePrefix = symbolName + "_"
      wrapExternC(w, (w: IndentWriter) => {
        writeDoc(w, doc)
        w.w("typedef enum")
        w.bracedEnd(s" ${symbolName};") {
          writeEnumOptionNone(w, e, idCpp.enum, "=", enumCasePrefix)
          writeEnumOptions(w, e, idCpp.enum, "=", enumCasePrefix)
          writeEnumOptionAll(w, e, idCpp.enum, "=", enumCasePrefix)
        }
      })
    }, (w: IndentWriter) => {
    })
  }

  private def writeDelimited[T](w: IndentWriter, seq: Seq[T], delimiter: String)(nested: T => Unit): Unit = {
    val lastIndex = seq.size - 1
    for ((v, i) <- seq.zipWithIndex) {
      nested(v)
      if (i != lastIndex) {
        w.w(delimiter)
      }
    }
  }

  private def writeParamList(w: IndentWriter, params: Seq[(String, String)]): Unit = {
    writeDelimited(w, params, ", ")(t => {
      w.w(t._1)
      w.w(" " + t._2)
    })
  }

  private def writeParamListWithResolvedFields(w: IndentWriter, params: Seq[ResolvedField]): Unit = {
    writeParamList(w, params.map(p => (p.translator.typename, p.field.ident.name)))
  }

  private def generateConstsHeader(typename: String, consts: Seq[ResolvedConst], w: IndentWriter): Unit = {
    for (const <- consts) {
      writeDoc(w, const.const.doc)
      w.wl(s"""${const.translator.typename} ${typename}_get_${const.const.ident.name}();""")
      w.wl
    }
  }

  private def generateConstsImpl(cppTypename: String, typename: String, consts: Seq[ResolvedConst], w: IndentWriter): Unit = {
    for (const <- consts) {
      w.w(s"""${const.translator.typename} ${typename}_get_${const.const.ident.name}()""")
      w.braced {
        val cppValue = s"${cppTypename}::${idCpp.const(const.const.ident)}"
        w.wl(s"""return ${const.translator.fromCpp(cppValue)};""")
      }
      w.wl
    }
  }

  private def writeCppWrapperClass(ident: Ident, w: IndentWriter, methods: IndentWriter => Unit, functionNames: Seq[String]): Unit = {
    val typeName = resolveRefSymbolTypeName(ident)
    val cppClassName = ident.name
    val cppNamespace = spec.cWrapperCppNamespace.getOrElse(spec.cppNamespace + "::c_wrappers")
    val prefix = resolveSymbolName(ident.name)
    val libHandleDefine = s"DJINNI_C_LIB_HANDLE_${prefix}"
    wrapIfCpp(w, (w: IndentWriter) => {
      w.wl("#include <utility>")
      if (spec.cWrapperUseDlsym) {
        w.wl("#include <cassert>")
        w.wl("#include <dlfcn.h>")
        w.wl(s"#if !defined(DJINNI_C_LOAD_SYM_FUNC)")
        w.wl(s"#define DJINNI_C_LOAD_SYM_FUNC dlsym")
        w.wl(s"#endif // !DJINNI_C_LOAD_SYM_FUNC")
        w.wl(s"#if !defined(${libHandleDefine})")
        w.wl(s"#if defined(DJINNI_C_DEFAULT_LIB_HANDLE)")
        w.wl(s"#define ${libHandleDefine} DJINNI_C_DEFAULT_LIB_HANDLE")
        w.wl(s"#else")
        w.wl(s"#define ${libHandleDefine} RTLD_DEFAULT")
        w.wl(s"#endif // DJINNI_C_DEFAULT_LIB_HANDLE")
        w.wl(s"#endif // !${libHandleDefine}")
      }
      wrapNamespace(w, cppNamespace, (w: IndentWriter) => {
          w.w(s"class ${cppClassName}").bracedSemi {
            w.wlOutdent("public:")
            w.wl
            w.wl(s"${cppClassName}(const ${typeName}& ref) : _ref(ref) { djinni_ref_retain(_ref); }")
            w.wl(s"${cppClassName}(${typeName}&& ref) noexcept : _ref(std::move(ref)) {}")
            w.wl(s"${cppClassName}(const ${cppClassName}& other) : _ref(other._ref) { djinni_ref_retain(_ref); }")
            w.wl(s"${cppClassName}(${cppClassName}&& other) : _ref(std::move(other._ref)) { other._ref = nullptr; }")
            w.wl(s"~${cppClassName}() { djinni_ref_release(_ref); }")

            val assignOps =
              s"""${cppClassName}& operator=(const ${cppClassName}& other) {
                |  if (&other != this) {
                |      auto old = _ref;
                |      _ref = other._ref;
                |      djinni_ref_retain(_ref);
                |      djinni_ref_release(old);
                |   }
                |   return *this;
                |}
                |${cppClassName}& operator=(${cppClassName}&& other) noexcept {
                |  if (&other != this) {
                |    auto old = _ref;
                |    _ref = other._ref;
                |    other._ref = nullptr;
                |
                |    djinni_ref_release(old);
                |  }
                |  return *this;
                |}
                |${cppClassName}& operator=(${typeName}&& ref) {
                |  auto old = _ref;
                |  _ref = ref;
                |  djinni_ref_release(old);
                |  return *this;
                |}
                |${cppClassName}& operator=(const ${typeName}& ref) {
                |  auto old = _ref;
                |  _ref = ref;
                |  djinni_ref_retain(ref);
                |  djinni_ref_release(old);
                |  return *this;
                |}""".stripMargin
            assignOps.split("\n").toSeq.foreach(line => w.wl(line))

            w.wl
            w.wl(s"operator const ${typeName}&() const { return _ref; }")
            w.wl(s"const ${typeName}& _djinni_ref() const { return _ref; }")
            w.wl
            methods(w)
            w.wlOutdent("private:")
            w.wl(s"${typeName} _ref;")
            if (spec.cWrapperUseDlsym) {
              w.wl
              // function table
              w.w(s"struct Funcs").bracedSemi {
                for (functionName <- functionNames) {
                  w.wl(s"decltype(&${functionName}) ${functionName};")
                }
              }
              w.wl
              val functionLoads = functionNames.map(functionName =>
                s"""|    reinterpret_cast<decltype(&${functionName})>(loadAndAssert("${functionName}")),""").mkString("\n")
              val functionLoader =
                s"""static inline Funcs* _loadFuncs() {
                |  auto loadAndAssert = [](const char* funcName) {
                |    auto* ptr = DJINNI_C_LOAD_SYM_FUNC(${libHandleDefine}, funcName);
                |    assert(ptr && "Failed to load djinni C functions for class ${cppNamespace}::${cppClassName}");
                |    return ptr;
                |  };
                |  static Funcs funcs {
                ${functionLoads}
                |  };
                |  return &funcs;
                |}""".stripMargin
              functionLoader.split("\n").toSeq.foreach(line => w.wl(line))
            }
          }
        })
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: ast.Record): Unit = {
    val selfCpp = cppMarshal.fqTypename(ident, r)

    val typeResolver = new CTypeResolver(ident, spec, cppMarshal)
    val prefix = resolveSymbolName(ident.name)
    val typeName = resolveRefSymbolTypeName(ident)

    val resolvedFields = r.fields.map(f => (new ResolvedField(f, typeResolver.resolve(f.ty.resolved))))
    val resolvedConsts = r.consts.map(r => new ResolvedConst(r, typeResolver.resolve(r.ty.resolved)))

    writeCFilePair(origin, ident, typeResolver.publicImports.toSeq, typeResolver.privateImports.toSeq)((w: IndentWriter) => {
      wrapExternC(w, (w: IndentWriter) => {
        writeDoc(w, doc)
        w.wl(s"""typedef djinni_record_ref ${typeName};""")
        w.wl

        writeFunctionVisiblity(w)
        w.w(s"""${typeName} ${prefix}_new(""")
        writeParamListWithResolvedFields(w, resolvedFields)
        w.wl(");")
        w.wl

        generateConstsHeader(prefix, resolvedConsts, w)

        for (resolvedField <- resolvedFields) {
          val fieldName = resolvedField.field.ident.name
          val fieldTypename = resolvedField.translator.typename
          writeDoc(w, resolvedField.field.doc)
          writeFunctionVisiblity(w)
          w.wl(s"""${fieldTypename} ${prefix}_get_${fieldName}(${typeName} instance);""")
          writeFunctionVisiblity(w)
          w.wl(s"""void ${prefix}_set_${fieldName}(${typeName} instance, ${fieldTypename} value);""")
          w.wl
        }
      })

      if (spec.cWrapperCppNamespace.isDefined) {
        val loadFuncPtr = if (spec.cWrapperUseDlsym) "_loadFuncs()->" else ""
        w.wl
        val functionNames = Seq(s"${prefix}_new") ++ resolvedFields.flatMap(resolvedField => {
          val fieldName = resolvedField.field.ident.name
          Seq(s"${prefix}_get_${fieldName}", s"${prefix}_set_${fieldName}")
        })
        writeCppWrapperClass(ident, w, (w: IndentWriter) => {
          w.w(s"static ${ident.name} make(")
          writeParamListWithResolvedFields(w, resolvedFields)
          w.w(")")
          w.braced {
            w.w(s"return ${loadFuncPtr}${prefix}_new(")
            w.w(resolvedFields.map(p => p.field.ident.name).mkString(", "))
            w.wl(");")
          }
          w.wl
          for (resolvedField <- resolvedFields) {
            val fieldName = resolvedField.field.ident.name
            val fieldTypename = resolvedField.translator.typename
            w.w(s"${fieldTypename} ${fieldName}() const")
            w.braced {
              w.wl(s"return ${loadFuncPtr}${prefix}_get_${fieldName}(_ref);")
            }
            w.wl
            w.w(s"${ident.name}& ${fieldName}(${fieldTypename} value)")
            w.braced {
              w.wl(s"${loadFuncPtr}${prefix}_set_${fieldName}(_ref, value);")
              w.wl("return *this;")
            }
            w.wl
          }
        }, functionNames)
      }
    }, (w: IndentWriter) => {
      w.w(s"""${typeName} ${prefix}_new(""")
      writeParamListWithResolvedFields(w, resolvedFields)
      w.wl(") ")

      w.braced {
        w.w(s"""return ::djinni::c_api::RecordTranslator<${selfCpp}>::make(""")

        writeDelimited(w, resolvedFields, ", ")(t => {
          w.w(t.translator.toCpp(t.field.ident.name))
        })

        w.wl(");")
      }

      w.wl

      generateConstsImpl(selfCpp, prefix, resolvedConsts, w)

      val toCppExpr = s"::djinni::c_api::RecordTranslator<${selfCpp}>::toCpp(instance)"
      for (resolvedField <- resolvedFields) {
        val fieldName = resolvedField.field.ident.name
        val fieldTypename = resolvedField.translator.typename
        w.wl(s"""${fieldTypename} ${prefix}_get_${fieldName}(${typeName} instance)""")
        w.braced {
          val param = s"${toCppExpr}.${idCpp.field(resolvedField.field.ident)}"
          w.wl(s"return ${resolvedField.translator.fromCpp(param)};")
        }
        w.wl
        w.wl(s"""void ${prefix}_set_${fieldName}(${typeName} instance, ${fieldTypename} value)""")
        w.braced {
          val toCppValue = resolvedField.translator.toCpp("value")
          w.wl(s"${toCppExpr}.${idCpp.field(resolvedField.field.ident)} = ${toCppValue};")
        }
        w.wl
      }
    })
  }

  private def isReservedIdentifier(ident: Ident): Boolean = {
    ident.name == "new" || ident.name == "proxy_class_new"
  }

  private def getConvertedParamName(resolvedField: ResolvedField): String = {
    return resolvedField.field.ident.name + "_c"
  }

  private def writeProxyClass(w: IndentWriter, ident: Ident, methodDefsStructName: String, resolvedMethods: Seq[ResolvedMethod]): String = {
    val baseProxyClassName = "Proxy_Parent"
    w.wl(s"using ${baseProxyClassName} = ::djinni::Proxy<${methodDefsStructName}>;")
    val cppClassName = spec.cppIdentStyle.ty(ident.name)
    val proxyClassName = s"${cppClassName}_Proxy"
    val baseClassName = withCppNs(cppClassName)
    w.w(s"struct ${proxyClassName}: public ${baseProxyClassName}, public ${baseClassName} ")
    w.bracedSemi {
      w.wl(s"${proxyClassName}(::djinni::ProxyClass<${methodDefsStructName}> *proxyClass, void *opaque): ${baseProxyClassName}(proxyClass, opaque) {}")
      w.wl
      w.wl(s"~${proxyClassName}() override = default;")
      w.wl

      for (resolvedMethod <- resolvedMethods.filter(m => !m.method.static)) {
        val returnType = if (resolvedMethod.retTypename != "void") cppMarshal.fqReturnType(resolvedMethod.method.ret) else "void"
        w.w(s"${returnType} ${resolvedMethod.method.ident.name}(")
        writeParamList(w, resolvedMethod.method.params.map(p => (cppMarshal.fqParamType(p.ty), p.ident.name)))
        w.w(") ")
        if (resolvedMethod.method.const) {
          w.w("const ")
        }
        w.w("override")
        w.braced {
          for (param <- resolvedMethod.parameters) {
            val resolvedExpr = cppMarshal.maybeMove(param.field.ident.name, param.field.ty)

            if (param.translator.isRefType) {
              w.wl(s"auto ${getConvertedParamName(param)} = ::djinni::c_api::Ref(${param.translator.fromCpp(resolvedExpr)});")
            } else {
              w.wl(s"auto ${getConvertedParamName(param)} = ${param.translator.fromCpp(resolvedExpr)};")
            }
          }

          val retValueName = "returnValue"
          val needsReturnValue = resolvedMethod.retTypename != "void"
          if (needsReturnValue) {
            w.w(s"auto ${retValueName} = ")

            if (resolvedMethod.returnType.get.isRefType) {
              w.w("::djinni::c_api::Ref(")
            }
          }

          w.w(s"${baseProxyClassName}::getProxyClass().methodDefs().${resolvedMethod.method.ident.name}(${baseProxyClassName}::getOpaque()")
          if (resolvedMethod.parameters.nonEmpty) {
            w.w(", ")
            w.w(resolvedMethod.parameters.map(p => if (p.translator.isRefType) getConvertedParamName(p) + ".get()" else getConvertedParamName(p)).mkString(", "))
          }

          if (needsReturnValue) {
            if (resolvedMethod.returnType.get.isRefType) {
              w.w("));")
            } else {
              w.wl(");")
            }
            w.wl

            if (resolvedMethod.returnType.get.isRefType) {
              w.wl(s"return ${resolvedMethod.returnType.get.toCpp(retValueName + ".get()")};")
            } else {
              w.wl(s"return ${resolvedMethod.returnType.get.toCpp(retValueName)};")
            }
          } else {
            w.wl(");")
          }

        }

        w.wl
      }
    }
    w.wl

    return proxyClassName
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val selfCpp = cppMarshal.fqTypename(ident, i)
    val typeResolver = new CTypeResolver(ident, spec, cppMarshal)
    val resolvedMethods = i.methods.map(m =>
      new ResolvedMethod(
        if (isReservedIdentifier(m.ident)) m.ident.name + "_2" else m.ident.name,
        m,
        m.params.map(p =>
          new ResolvedField(
            p,
            typeResolver.resolve(p.ty.resolved))
        ),
        m.ret.map(r => typeResolver.resolve(r.resolved))
      ))
    val resolvedConsts = i.consts.map(r => new ResolvedConst(r, typeResolver.resolve(r.ty.resolved)))

    val prefix = resolveSymbolName(ident.name)
    val typeName = resolveRefSymbolTypeName(ident)

    val proxyClassName = s"${resolveSymbolName(ident)}_proxy_class_ref"
    val methodDefsStructName = s"${resolveSymbolName(ident)}_method_defs"
    writeCFilePair(origin, ident, typeResolver.publicImports.toSeq, typeResolver.privateImports.toSeq)((w: IndentWriter) => {
      wrapExternC(w, (w: IndentWriter) => {
        writeDoc(w, doc)
        w.wl(s"""typedef djinni_interface_ref ${typeName};""")

        if (i.ext.cc) {
          w.wl(s"""typedef djinni_proxy_class_ref ${proxyClassName};""")
          w.wl

          w.wl(s"""typedef struct """)
          w.bracedEnd(s" ${methodDefsStructName};") {

            if (resolvedMethods.isEmpty) {
              w.wl("void *reserved[1];")
            } else {
              for (resolvedMethod <- resolvedMethods) {
                w.w(s"""${resolvedMethod.retTypename} (*${resolvedMethod.method.ident.name})(""")
                writeDelimited(w, "void *" +: resolvedMethod.parameters.map(p => p.translator.typename), ", ")(s => w.w(s))
                w.wl(");")
              }
            }
          }
          w.wl

          writeFunctionVisiblity(w)
          w.wl(s"${proxyClassName} ${prefix}_proxy_class_new(const ${methodDefsStructName} *method_defs, djinni_opaque_deallocator opaque_deallocator);")
          w.wl
          writeFunctionVisiblity(w)
          w.wl(s"${typeName} ${prefix}_new(${proxyClassName} proxy_class, void *opaque);")
          w.wl("")
        } else {
          w.wl
        }

        generateConstsHeader(prefix, resolvedConsts, w)

        for (resolvedMethod <- resolvedMethods) {
          writeDoc(w, resolvedMethod.method.doc)
          writeFunctionVisiblity(w)
          w.w(s"${resolvedMethod.retTypename} ${prefix}_${resolvedMethod.resolvedName}(")

          if (resolvedMethod.method.static) {
            writeParamList(w, resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
          } else {
            writeParamList(w, (typeName, "instance") +: resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
          }

          w.wl(");")

          w.wl
        }
      })

      if (i.ext.cpp && spec.cWrapperCppNamespace.isDefined) {
        val loadFuncPtr = if (spec.cWrapperUseDlsym) "_loadFuncs()->" else ""
        w.wl
        val functionNames = resolvedMethods.map(resolvedMethod => s"${prefix}_${resolvedMethod.resolvedName}")
        writeCppWrapperClass(ident, w, (w: IndentWriter) => {
          for (resolvedMethod <- resolvedMethods) {
            if (resolvedMethod.method.static) {
              w.w("static ")
            }
            w.w(s"${resolvedMethod.retTypename} ${resolvedMethod.resolvedName}(")
            writeParamList(w, resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
            w.w(") ")
            w.braced {
              val argsList = resolvedMethod.parameters.map(p => (p.field.ident.name))
              val fullArgsList = if (resolvedMethod.method.static) argsList else "_ref" +: argsList
              if (resolvedMethod.retTypename != "void") {
                w.w("return ")
              }
              w.wl(s"${loadFuncPtr}${prefix}_${resolvedMethod.resolvedName}(${fullArgsList.mkString(", ")});")
            }
            w.wl
            }
        }, functionNames)
      }
    }, (w: IndentWriter) => {
      if (i.ext.cc) {
        val proxyClassNameCpp = writeProxyClass(w, ident, methodDefsStructName, resolvedMethods)
        w.w(s"${proxyClassName} ${prefix}_proxy_class_new(const ${methodDefsStructName} *method_defs, djinni_opaque_deallocator opaque_deallocator)")
        w.braced {
          w.wl(s"return ::djinni::c_api::InterfaceTranslator<${selfCpp}>::makeProxyClass<${methodDefsStructName}>(method_defs, opaque_deallocator);")
        }
        w.wl

        w.w(s"${typeName} ${prefix}_new(${proxyClassName} proxy_class, void *opaque)")
        w.braced {
          w.wl(s"return ::djinni::c_api::InterfaceTranslator<${selfCpp}>::makeProxy<${methodDefsStructName}, ${proxyClassNameCpp}>(proxy_class, opaque);")
        }
        w.wl
      }

      generateConstsImpl(selfCpp, prefix, resolvedConsts, w)

      for (resolvedMethod <- resolvedMethods) {
        writeDoc(w, resolvedMethod.method.doc)
        w.w(s"${resolvedMethod.retTypename} ${prefix}_${resolvedMethod.resolvedName}(")

        if (resolvedMethod.method.static) {
          writeParamList(w, resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
        } else {
          writeParamList(w, (typeName, "instance") +: resolvedMethod.parameters.map(p => (p.translator.typename, p.field.ident.name)))
        }

        w.wl(")")
        w.braced {
          w.wl("DJINNI_HANDLE_EXCEPTION_PROLOGUE")
              val needsReturnValue = resolvedMethod.retTypename != "void"

          if (needsReturnValue) {
            w.w(s"auto retValue = ")
          }

          if (resolvedMethod.method.static) {
            w.w(s"""${selfCpp}::${resolvedMethod.method.ident.name}(""")
          } else {
            w.w(s"""::djinni::c_api::InterfaceTranslator<${selfCpp}>::toCpp(instance)->${resolvedMethod.method.ident.name}(""")
          }

          writeDelimited(w, resolvedMethod.parameters, ", ")(p => {
            w.w(p.translator.toCpp(p.field.ident.name))
          })

          w.w(")")

          w.wl(";")
          if (needsReturnValue) {
            w.wl(s"""return ${resolvedMethod.returnType.get.fromCpp("std::move(retValue)")};""")
          }

          w.wl(s"DJINNI_HANDLE_EXCEPTION_EPILOGUE(${resolvedMethod.retTypename})")

        }

        w.wl
      }
    })
  }
}
