// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativeConversation.hpp"  // my header

namespace djinni_generated {

auto NativeConversation::toCpp(const JsType& j) -> CppType {
    return {::djinni::Binary::Boxed::toCpp(j["id"])};
}
auto NativeConversation::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::Binary::Boxed::fromCpp(c.id));
    return js;
}

}  // namespace djinni_generated
