name: Build and Test

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Bazel cache directory
        id: bazel-cache-dir
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "dir=/private/var/tmp/_bazel_$USER" >> $GITHUB_OUTPUT
          else
            echo "dir=~/.cache/bazel" >> $GITHUB_OUTPUT
          fi
      
      - name: Cache bazel build results
        uses: actions/cache@v3
        with:
          path: ${{ steps.bazel-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', 'MODULE.bazel', 'MODULE.bazel.lock') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: bazel build //src:djinni

      - name: Generate examples / check clean output
        run: ./ci/generate.sh

      - name: Test
        run: ./ci/run-tests.sh

      - name: External Test
        working-directory: external-test
        run: bazel run @snap_djinni//src:djinni -- --help
